erDiagram
    BOOKINGS {
        string booking_id PK
        string user_id
        string hotel_id
        string room_number
        date start_date
        date end_date
        string hotel_name
    }