erDiagram
State{
	bounded-context simulation-engine}
Event{
	bounded-context simulation-engine}
Entity
State ||--o{ Entity : "is stored"
Event |{--o{ Entity : "lifecycle's controlled by "
Entity ||--|| Entity-state : "is described with"
Entity ||--|| Life-status : "has lifecycle described with"
