---
title: IFA
---
erDiagram
    EVENT many--one VENUE : "takes place at"
    COMPETITOR zero or more--zero or more EVENT : "entrant"
    COMPETITOR one or zero--one USER :  ""
    ORGANISER one or many--many EVENT : "organises"
    ORGANISER  one or zero--one USER :  ""
