erDiagram
    PATIENT ||--o{ REVIEW : leaves
    PATIENT ||..o{ TIME_SLOT : selects
    DOCTOR ||--o{ REVIEW : receives
    DOCTOR ||--o{ TIME_SLOT : creates
    DOCTOR{
        int id PK
        string first_name
        string last_name
        string specialization
        string username UK
        string email UK
        string phone_number UK
        string password
        string address
        float average_rating "not stored in the DB"
        datetime date_joined
        datetime last_login
    }
    PATIENT{
        int id PK
        string ssn UK
        string first_name
        string last_name
        date date_born
        string username UK
        string email UK
        string password
        datetime date_joined
        datetime last_login
    }
    REVIEW{
        int id PK
        int rating "from 0 to 5"
        string comment "optional"
        int patient FK
        int doctor FK
        date date_left "set automatically"
    }
    TIME_SLOT{
        int id PK
        date day
        time beginning
        time end
        int doctor FK
        int patient FK "optional"
        bool is_booked "not stored in the DB"
        bool is_confirmed "defaults to False"
        bool is_cancelled "defaults to False"
    }

