erDiagram
    LIBRARY ||--o{ BOOK : contains
    LIBRARY {
        int id
        string name
        string metadata
    }
    BOOK {
        int id
        int libraryId
        string serialnumber
        string title
        string author
        string description
        ennum category
        ennum onlineStatus
        bool reserved
    }
    USER }o--o{ LIBRARY : accesses
    USER {
        int id
        string username
        string password
        string email
    }

    USER ||--|| CART : has
    CART {
        int id
        int userId
        Book books
    }

    CART }o--o{ BOOK : contains
