erDiagram
    icd9_mapping {
        icd9_code TEXT
        icd9_description TEXT
    }
    patient_info {
        patient_id UNDEFINED
        gender UNDEFINED
        age UNDEFINED
    }
    patient_diagnosis {
        patient_id UNDEFINED
        diagnosis_code UNDEFINED
    }
