erDiagram
    bank_card {
        integer bank_card_id PK 
        character_varying card_number 
        character_varying cardholder_name 
        integer client_id FK 
        character_varying cvv 
        date expires_at 
    }

    client {
        integer client_id PK 
        timestamp_without_time_zone created_at 
        character_varying email_address UK 
        character_varying first_name 
        character_varying last_name 
        character_varying password_hash 
        character_varying patronymic 
        character_varying phone_number 
        character_varying profile_picture_url 
    }

    employee {
        integer client_id FK 
        integer employee_id PK 
        employee_type employee_type 
        timestamp_without_time_zone left_at 
    }

    gym {
        character_varying building 
        character_varying city 
        text description 
        integer gym_id PK 
        character_varying street 
    }

    membership {
        integer client_id FK 
        timestamp_without_time_zone created_at 
        timestamp_without_time_zone expires_at 
        timestamp_without_time_zone freezed_at 
        level_type level_type 
        integer membership_id PK 
    }

    membership_payment_history {
        integer client_id FK 
        timestamp_without_time_zone created_at 
        integer membership_id FK 
        integer membership_payment_history_id PK 
        integer payment_history_id FK 
    }

    payment_history {
        integer bank_card_id FK 
        integer client_id FK 
        timestamp_without_time_zone created_at 
        integer payment_history_id PK 
        timestamp_without_time_zone processed_at 
        boolean revoked 
        integer value 
    }

    session {
        integer client_id FK 
        timestamp_without_time_zone created_at 
        timestamp_without_time_zone expires_at 
        text jwt UK 
        boolean revoked 
        integer session_id PK 
    }

    trainer_appointment {
        timestamp_without_time_zone appointed_at 
        integer client_id FK 
        timestamp_without_time_zone created_at 
        integer employee_id FK 
        timestamp_without_time_zone ends_at 
        integer gym_id FK 
        integer payment_history_id FK 
        boolean revoked 
        integer trainer_appointment_id PK 
    }

    visit_history {
        integer client_id FK 
        timestamp_without_time_zone entered_at 
        integer gym_id FK 
        timestamp_without_time_zone left_at 
        integer visit_history_id PK 
    }

    bank_card }o--|| client : "client_id"
    payment_history }o--|| bank_card : "bank_card_id"
    employee }o--|| client : "client_id"
    membership }o--|| client : "client_id"
    membership_payment_history }o--|| client : "client_id"
    payment_history }o--|| client : "client_id"
    session }o--|| client : "client_id"
    trainer_appointment }o--|| client : "client_id"
    visit_history }o--|| client : "client_id"
    trainer_appointment }o--|| employee : "employee_id"
    trainer_appointment }o--|| gym : "gym_id"
    visit_history }o--|| gym : "gym_id"
    membership_payment_history }o--|| membership : "membership_id"
    membership_payment_history }o--|| payment_history : "payment_history_id"
    trainer_appointment }o--|| payment_history : "payment_history_id"
