erDiagram
   	RANDOM-VARIABLE o{--o{ EVENT-EXECUTION : "realizes"
   	EVENT-EXECUTION o{--|| EVENT : "realizes"
    EVENT-EXECUTION ||--o{ STATE : "modifies"
    EVENT-EXECUTION ||--o{ FUTURE_EVENT : "modifies"
