erDiagram
    MODEL{
        aggregate-root yes}
    MIDDLEWARES {
        value-object yes}
    MIDDLEWARE {
        value-object yes}
    SNAPSHOT {
        iteration int
        value-object yes}
    ORDERING {
  	    value-object yes}
    REGISTRY {
  	    value-object yes}
    EVENT-EXECUTION {
  	    value-object yes}
    PAST-EVENT {
  	    value-object yes}
    FUTURE-EVENT {
  	    value-object yes}
    STATE {
  	    value-object yes}
    EVENT {
  	    value-object yes}
  	DATE {
  	    value-object yes}
    MODEL ||--|| MIDDLEWARES : ""
    MIDDLEWARES ||--o{ MIDDLEWARE : ""
    MODEL ||--|| SNAPSHOT : ""
    MODEL  ||--|| ORDERING : ""
    MODEL  ||--|| REGISTRY : ""
    REGISTRY ||--|{ EVENT-EXECUTION : ""
    SNAPSHOT ||--o{ FUTURE-EVENT : ""
    SNAPSHOT ||--o{ PAST-EVENT : ""
    SNAPSHOT ||--|| STATE : ""
    FUTURE-EVENT ||--|{ EVENT : ""
    PAST-EVENT ||--|{ EVENT : ""
    SNAPSHOT ||--|| DATE : ""
    EVENT ||--|| DATE : ""
