erDiagram
    OFFENDER_CSIP_REPORTS ||--o{ OFFENDER_CSIP_FACTORS : has
    OFFENDER_CSIP_REPORTS ||--o{ OFFENDER_CSIP_INTVW : has
    OFFENDER_CSIP_REPORTS ||--o{ OFFENDER_CSIP_PLANS : has
    OFFENDER_CSIP_REPORTS ||--o{ OFFENDER_CSIP_REVIEWS : has
    OFFENDER_CSIP_REVIEWS ||--o{ OFFENDER_CSIP_ATTENDEES : has

OFFENDER_CSIP_REPORTS {
    NUMBER(10) CSIP_ID PK "NOT NULL"
    NUMBER(10) ROOT_OFFENDER_ID "NOT NULL"
    NUMBER(10) OFFENDER_BOOK_ID FK
    DATER FR_INCIDENT_DATE "NOT NULL"
    DATE RFR_INCIDENT_TIME
    VARCHAR2(12) RFR_INCIDENT_TYPE "NOT NULL"
    VARCHAR2(40) RFR_INCIDENT_LOCATION "NOT NULL"
    VARCHAR2(12) RFR_CSIP_FUNCTION "NOT NULL"
    VARCHAR2(240) RFR_REPORTED_BY
    DATE RFR_DATE_REPORTED
    VARCHAR2(4000) RFR_COMMENT
    VARCHAR2(1) RFR_PROACTIVE_RESPONSE "DEFAULT ('N')"
    VARCHAR2(1) RFR_STAFF_ASSAULTED "DEFAULT ('N')"
    VARCHAR2(1000) RFR_STAFF_NAME
    VARCHAR2(12) CDR_OUTCOME
    VARCHAR2(100) CDR_OUTCOME_RECORDED_BY
    DATE CDR_OUTCOME_DATE
    VARCHAR2(4000) CDR_OTHER_INFORMATION
    VARCHAR2(4000) CDR_CONCERN_DESCRIPTION
    VARCHAR2(4000) INV_KNOWN_REASONS
    VARCHAR2(4000) INV_PERSONS_TRIGGER
    VARCHAR2(4000) INV_STAFF_INVOLVED
    VARCHAR2(4000) INV_EVIDENCE_SECURED
    VARCHAR2(4000) INV_CONCLUSION
    VARCHAR2(4000) INV_NEXT_STEPS
    VARCHAR2(12) INV_OUTCOME
    VARCHAR2(12) INV_SIGNED_OFF_BY
    VARCHAR2(100) INV_NAME
    VARCHAR2(100) INV_OUTCOME_RECORDED_BY
    DATE INV_OUTCOME_DATE
    VARCHAR2(1) INV_NON_ASSOC_UPDATED "DEFAULT ('N')"
    VARCHAR2(1) INV_OBSERVATION_BOOK "DEFAULT ('N')"
    VARCHAR2(1) INV_MOVE "DEFAULT ('N')"
    VARCHAR2(1) INV_REVIEW "DEFAULT ('N')"
    VARCHAR2(1) INV_SERVICE_REFERRAL "DEFAULT ('N')"
    VARCHAR2(1) INV_SIM_REFERRAL "DEFAULT ('N')"
    VARCHAR2(4000) INV_OTHER
    VARCHAR2(4000) INV_OCCURRENCE_REASON
    VARCHAR2(4000) INV_USUAL_BEHAVIOUR
    VARCHAR2(4000) INV_PROTECTIVE_FACTORS
    VARCHAR2(12) CDR_INVOLVEMENT
    VARCHAR2(1) CDR_SENT_DENT "DEFAULT ('N')"
    VARCHAR2(1) INV_NOMIS_CASE_NOTE  "DEFAULT ('N')"
    VARCHAR2(10) CSIP_SEQ
    DATE CDR_RELEASE_DATE
    TIMESTAMP(9) CREATE_DATETIME "NOT NULL DEFAULT SYSTIMESTAMP"
    VARCHAR2(32) CREATE_USER_ID "NOT NULL DEFAULT USER"
    TIMESTAMP(9) MODIFY_DATETIME
    VARCHAR2(32) MODIFY_USER_ID
    TIMESTAMP(9) AUDIT_TIMESTAMP
    VARCHAR2(32) AUDIT_USER_ID
    VARCHAR2(65) AUDIT_MODULE_NAME
    VARCHAR2(64) AUDIT_CLIENT_USER_ID
    VARCHAR2(39) AUDIT_CLIENT_IP_ADDRESS
    VARCHAR2(64) AUDIT_CLIENT_WORKSTATION_NAME
    VARCHAR2(256) AUDIT_ADDITIONAL_INFO
    VARCHAR2(100) CASE_MANAGER
    VARCHAR2(240) REASON
    VARCHAR2(6) AGY_LOC_ID FK "Records AGY_LOC_ID at point of CSIP creation. Released 15/12/2018 under DB_V11.2.1.1.71. Null before this date"
    VARCHAR2(4000) CDR_DECISION_REASON
    VARCHAR2(1) REFERRAL_COMPLETE_FLAG "DEFAULT ('N')"
    VARCHAR2(32) REFERRAL_COMPLETED_BY
    DATE REFERRAL_COMPLETED_DATE
    VARCHAR2(1) OPEN_CSIP_ALERT "DEFAULT ('N')"
    DATE CASE_REV_DATE
}

OFFENDER_CSIP_FACTORS {
    NUMBER(10) CSIP_ID FK "NOT NULL"
    NUMBER(10) CSIP_FACTOR_ID PK "NOT NULL"
    VARCHAR2(12) CSIP_FACTOR "NOT NULL. Reference data code from the CSIP_FAC domain"
    VARCHAR2(4000) COMMENTS
    TIMESTAMP(9) CREATE_DATETIME "NOT NULL DEFAULT SYSTIMESTAMP"
    VARCHAR2(32) CREATE_USER_ID "NOT NULL DEFAULT USER"
    TIMESTAMP(9) MODIFY_DATETIME
    VARCHAR2(32) MODIFY_USER_ID
    TIMESTAMP(9) AUDIT_TIMESTAMP
    VARCHAR2(32) AUDIT_USER_ID
    VARCHAR2(65) AUDIT_MODULE_NAME
    VARCHAR2(64) AUDIT_CLIENT_USER_ID
    VARCHAR2(39) AUDIT_CLIENT_IP_ADDRESS
    VARCHAR2(64) AUDIT_CLIENT_WORKSTATION_NAME
    VARCHAR2(256) AUDIT_ADDITIONAL_INFO
}

OFFENDER_CSIP_INTVW {
    NUMBER(10) CSIP_ID FK "NOT NULL"
    NUMBER(10) CSIP_INTVW_ID PK "NOT NULL"
    VARCHAR2(100)  CSIP_INTERVIEWEE "NOT NULL"
    DATE INTVW_DATE
    VARCHAR2(12) INTVW_ROLE "NOT NULL"
    VARCHAR2(4000) COMMENTS
    TIMESTAMP(9) CREATE_DATETIME "NOT NULL DEFAULT SYSTIMESTAMP"
    VARCHAR2(32) CREATE_USER_ID "NOT NULL DEFAULT USER"
    TIMESTAMP(9) MODIFY_DATETIME
    VARCHAR2(32) MODIFY_USER_ID
    TIMESTAMP(9) AUDIT_TIMESTAMP
    VARCHAR2(32) AUDIT_USER_ID
    VARCHAR2(65) AUDIT_MODULE_NAME
    VARCHAR2(64) AUDIT_CLIENT_USER_ID
    VARCHAR2(39) AUDIT_CLIENT_IP_ADDRESS
    VARCHAR2(64) AUDIT_CLIENT_WORKSTATION_NAME
    VARCHAR2(256) AUDIT_ADDITIONAL_INFO
}

OFFENDER_CSIP_PLANS {
    NUMBER(10) CSIP_ID FK "NOT NULL"
    NUMBER(10) PLAN_ID PK "NOT NULL"
    DATE CREATE_DATE "NOT NULL"
    DATE TARGET_DATE "NOT NULL"
    DATE CLOSED_DATE
    VARCHAR2(1000) IDENTIFIED_NEED "NOT NULL"
    VARCHAR2(4000) PROGRESSION
    VARCHAR2(4000) INTERVENTION "NOT NULL"
    VARCHAR2(100) BY_WHOM "NOT NULL"
    TIMESTAMP(9) CREATE_DATETIME "NOT NULL DEFAULT SYSTIMESTAMP"
    VARCHAR2(32) CREATE_USER_ID "NOT NULL DEFAULT USER"
    TIMESTAMP(9) MODIFY_DATETIME
    VARCHAR2(32) MODIFY_USER_ID
    TIMESTAMP(9) AUDIT_TIMESTAMP
    VARCHAR2(32) AUDIT_USER_ID
    VARCHAR2(65) AUDIT_MODULE_NAME
    VARCHAR2(64) AUDIT_CLIENT_USER_ID
    VARCHAR2(39) AUDIT_CLIENT_IP_ADDRESS
    VARCHAR2(64) AUDIT_CLIENT_WORKSTATION_NAME
    VARCHAR2(256) AUDIT_ADDITIONAL_INFO
}

OFFENDER_CSIP_REVIEWS {
    NUMBER(10) CSIP_ID FK "NOT NULL"
    NUMBER(10) REVIEW_ID PK "NOT NULL"
    NUMBER(10) REVIEW_SEQ "NOT NULL"
    DATE CREATE_DATE
    DATE NEXT_REVIEW_DATE
    DATE CLOSE_DATE
    VARCHAR2(1) REMAIN_ON_CSIP "DEFAULT ('N')"
    VARCHAR2(1) CSIP_UPDATED "DEFAULT ('N')"
    VARCHAR2(1) CASE_NOTE "DEFAULT ('N')"
    VARCHAR2(1) CLOSE_CSIP "DEFAULT ('N')"
    VARCHAR2(4000) SUMMARY
    VARCHAR2(32) CREATE_USER
    VARCHAR2(1) PEOPLE_INFORMED "DEFAULT ('N')"
    TIMESTAMP(9) CREATE_DATETIME "NOT NULL DEFAULT SYSTIMESTAMP"
    VARCHAR2(32) CREATE_USER_ID "NOT NULL DEFAULT USER"
    TIMESTAMP(9) MODIFY_DATETIME
    VARCHAR2(32) MODIFY_USER_ID
    TIMESTAMP(9) AUDIT_TIMESTAMP
    VARCHAR2(32) AUDIT_USER_ID
    VARCHAR2(65) AUDIT_MODULE_NAME
    VARCHAR2(64) AUDIT_CLIENT_USER_ID
    VARCHAR2(39) AUDIT_CLIENT_IP_ADDRESS
    VARCHAR2(64) AUDIT_CLIENT_WORKSTATION_NAME
    VARCHAR2(256) AUDIT_ADDITIONAL_INFO
}

OFFENDER_CSIP_ATTENDEES {
    NUMBER(10) REVIEW_ID FK "NOT NULL"
    NUMBER(10) ATTENDEE_ID PK "NOT NULL"
    VARCHAR2(100) ATTENDEE_NAME
    VARCHAR2(50) ATTENDEE_ROLE
    VARCHAR2(1) ATTENDED "DEFAULT ('N')"
    VARCHAR2(4000) CONTRIBUTION
    TIMESTAMP(9) CREATE_DATETIME "NOT NULL DEFAULT SYSTIMESTAMP"
    VARCHAR2(32) CREATE_USER_ID "NOT NULL DEFAULT USER"
    TIMESTAMP(9) MODIFY_DATETIME
    VARCHAR2(32) MODIFY_USER_ID
    TIMESTAMP(9) AUDIT_TIMESTAMP
    VARCHAR2(32) AUDIT_USER_ID
    VARCHAR2(65) AUDIT_MODULE_NAME
    VARCHAR2(64) AUDIT_CLIENT_USER_ID
    VARCHAR2(39) AUDIT_CLIENT_IP_ADDRESS
    VARCHAR2(64) AUDIT_CLIENT_WORKSTATION_NAME
    VARCHAR2(256) AUDIT_ADDITIONAL_INFO
}
