erDiagram
	predicate-query ||--o| equality-predicate : "grouped as"
	predicate-query ||--o| composed-predicate : "grouped as"
	predicate-query ||--|| predicate-kw : "contains"
	predicate-query ||--o{ predicate-params : "contains"
