erDiagram
 	 INDUSTRY-MODELLING o|--o| REGISTRY : "produces events"
	 RC-MODELLING o|--o| REGISTRY : "produces events"
   EVENT-EXECUTION {
       EVENT-TYPE type}
    REGISTRY ||--|| SCHEDULER : contains
    REGISTRY |{--|{ EVENT-EXECUTION : defines
