---
title: LinkLake database schema design
---
erDiagram

    USER_IDENTITY {
        string user_id PK
        string idp_sub
    }

    LINK {
        string link_id PK
        stirng user_id FK
        string name
        string link
    }

    TAG {
        string tag_id PK
        string user_id FK
        string name
    }

    RESOURCE {
        string resource_id PK
        string user_id FK
        string name
    }

    RESOURCE_TAG {
        string user_id FK
        string resource_id FK
        string tag_id FK
    }

    USER_IDENTITY ||--o{ LINK : has
    USER_IDENTITY ||--o{ TAG : has
    USER_IDENTITY ||--o{ RESOURCE : has
    RESOURCE_TAG }o--|| USER_IDENTITY : joins
    RESOURCE_TAG }o--|| TAG : joins
    RESOURCE_TAG }o--|| RESOURCE : joins

