erDiagram
  CONTROL{
     bounded-context RENDERING}
  COMPUTATION{
     bounded-context RENDERING}
  STOPPING-DEFINITION{
      id keyword PK
      stopping-evaluation fn
      built-inQMark boolean
      next-possibleQMark boolean}
  SNAPSHOT {
     value-object true}
  COMPUTATION o{--o{ STOPPING-DEFINITION : "uses"
  CONTROL o{--o{ STOPPING-DEFINITION : "uses"
  INDUSTRIAL-MODEL o{--o{ STOPPING-DEFINITION : ""
  STOPPING-DEFINITION o{--|| SCHEDULER : "uses built-in"
  STOPPING-DEFINITION o|--o{ STOPPING-CRITERIA : "is contained"
  STOPPING-DEFINITION o{--|| SNAPSHOT : "inspects"
  STOPPING-DEFINITION o{--o{ STOPPING-REGISTRY : "is registered"
