[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# day08\-mindmap

## 字典必須要掌握的操作

### 1\.按k取值\(不推薦使用\)

#### user\_dict\['username'\]

### 2\.按內建方法get取值\(推薦使用\)

#### user\_dict\.get\('username'\)

### 3\.修改值數據

#### user\_dict\['username'\] = 'tony'

##### 鍵存在則修改對應的值

### 4\.新增鍵值對

#### user\_dict\['age'\] = 18

##### 鍵不存在則新增鍵值對

### 5\.刪除數據

#### del user\_dict\['username'\]

#### user\_dict\.pop\('password'\)

### 6\.統計字典中鍵值對的個數

#### len\(user\_dict\)

### 7\.字典三劍客

#### user\_dict\.keys\(\)

##### 一次性獲取字典所有的鍵

#### user\_dict\.values\(\)

##### 一次性獲取字典所有的值

#### user\_dict\.items\(\)

##### 一次性獲取字典的鍵值對數據

##### 可用解壓賦值

###### for k, v in user\_dict\.items\(\):

## 元組必須掌握的方法
> leftSide=`true`


### 1\.索引取值

### 2\.切片操作

### 3\.間隔、方向

### 4\.統計元組內數據值的個數

#### len\(t1\)

### 5\.統計元組內某個數據值出現的次數

#### t1\.count\(11\)

### 6\.統計元組內指定數據值的索引值

### 7\.元組內如果只有一個數據值那麼逗號不能少

### 8\.元組內索引綁定的記憶體地址不能被修改\(注意區分 可變與不可變\)

### 9\.元組不能新增或刪除數據

## 集合需要掌握的方法
> leftSide=`true`


### 1\.類型轉換

#### 集合內數據必須是不可變類型\(整型 浮點型 字串 元組\)

#### 集合內數據也是無序的 沒有索引的概念

### 去重

### 關係運算

#### 群體之間做差異化校驗

#### 1\.交集

##### f1 & f2

#### 2\.差集

##### f1 \- f2

#### 3\.或，所有

##### f1 | f2

#### 4\.各自獨有

##### f1 ^ f2

#### 5\.父集 子集

##### f1 \> f2

###### f1 是否都包含 f2

##### f1 \< f2

###### f2 是否都包含 f1

### ps:只有遇到上述兩種需求的時候才應該考慮使用集合
