mindmap
  root((Coucal))
    Core
        p)CalDAV/Local FS, etc.(
    API
        p)HTTP(
    Channel
        p)SMTP/IMAP/XMPP, etc.(
    Workflow
        p)Automation(
    Command
        p)Command line support(

