mindmap
  root((Django
  Quiz App))
    Models
      Quiz
      Question
      Answer
      QuizAttempt
      UserAnswer
      UserProfile
    Field Types
      CharField
      TextField
      ForeignKey
      DateTimeField
      IntegerField
      BooleanField
      DurationField
      OneToOneField
    Relationships
      Many-to-One
        ForeignKey
      One-to-One
        OneToOneField
    Model Options
      on_delete
      related_name
    Model Methods
      __str__
    Django Auth
      User model
    Database Concepts
      Primary Key
      Foreign Key
    ORM Features
      Auto-created fields
        id
      Timestamps
        auto_now_add
        auto_now
    Metadata
      verbose_name
      verbose_name_plural
