mindmap
Psychomotrice

      ce qu'il fait

       Obtention de la liste des bénéficiaires.
       Gestion de la liste d'attente et saisie des informations médicales dans des tableaux Excel trimestriels.


      
        