mindmap
Orthophoniste
  
      ce qu'il fait
       Saisie les informations de handicap Gestion des rendez-vous, Informer le service social

      ce qu'il dit
            Obtention de la liste des bénéficiaires du pôle médical, gestion de la liste d'attente incluant la gestion des rendez-vous et l'information au service social.


      
        