mindmap
Orthoptiste

      ce qu'il fait

        Réception des bénéficiaires avec référence du médecin généraliste, gestion par tableau temporel, suivi des dossiers par l'infirmière, présentation du bilan orthoptique et transition vers Excel avec difficultés.

      

      
        