mindmap
    root((IReadOnlyAnnotatable))
        IAnnotatable
            AnnotatableBase
                Annotatable
                    MigrationOperation
                        ColumnOperation
                            AddColumnOperation
                            AlterColumnOperation
                        AddForeignKeyOperation
                        AddPrimaryKeyOperation
                        AddUniqueConstraintOperation
                        DatabaseOperation
                            AlterDatabaseOperation
                        SequenceOperation
                            AlterSequenceOperation
                            CreateSequenceOperation
                        TableOperation
                            AlterTableOperation
                            CreateTableOperation
                        AddCheckConstraintOperation
                        CreateIndexOperation
                        DropColumnOperation
                        DropForeignKeyOperation
                        DropIndexOperation
                        DropPrimaryKeyOperation
                        DropSchemaOperation
                        DropSequenceOperation
                        DropTableOperation
                        DropUniqueConstraintOperation
                        DropCheckConstraintOperation
                        EnsureSchemaOperation
                        RenameColumnOperation
                        RenameIndexOperation
                        RenameSequenceOperation
                        RenameTableOperation
                        RestartSequenceOperation
                        SqlOperation
                        InsertDataOperation
                        DeleteDataOperation
                        UpdateDataOperation
