---
config:
  theme: base
---
mindmap
  root((Web Developer))
    Skills
        Logical thinking
        Development Methologies
        Soft Skills
        Code Quality
        Developer Tooling
        Research Skils
        UX
        Security
        DevOps
        Source Control
        Graphic Design
        Networking
        Generative AI
        No-Code Solutions              
    {{Frontend}}
        CRMs
        JavaScript
        HTML
            Responsive Design
        CSS
            CSS Libraries
        Frameworks
            TypeScript
            Bundlers
        Full Stack
    {{Backend}}
        .NET
        PHP
        Node and NPM
        Java and Spring Boot
        Cloud Infrastructure
        Linux
        VMs and Containers
        Python
        Databases
        Full Stack
    {{Career Path}}
        Demonstrated Abilities
        Interview Skills
        Code Tests
        Ongoing Growth
            Open Source Contributions
            Certifications
