mindmap
(lab : node.js) 
    1.Démarrez votre aventure JavaScript avec Node.js
    2.Installation et débugage avec Node.js 
    3.Création et utilisation des modules
    4.Exploitez la puissance de npm
    5.Pratique