mindmap
  root((mindmap))
    Origins
      Long History
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On efecctives
      On automatic creations
        Uses
          Creating techniques
          Strategic planning
          Argument mapping


    Tools
      Pen and paper
      Mermaid
