\begin{tabular}{|l|l|}
\hline Candidate surname & Other names \\
\hline
\end{tabular}

Centre Number
Candidate Number
\begin{tabular}{|l|l|l|l|l|}
\hline & & & & \\
\hline
\end{tabular}
\begin{tabular}{|l|l|l|l|}
\hline & & & \\
\hline
\end{tabular}

\title{
Pearson Edexcel Level 3 GCE
}

Time 2 hours
Paper reference
9MA0/01

\section*{Mathematics}

\section*{Advanced PAPER 1: Pure Mathematics 1}

\section*{You must have:}

Mathematical Formulae and Statistical Tables (Green), calculator

Candidates may use any calculator allowed by Pearson regulations.
Calculators must not have the facility for symbolic algebra manipulation, differentiation and integration, or have retrievable mathematical formulae stored in them.

\section*{Instructions}
- Use black ink or ball-point pen.
- If pencil is used for diagrams/sketches/graphs it must be dark (HB or B).
- Fill in the boxes at the top of this page with your name, centre number and candidate number.
- Answer all questions and ensure that your answers to parts of questions are clearly labelled.
- Answer the questions in the spaces provided - there may be more space than you need.
- You should show sufficient working to make your methods clear. Answers without working may not gain full credit.
- Inexact answers should be given to three significant figures unless otherwise stated.

\section*{Information}
- A booklet 'Mathematical Formulae and Statistical Tables' is provided.
- There are 16 questions in this question paper. The total mark for this paper is 100.
- The marks for each question are shown in brackets - use this as a guide as to how much time to spend on each question.

\section*{Advice}
- Read each question carefully before you start to answer it.
- Try to answer every question.
- Check your answers if you have time at the end.

![](https://cdn.mathpix.com/cropped/2024_10_02_d0e9c93c9c19b63d5a6fg-01.jpg?height=187&width=772&top_left_y=2619&top_left_x=642)
1. The point \(P(-2,-5)\) lies on the curve with equation \(y=\mathrm{f}(x), x \in \mathbb{R}\)

Find the point to which \(P\) is mapped, when the curve with equation \(y=\mathrm{f}(x)\) is transformed to the curve with equation
(a) \(y=\mathrm{f}(x)+2\)
(b) \(y=|\mathrm{f}(x)|\)
(c) \(y=3 \mathrm{f}(x-2)+2\)
(2)

Question 1 continued
2. \(\mathrm{f}(x)=(x-4)\left(x^{2}-3 x+k\right)-42\) where \(k\) is a constant Given that \((x+2)\) is a factor of \(\mathrm{f}(x)\), find the value of \(k\).

Question 2 continued
3. A circle has equation
\[
x^{2}+y^{2}-10 x+16 y=80
\]
(a) Find
(i) the coordinates of the centre of the circle,
(ii) the radius of the circle.

Given that \(P\) is the point on the circle that is furthest away from the origin \(O\),
(b) find the exact length \(O P\)
(2)

Question 3 continued
4. (a) Express \(\lim _{\delta x \rightarrow 0} \sum_{x=2.1}^{6.3} \frac{2}{x} \delta x\) as an integral.
(1)
(b) Hence show that
\[
\lim _{\delta x \rightarrow 0} \sum_{x=2.1}^{6.3} \frac{2}{x} \delta x=\ln k
\]
where \(k\) is a constant to be found.
(2)

Question 4 continued
5. The height, \(h\) metres, of a tree, \(t\) years after being planted, is modelled by the equation
\[
h^{2}=a t+b \quad 0 \leqslant t<25
\]
where \(a\) and \(b\) are constants.
Given that
- the height of the tree was 2.60 m , exactly 2 years after being planted
- the height of the tree was 5.10 m , exactly 10 years after being planted
(a) find a complete equation for the model, giving the values of \(a\) and \(b\) to 3 significant figures.
(4)

Given that the height of the tree was 7 m , exactly 20 years after being planted
(b) evaluate the model, giving reasons for your answer.
![](https://cdn.mathpix.com/cropped/2024_10_02_d0e9c93c9c19b63d5a6fg-10.jpg?height=58&width=75&top_left_y=948&top_left_x=1707)

Question 5 continued
6 .

![](https://cdn.mathpix.com/cropped/2024_10_02_d0e9c93c9c19b63d5a6fg-12.jpg?height=532&width=826&top_left_y=245&top_left_x=615)

Figure 1
Figure 1 shows a sketch of a curve \(C\) with equation \(y=\mathrm{f}(x)\) where \(\mathrm{f}(x)\) is a cubic expression in \(x\).

The curve
- passes through the origin
- has a maximum turning point at \((2,8)\)
- has a minimum turning point at \((6,0)\)
(a) Write down the set of values of \(x\) for which
\[
\mathrm{f}^{\prime}(x)<0
\]

The line with equation \(y=k\), where \(k\) is a constant, intersects \(C\) at only one point.
(b) Find the set of values of \(k\), giving your answer in set notation.
(c) Find the equation of \(C\). You may leave your answer in factorised form.

Question 6 continued
7. (i) Given that \(p\) and \(q\) are integers such that
\[
p q \text { is even }
\]
use algebra to prove by contradiction that at least one of \(p\) or \(q\) is even.
(ii) Given that \(x\) and \(y\) are integers such that
- \(x<0\)
- \((x+y)^{2}<9 x^{2}+y^{2}\)
show that \(y>4 x\)
(2)

Question 7 continued
8.

![](https://cdn.mathpix.com/cropped/2024_10_02_d0e9c93c9c19b63d5a6fg-16.jpg?height=535&width=692&top_left_y=241&top_left_x=682)

Figure 2
A car stops at two sets of traffic lights.
Figure 2 shows a graph of the speed of the car, \(v \mathrm{~ms}^{-1}\), as it travels between the two sets of traffic lights.

The car takes \(T\) seconds to travel between the two sets of traffic lights.
The speed of the car is modelled by the equation
\[
v=(10-0.4 t) \ln (t+1) \quad 0 \leqslant t \leqslant T
\]
where \(t\) seconds is the time after the car leaves the first set of traffic lights.
According to the model,
(a) find the value of \(T\)
(b) show that the maximum speed of the car occurs when
\[
t=\frac{26}{1+\ln (t+1)}-1
\]

Using the iteration formula
\[
t_{n+1}=\frac{26}{1+\ln \left(t_{n}+1\right)}-1
\]
with \(t_{1}=7\)
(c) (i) find the value of \(t_{3}\) to 3 decimal places,
(ii) find, by repeated iteration, the time taken for the car to reach maximum speed.

Question 8 continued

Question 8 continued

Question 8 continued
9 .

![](https://cdn.mathpix.com/cropped/2024_10_02_d0e9c93c9c19b63d5a6fg-20.jpg?height=418&width=533&top_left_y=239&top_left_x=770)

Figure 3
Figure 3 shows a sketch of a parallelogram \(P Q R S\).
Given that
- \(\overrightarrow{P Q}=2 \mathbf{i}+3 \mathbf{j}-4 \mathbf{k}\)
- \(\overrightarrow{Q R}=5 \mathbf{i}-2 \mathbf{k}\)
(a) show that parallelogram \(P Q R S\) is a rhombus.
(b) Find the exact area of the rhombus \(P Q R S\).

Question 9 continued

Question 9 continued

Question 9 continued
10. A scientist is studying the number of bees and the number of wasps on an island. The number of bees, measured in thousands, \(N_{b}\), is modelled by the equation
\[
N_{b}=45+220 \mathrm{e}^{0.05 t}
\]
where \(t\) is the number of years from the start of the study.
According to the model,
(a) find the number of bees at the start of the study,
(b) show that, exactly 10 years after the start of the study, the number of bees was increasing at a rate of approximately 18 thousand per year.

The number of wasps, measured in thousands, \(N_{w}\), is modelled by the equation
\[
N_{w}=10+800 \mathrm{e}^{-0.05 t}
\]
where \(t\) is the number of years from the start of the study.
When \(t=T\), according to the models, there are an equal number of bees and wasps.
(c) Find the value of \(T\) to 2 decimal places.

Question 10 continued

Question 10 continued

Question 10 continued
11.

![](https://cdn.mathpix.com/cropped/2024_10_02_d0e9c93c9c19b63d5a6fg-28.jpg?height=643&width=855&top_left_y=244&top_left_x=606)

Figure 4
Figure 4 shows a sketch of part of the curve \(C_{1}\) with equation
\[
y=2 x^{3}+10 \quad x>0
\]
and part of the curve \(C_{2}\) with equation
\[
y=42 x-15 x^{2}-7 \quad x>0
\]
(a) Verify that the curves intersect at \(x=\frac{1}{2}\)

The curves intersect again at the point \(P\)
(b) Using algebra and showing all stages of working, find the exact \(x\) coordinate of \(P\)

Question 11 continued

Question 11 continued

Question 11 continued
12.

In this question you must show all stages of your working.
Solutions relying on calculator technology are not acceptable.
Show that
\[
\int_{1}^{\mathrm{e}^{2}} x^{3} \ln x \mathrm{~d} x=a \mathrm{e}^{8}+b
\]
where \(a\) and \(b\) are rational constants to be found.

Question 12 continued
13. (i) In an arithmetic series, the first term is \(a\) and the common difference is \(d\).

Show that
\[
S_{n}=\frac{n}{2}[2 a+(n-1) d]
\]
(ii) James saves money over a number of weeks to buy a printer that costs \(£ 64\)

He saves \(£ 10\) in week \(1, £ 9.20\) in week 2 , \(£ 8.40\) in week 3 and so on, so that the weekly amounts he saves form an arithmetic sequence.

Given that James takes \(n\) weeks to save exactly \(£ 64\)
(a) show that
\[
n^{2}-26 n+160=0
\]
(b) Solve the equation
\[
n^{2}-26 n+160=0
\]
(c) Hence state the number of weeks James takes to save enough money to buy the printer, giving a brief reason for your answer.

Question 13 continued

Question 13 continued

Question 13 continued
14. In this question you must show all stages of your working.

Solutions relying entirely on calculator technology are not acceptable.
(a) Given that
\[
2 \sin \left(x-60^{\circ}\right)=\cos \left(x-30^{\circ}\right)
\]
show that
\[
\tan x=3 \sqrt{3}
\]
(b) Hence or otherwise solve, for \(0 \leqslant \theta<180^{\circ}\)
\[
2 \sin 2 \theta=\cos \left(2 \theta+30^{\circ}\right)
\]
giving your answers to one decimal place.

Question 14 continued

Question 14 continued

Question 14 continued
15.

![](https://cdn.mathpix.com/cropped/2024_10_02_d0e9c93c9c19b63d5a6fg-42.jpg?height=438&width=738&top_left_y=244&top_left_x=662)

Figure 5
A company makes toys for children.
Figure 5 shows the design for a solid toy that looks like a piece of cheese.
The toy is modelled so that
- face \(A B C\) is a sector of a circle with radius \(r \mathrm{~cm}\) and centre \(A\)
- angle \(B A C=0.8\) radians
- faces \(A B C\) and \(D E F\) are congruent
- edges \(A D, C F\) and \(B E\) are perpendicular to faces \(A B C\) and \(D E F\)
- edges \(A D, C F\) and \(B E\) have length \(h \mathrm{~cm}\)

Given that the volume of the toy is \(240 \mathrm{~cm}^{3}\)
(a) show that the surface area of the toy, \(S \mathrm{~cm}^{2}\), is given by
\[
S=0.8 r^{2}+\frac{1680}{r}
\]
making your method clear.

Using algebraic differentiation,
(b) find the value of \(r\) for which \(S\) has a stationary point.
(c) Prove, by further differentiation, that this value of \(r\) gives the minimum surface area of the toy.
(2)

Question 15 continued

Question 15 continued

Question 15 continued
16 .

![](https://cdn.mathpix.com/cropped/2024_10_02_d0e9c93c9c19b63d5a6fg-46.jpg?height=763&width=1012&top_left_y=241&top_left_x=522)

Figure 6
Figure 6 shows a sketch of the curve \(C\) with parametric equations
\[
x=8 \sin ^{2} t \quad y=2 \sin 2 t+3 \sin t \quad 0 \leqslant t \leqslant \frac{\pi}{2}
\]

The region \(R\), shown shaded in Figure 6, is bounded by \(C\), the \(x\)-axis and the line with equation \(x=4\)
(a) Show that the area of \(R\) is given by
\[
\int_{0}^{a}\left(8-8 \cos 4 t+48 \sin ^{2} t \cos t\right) \mathrm{d} t
\]
where \(a\) is a constant to be found.
(b) Hence, using algebraic integration, find the exact area of \(R\).

Question 16 continued

Question 16 continued