### Handtücher {#handtuecher  .chapter  .small .term}

Frische Handtücher gibt's im [Lager](#lager), rechter Gang, Mitte.
Dort kann man im [Wäschekorb](#waeschekorb) auch benutzte Handtücher ablegen zur nächsten Wäsche.

#### Siehe auch:
["Hinter'm Kühlschrank" (Regal)](#hinterm-kuehlschrank) | 
[Lager](#lager) | 
[Toiletten](#toiletten) | 
[Toiletten-Papier](#toiletten-papier) | 
[Wäschekorb](#waeschekorb) | 
[Index](#index) | 

----

