### "Hinter'm Kühlschrank" (Regal) {#hinterm-kuehlschrank .chapter .small .term}

Das Regal mit dem schönen Namen "Hinter'm Kühlschrank" befindet sich im [Lagerraum](#lager).
Es ist unverwechselbar beschriftet.

#### Siehe auch:
[Handtücher](#handtuecher) | 
[Toiletten-Papier](#toiletten-papier) | 
[Lager](#lager) | 
[Wäschekorb](#waeschekorb) | 
[Index](#index) | 

----

