flowchart LR
    %% Galaxies
    Nyxophora --> Erebusian-Expanse(Erebusian Expanse)
    Nyxophora --> Morphean-Veil(Morphean Veil)

    %% Solar Systems
    Erebusian-Expanse --> Zoca
    Erebusian-Expanse --> Nyxarchia
    Erebusian-Expanse --> Precipydom
    Erebusian-Expanse --> Twiryx
    Morphean-Veil --> Olynovance-I(Olynovance I)
    Morphean-Veil --> Olynovance-II(Olynovance II)
    Morphean-Veil --> Ulynthura

    %% Planets
    Nyxarchia --> Lavernury
    Nyxarchia --> Voluptas
    Nyxarchia --> Bellona
    Nyxarchia --> Sancus
    Nyxarchia --> Consus
    Nyxarchia --> Caelus
    Nyxarchia --> Nyx-Lystra
    Nyxarchia --> Nyx-Ombra
    Nyxarchia --> Aetherus
    Nyxarchia --> Portune
    Nyxarchia --> Charon
    Nyxarchia --> Proserpo

    %% Continents
    Nyx-Lystra --> Euryopsis
    Nyx-Lystra --> Ventricosa
    Nyx-Lystra --> Voreios
    Nyx-Lystra --> Notios
    Nyx-Lystra --> Anatoli

    %% Countries
    Euryopsis --> Suleo
    Euryopsis --> Thalasio
    Ventricosa --> Yuniata
    Ventricosa --> Talanya
    Ventricosa --> Ezio
    Ventricosa --> Auroragno
    Ventricosa --> Paxphania
    Ventricosa --> Monychro
    Ventricosa --> Stelliphastra
    Voreios --> Paciconus
    Voreios --> Valenphos
    Notios --> Pient
    Notios --> Aphronysus
    Notios --> Nosiphos
    Notios --> Minael
    Anatoli --> Teluna
    Anatoli --> Nachor
    Anatoli --> Cour
    Anatoli --> Nadyn
    Anatoli --> Dachros
    Anatoli --> Noluchro
    Anatoli --> Sivibra
    Anatoli --> Stroso
