* [307] J. Lu, K. Chen, H. Zou, Fixed point realization of partial updating adaptive algorithm for active noise control, J. Acoust. Soc. Amer. 131 (4) (2012) 3380-3380.
* [308] G. L. Sicuranza, A. Carini, Nonlinear multichannel active noise control using partial updates, in: IEEE Int. Conf. Acoust., Speech, Signal Process., Vol. 3, 2005, pp. 109-112.
* [309] L. Lu, K.-L. Yin, R. C. de Lamare, Z. Zheng, Y. Yu, X. Yang, B. Chen, A survey on active noise control in the past decade-Part II: Nonlinear systems, Signal Process. 181 (2021) 107929.
* [310] C. R. Fuller, J. D. Jones, Experiments on reduction of propeller induced interior noise by active control of cylinder vibration, J. Sound Vib. (112) (1987) 389-395.
* [311] S. D. Sommerfeldt, Multi-channel adaptive control of structural vibration, Noise Control Eng. J. 37 (2) (1991) 77-89.
* [312] R. L. Clark, C. R. Fuller, Optimal placement of piezoelectric actuators and polyvinylidene fluoride error sensors in active structural acoustic control approaches, J. Acoust. Soc. Amer. 92 (3) (1992) 1521-1533.
* [313] R. L. Clark, C. R. Fuller, Modal sensing of efficient acoustic radiators with polyvinylidene fluoride distributed sensors in active structural acoustic control approaches, J. Acoust. Soc. Amer. 91 (6) (1992) 3321-3329.
* [314] W. T. Baumann, F.-S. Ho, H. H. Robertshaw, Active structural acoustic control of broadband disturbances, J. Acoust. Soc. Amer. 92 (4) (1992) 1998-2005.
* [315] C. R. Fuller, G. P. Gibbs, Active control of interior noise in a business jet using piezoceramic actuators, in: Proc. Noise Con., 1994, pp. 389-394.
* [316] G. P. Gibbs, R. L. Clark, D. E. Cox, J. S. Vipperman, Radiation modal expansion: Application to active structural acoustic control, J. Acoust. Soc. Amer. 107 (1) (2000) 332-339.
* [317] A. P. Berkhoff, Sensor scheme design for active structural acoustic control, J. Acoust. Soc. Amer. 108 (3) (2000) 1037-1045.
* [318] P. Gardonio, Y.-S. Lee, S. J. Elliott, S. Debost, Analysis and measurement of a matched volume velocity sensor and uniform force actuator for active structural acoustic control, J. Acoust. Soc. Amer. 110 (6) (2001) 3025-3031.