* (149) Z. Qiu, C.-M. Lee, Z. H. Xu, L. N. Sui, A multi-resolution filtered-x LMS algorithm based on discrete wavelet transform for active noise control, Mech. Syst. Signal Process. 66 (2016) 458-469.
* (150) N. K. Rout, D. P. Das, G. Panda, Computationally efficient algorithm for high sampling-frequency operation of active noise control, Mech. Syst. Signal Process. 56 (2015) 302-319.
* (151) X. L. Tang, C.-M. Lee, Time-frequency-domain filtered-x LMS algorithm for active noise control, J. Sound Vib. 331 (23) (2012) 5002-5011.
* (152) S. Zhang, Y. S. Wang, H. Guo, C. Yang, X. Wang, N. N. Liu, A normalized frequency-domain block filtered-x LMS algorithm for active vehicle interior noise control, Mech. Syst. Signal Process. 120 (2019) 150-165.
* (153) S. C. Chan, Y. Chu, Z. G. Zhang, A new variable regularized transform domain NLMS adaptive filtering algorithm-Acoustic applications and performance analysis, IEEE Trans. Audio Speech Lang. Process. 21 (4) (2013) 868-878.
* (154) Z. Zecevic, B. Krstajic, M. Radulovic, Frequency-domain adaptive algorithm for improving the active noise control performance, IET Signal Process. 9 (4) (2015) 349-356.
* (155) Z.-H. Deng, H.-G. Wang, G. Chen, Blind adaptive preprocessing to multichannel feedfoward active noise control system, IET Signal Process. 7 (6) (2013) 461-470.
* (156) Y. S. Wang, H. Guo, Y. R. Li, N. N. Liu, C. Yang, Active control for vehicle interior noise based on DWT-FxLMS algorithm using a piezoelectric feedback system, Appl. Acoust. 167 (2020) 107409.
* (157) W. J. Kozacky, T. Ogunfunmi, Convergence analysis of an adaptive algorithm with output power constraints, IEEE Trans. Circuits Syst. II 61 (5) (2014) 364-367.
* (158) W. J. Kozacky, T. Ogunfunmi, A cascaded IIR-FIR adaptive ANC system with output power constraints, Signal Process. 94 (2014) 456-464.
* (159) B. Huang, Y. Xiao, J. Sun, G. Wei, A variable step-size FXLMS algorithm for narrowband active noise control, IEEE Trans. Audio Speech Lang. Process. 21 (2) (2013) 301-312.