* (319) J. P. Carneal, C. R. Fuller, An analytical and experimental investigation of active structural acoustic control of noise transmission through double panel systems, J. Sound Vib. 272 (3-5) (2004) 749-771.
* (320) M. Misol, S. Algermissen, H. P. Monner, Experimental investigation of different active noise control concepts applied to a passenger car equipped with an active windshield, J. Sound Vib. 331 (10) (2012) 2209-2219.
* (321) G. Zhao, N. Alujevic, B. Depraetere, G. Pinte, J. Swevers, P. Sas, Experimental study on active structural acoustic control of rotating machinery using rotating piezo-based inertial actuators, J. Sound Vib. 348 (2015) 15-30.
* (322) P. Belanger, A. Berry, Y. Pasco, O. Robin, Y. St-Amant, S. Rajan, Multi-harmonic active structural acoustic control of a helicopter main transmission noise using the principal component analysis, Appl. Acoust. 70 (1) (2009) 153-164.
* (323) X. Ma, Y. Lu, F. Wang, Active structural acoustic control of helicopter interior multifrequency noise using input-output-based hybrid control, J. Sound Vib. 405 (2017) 187-207.
* (324) H. Guo, Y. S. Wang, C. Yang, X. L. Wang, N. N. Liu, Z. J. Xu, Vehicle interior noise active control based on piezoelectric ceramic materials and improved fuzzy control algorithm, Appl. Acoust. 150 (2019) 216-226.
* (325) G. Pinte, S. Devos, B. Stallaert, W. Symens, J. Swevers, P. Sas, A piezo-based bearing for the active structural acoustic control of rotating machinery, J. Sound Vib. 329 (9) (2010) 1235-1253.
* (326) X. Ma, G. Jin, Z. Liu, Active structural acoustic control of an elastic cylindrical shell coupled to a two-stage vibration isolation system, Int. J. Mech. Sci. 79 (2014) 182-194.
* (327) D. R. Hendricks, W. R. Johnson, S. D. Sommerfeldt, J. D. Blotter, Experimental active structural acoustic control of simply supported plates using a weighted sum of spatial gradients, J. Acoust. Soc. Amer. 136 (5) (2014) 2598-2608.
* (328) G. Pinte, R. Boonen, W. Desmet, P. Sas, Active structural acoustic control of repetitive impact noise, J. Sound Vib. 319 (3-5) (2009) 768-794.