### Toiletten-Papier {#toiletten-papier  .chapter  .small .term}

Nachschub an Toiletten-Papier befindet sich im Regal ["Hinter'm Kühlschrank"](#hinterm-kuehlschrank).

#### Siehe auch:
[Handtücher](#handtuecher) | 
["Hinter'm Kühlschrank" (Regal)](#hinterm-kuehlschrank) | 
[Lager](#lager) | 
[Toiletten-Papier](#toiletten-papier) | 
[Wäschekorb](#waeschekorb) | 
[Index](#index) | 

----

