flowchart LR
    F[Frontend]
    B[Backend]
    D[Database]
    F <-- HTTP Request --> B
    B <-- MySQL Connector/Python --> D
    %% Dir((<img src='https://iconscout.com/ms-icon-310x310.png' width='40' />))