flowchart TD
  zq{zq} --> fd
  zq{zq} --> gk
  zq{zq} --> pp
  zq{zq} --> ph
  zq{zq} --> ss
  zq{zq} --> dr
  zq{zq} --> pl
  qg --> jh
  qg --> nk
  lm --> lg
  lm --> qm
  fk --> lr
  pp --> hh
  bf --> sj
  bf --> qm
  qm{qm} --> kb
  qm{qm} --> jl
  qm{qm} --> bs
  qm{qm} --> kx
  qm{qm} --> bl
  qm{qm} --> cz
  qm{qm} --> dd
  db --> dc
  db --> jn
  kl --> dc
  kl --> qv
  xm --> jh
  ss --> zq
  ss --> nd
  vq --> bh
  vq --> dc
  bl --> bs
  fd --> gk
  dc{dc} --> tx
  dc{dc} --> vq
  dc{dc} --> ct
  dc{dc} --> df
  dc{dc} --> fx
  dj --> zq
  dj --> pp
  fv --> vj
  fv --> zq
  pv --> lm
  pv --> qm
  dg --> zz
  dg --> jh
  fc --> fk
  qv --> dc
  qv --> db
  ls{ls} --> rx
  tx{tx} --> ls
  vl --> fc
  dr --> fd
  dd{dd} --> ls
  kx --> jl
  sj --> qm
  sj --> bl
  vj --> zq
  nk --> jh
  nk --> vl
  xr --> kr
  xr --> jh
  nz{nz} --> ls
  cz --> bf
  ms --> qm
  ct --> fx
  lg --> qm
  lg --> ms
  lr --> dg
  pl --> dr
  rt --> zq
  rt --> dj
  jn --> dc
  zz --> zm
  kf --> kl
  kf --> dc
  jl --> cz
  hh --> fv
  hh --> zq
  df --> mr
  jh{jh} --> zz
  jh{jh} --> lr
  jh{jh} --> vl
  jh{jh} --> fc
  jh{jh} --> nz
  jh{jh} --> fk
  jh{jh} --> qg
  fx --> hq
  hq --> df
  hq --> dc
  kb --> qm
  kb --> kx
  ph{ph} --> ls
  broadcaster --> kb
  broadcaster --> vq
  broadcaster --> ss
  broadcaster --> qg
  nd --> pl
  nd --> zq
  gk --> rt
  mr --> dc
  mr --> kf
  bs --> pv
  bh --> dc
  bh --> ct
  kr --> jh
  kr --> xm
  zm --> xr
  zm --> jh
