flowchart
    broadcaster --> db
    broadcaster --> hd
    broadcaster --> cm
    broadcaster --> xf
    db[%db] --> ml
    db[%db] --> nl
    hd[%hd] --> jx
    hd[%hd] --> zl
    cm[%cm] --> vj
    cm[%cm] --> fh
    xf[%xf] --> mb
    xf[%xf] --> cr
    ml[%ml] --> nl
    ml[%ml] --> bn
    nl[&nl] --> db
    nl[&nl] --> hr
    nl[&nl] --> mr
    nl[&nl] --> hh
    nl[&nl] --> hk
    nl[&nl] --> rs
    nl[&nl] --> bn
    jx[&jx] --> fn
    jx[&jx] --> bd
    jx[&jx] --> tt
    jx[&jx] --> gl
    jx[&jx] --> zl
    jx[&jx] --> hd
    zl[%zl] --> qn
    vj[&vj] --> bb
    vj[&vj] --> qc
    vj[&vj] --> cm
    fh[%fh] --> jj
    fh[%fh] --> vj
    mb[%mb] --> bq
    mb[%mb] --> cr
    cr[&cr] --> dg
    cr[&cr] --> bq
    cr[&cr] --> kk
    cr[&cr] --> xf
    cr[&cr] --> gm
    bn[%bn] --> hk
    hr[%hr] --> kf
    mr[&mr] --> qt
    hh[%hh] --> rg
    hk[%hk] --> rs
    rs[%rs] --> hh
    fn[%fn] --> hn
    bd[%bd] --> fd
    tt[%tt] --> bd
    gl[&gl] --> qt
    qn[%qn] --> jx
    qn[%qn] --> fn
    bb[&bb] --> qt
    qc[%qc] --> tf
    jj[%jj] --> vj
    jj[%jj] --> lp
    bq[%bq] --> tj
    dg[%dg] --> vm
    kk[&kk] --> qt
    gm[%gm] --> qs
    kf[%kf] --> xx
    kf[%kf] --> nl
    qt[&qt] --> rx
    rg[%rg] --> nl
    rg[%rg] --> hr
    hn[%hn] --> jx
    hn[%hn] --> tt
    fd[%fd] --> hm
    fd[%fd] --> jx
    tf[%tf] --> vj
    tf[%tf] --> xl
    lp[%lp] --> cz
    lp[%lp] --> vj
    tj[%tj] --> cr
    tj[%tj] --> qd
    vm[%vm] --> gm
    vm[%vm] --> cr
    qs[%qs] --> jf
    qs[%qs] --> cr
    xx[%xx] --> nl
    xx[%xx] --> ff
    hm[%hm] --> jx
    hm[%hm] --> fq
    xl[%xl] --> gq
    xl[%xl] --> vj
    cz[%cz] --> nb
    cz[%cz] --> vj
    qd[%qd] --> cr
    qd[%qd] --> dg
    jf[%jf] --> cr
    jf[%jf] --> dn
    ff[%ff] --> ql
    ff[%ff] --> nl
    fq[%fq] --> jx
    fq[%fq] --> zk
    gq[%gq] --> lc
    gq[%gq] --> vj
    nb[%nb] --> vj
    nb[%nb] --> dr
    dn[%dn] --> cr
    dn[%dn] --> rb
    ql[%ql] --> nl
    zk[%zk] --> jx
    zk[%zk] --> sf
    lc[%lc] --> vj
    dr[%dr] --> vj
    dr[%dr] --> qc
    rb[%rb] --> cr
    sf[%sf] --> jx