flowchart TD
    A(Open science)
    A -->|Stance| B(* Positionality statements\n* Declaration of conflicts\n &nbsp; &nbsp;of interest\n* Open data)
    style B text-align:left
    A -->|Workflow| C(* Reproducible code/projects\n* Literate programming)
    style C text-align:left
    A -->|Dissemination| D(* Preregistration\n* Registered reports\n* Pre-prints)
    style D text-align:left
