flowchart TD
    User -->|USDC| Minter
    Minter -->|USD+| User
    User -->|USD+| Redeemer
    Redeemer -->|USDC| User
    Minter -->|USDC| Ramp[Fiat-Crypto Conversion]
    Ramp -->|USD| TBills[TBills Fund]
    TBills -->|USD| Ramp
    TBills --> TBills
    Ramp -->|USDC| Redeemer