flowchart TB 
    A([Start]) --> B[/Input Gaji Kotor/]
    B -->C[Hitung Pajak = 10% * Gaji Kotor]
    C --> D[Hitung Gaji Bersih = Gaji Kotor - Pajak]
    D --> E[/Tampilkan Gaji Bersih/]
    E --> F([End])