flowchart TD
    hadoks01("Submit your form 
    (in Dutch) 
    to Hadoks's advisory 
    committee") -->|About 1 month| hadoks02("When approved, you will 
    receive a second form 
    from Hadoks's advisory 
    committee that you will 
    need to submit
    to said committee")
    hadoks02 -->|6 to 8 weeks| hadoks03("If permission
    is granted, you will be 
    supplied the data by 
    the data supplier")

    style hadoks01 fill:#c594c3
    click hadoks01 "https://elan-dcc.github.io/hadoks_projectaanvragen_2024.docx" "Form application Hadoks" _blank