flowchart TD
  start["[38 27 43 3 9 82 10]"]
  start --1. MergeSort--> split1["[38 27 43 3]"]
  split1 --2. MergeSort--> split2["[38 27]"]
  split2 --3. MergeSort--> split3["[38]"]
  split2 --4. MergeSort--> split4["[27]"]
  split3 & split4 --- temp1(( )):::empty --5. Merge--> merge1["[27 38]"]
  split1 --6. MergeSort--> split5["[43 3]"]
  split5 --7. MergeSort--> split6["[43]"]
  split5 --8. MergeSort--> split7["[3]"]
  split6 & split7 --- temp2(( )):::empty --9. Merge--> merge2["[3 43]"]
  merge1 & merge2 --- temp3(( )):::empty --10. Merge--> merge3["[3 27 38 43]"]
  start --11. MergeSort--> split8["[9 82 10]"]
  split8 --12. MergeSort--> split9["[9 82]"]
  split9 --13. MergeSort--> split10["[9]"]
  split9 --14. MergeSort--> split11["[82]"]
  split10 & split11 --- temp4(( )):::empty --15.Merge--> merge4["[9 82]"]
  split8 --16. MergeSort--> split12["[10]"]
  merge4 & split12 --- temp5(( )):::empty --17. Merge--> merge5["[9 10 82]"]
  merge3 & merge5 --- temp6(( )):::empty --18. Merge--> finish["[3 9 10 27 38 43 82]"]