---
config:
  theme: base
  themeVariables:
    fontFamily: arial
    fontSize: 16px
    lineColor: '#666666'
---
flowchart TD
    A["Chairman"] --> B["Vice Chairman"]
    B --> C["Executive Director"]
    C --> D["Wool Marketing<br>Development Officer"] & E["Administrative Officer"]
    D --> F["Deputy Manager Marketing"]
    F --> G["Marketing Assistant"] & H["Research Assistant"]
    E --> I["Accountant"] & J["Stenographer"] & K["L.D.C."] & L["Peon"]
    A@{ shape: rounded}
    B@{ shape: rounded}
    E@{ shape: rounded}
    F@{ shape: rounded}
    G@{ shape: rounded}
    H@{ shape: rounded}
    I@{ shape: rounded}
    J@{ shape: rounded}
    K@{ shape: rounded}
    L@{ shape: rounded}
     A:::executive
     B:::executive
     C:::executive
     D:::marketing
     E:::administrative
     F:::marketingOps
     G:::marketingOps
     H:::marketingOps
     I:::adminOps
     J:::adminOps
     K:::support
     K:::adminOps
     L:::support
     L:::adminOps
    classDef executive fill:#4A90E2,stroke:#2171C7,color:white
    classDef marketing fill:#9B6ABC,stroke:#7A4F96,color:white
    classDef administrative fill:#50B87C,stroke:#3D9963,color:white
    classDef marketingOps fill:#B784D9,stroke:#9B6ABC,color:white
    classDef support fill:#F5A623,stroke:#E69112,color:white
    classDef adminOps fill:#72C697, stroke:#50B87C, color:white
