flowchart
    subgraph Python
        py_float_model[Float model]

        fx_float_model[FX graph]
        fx_qprep_model[Graph with observers]
        fx_qconv_model[Quantized graph]

        subgraph converted_model[Converted model]
            aten_graph[FX graph with ATen ops]
            aten_shir_graph[FX graph with ATen + SHIR ops]
            aten_decomp_graph[FX graph with Core ATen + prims + SHIR ops]
            fx_supported_subgraph[SHIR supported graph]
            fx_remainder_subgraph[Fallback graph]
            fx_final_graph[Final graph]
        end
    end
    subgraph SHIR
        shir_algo_expr[algo + algo.torch nodes]
        shir_arch_expr[arch nodes]
        shir_graph_ir[graph IR]
    end
    subgraph Synthesis
        vhdl[VHDL]
        gbs[Reconfiguration bitstream]
    end
    mem_layout[Memory layout]

    py_float_model -->|torch export| fx_float_model
    fx_float_model -->|torch quantization prepare| fx_qprep_model
    fx_qprep_model -->|torch quantization convert| fx_qconv_model
    fx_qconv_model -->|torch compile| converted_model
    aten_graph -->|apply SHIR intrinsics| aten_shir_graph
    aten_shir_graph -->|ATen decomposition| aten_decomp_graph
    aten_decomp_graph -->|partitioner| fx_supported_subgraph
    aten_decomp_graph -->|partitioner| fx_remainder_subgraph
    fx_remainder_subgraph -->|insert driver logic| fx_final_graph
    fx_supported_subgraph -->|SHIR backend| shir_algo_expr
    shir_algo_expr -->|ArchCompiler| shir_arch_expr
    shir_arch_expr -->|rewrites + lowering| shir_arch_expr
    shir_arch_expr -->|GraphGenerator| shir_graph_ir
    shir_graph_ir -->|VhdlGenerator| vhdl
    shir_graph_ir -->|MemoryLayout| mem_layout
    vhdl -->|synthesis| gbs
    gbs -.-> fx_final_graph
    mem_layout -.-> fx_final_graph

