flowchart TD
  pr --> pd
  pr --> vx
  pr --> vn
  pr --> cl
  pr --> hm
  hm((hm)) --> qb
  nm((nm)) --> dh
  nm((nm)) --> jv
  lv((lv)) --> jv
  lv((lv)) --> tg
  dg((dg)) --> tm
  dg((dg)) --> jm
  mt((mt)) --> jv
  mt((mt)) --> zp
  ln --> kj
  kj --> rx
  dr --> kj
  dx((dx)) --> ts
  qs --> kf
  qs --> dr
  qs --> sc
  qs --> rg
  qs --> gl
  qs --> dx
  dh((dh)) --> jv
  dh((dh)) --> mc
  rg((rg)) --> qs
  rg((rg)) --> vq
  kt((kt)) --> jv
  kt((kt)) --> mt
  lh((lh)) --> qs
  lh((lh)) --> dl
  tp((tp)) --> pf
  tp((tp)) --> jm
  bf((bf)) --> vx
  bf((bf)) --> pr
  mv((mv)) --> qs
  mv((mv)) --> gl
  ts((ts)) --> ng
  ts((ts)) --> qs
  kf((kf)) --> dx
  gv((gv)) --> jm
  gv((gv)) --> km
  dl((dl)) --> qs
  nd((nd)) --> dg
  km((km)) --> jm
  ns((ns)) --> pr
  ns((ns)) --> pn
  gl((gl)) --> kf
  pd((pd)) --> pr
  pd((pd)) --> jp
  xv((xv)) --> nd
  xv((xv)) --> jm
  hf((hf)) --> nm
  vx((vx)) --> ns
  vq((vq)) --> bs
  vq((vq)) --> qs
  sc((sc)) --> mv
  jv --> hj
  jv --> rc
  jv --> kt
  jv --> ln
  jv --> zp
  jv --> hf
  rc((rc)) --> hj
  jp((jp)) --> mx
  jp((jp)) --> pr
  mf((mf)) --> gv
  mf((mf)) --> jm
  zx --> kj
  tg((tg)) --> jv
  bs((bs)) --> sc
  bs((bs)) --> qs
  ng((ng)) --> qs
  ng((ng)) --> lh
  tk((tk)) --> pr
  qb((qb)) --> bf
  qb((qb)) --> pr
  pn((pn)) --> pr
  pn((pn)) --> cb
  cl((cl)) --> hm
  pb((pb)) --> tp
  broadcaster{broadcaster} --> kt
  broadcaster{broadcaster} --> pd
  broadcaster{broadcaster} --> xv
  broadcaster{broadcaster} --> rg
  jm --> pb
  jm --> tm
  jm --> zx
  jm --> mk
  jm --> xv
  jm --> nd
  vc((vc)) --> jv
  vc((vc)) --> hf
  mc((mc)) --> jv
  mc((mc)) --> lv
  mk((mk)) --> pb
  tm((tm)) --> mh
  cb((cb)) --> pr
  cb((cb)) --> tk
  hj((hj)) --> vc
  zp((zp)) --> rc
  mh((mh)) --> mk
  mh((mh)) --> jm
  pf((pf)) --> mf
  pf((pf)) --> jm
  mx((mx)) --> cl
  mx((mx)) --> pr
  vn --> kj
