flowchart TD
    A(["시작"]) --> B{"알파벳 입력"}
    B --> C1{"영소문자"} & C2{"영대문자"} & C3{"숫자"} & C4{"해당사항 없음"}
    C1 --> D["모스부호 처리"]
    C2 --> D
    C3 --> D
    C4 --> B
    D --> F1["피에조 출력"] & F2["LED 출력"]
    F1 --> G(["종료"])
    F2 --> G
    style A color:#000000, stroke:#FFFFFF,fill:#E1BEE7
    style B color:#000000, stroke:#FFFFFF, fill:#FFF9C4
    style C1 color:#000000, stroke:#FFFFFF, fill:#BBDEFB
    style C2 color:#000000, stroke:#FFFFFF, fill:#BBDEFB
    style C3 color:#000000, stroke:#FFFFFF, fill:#BBDEFB
    style C4 color:#000000, stroke:#FFFFFF,fill:#757575
    style D color:#000000, stroke:#FFFFFF, fill:#C8E6C9
    style F1 color:#000000, stroke:#FFFFFF,fill:#FFCDD2
    style F2 color:#000000, stroke:#FFFFFF,fill:#FFE0B2
    style G color:#000000, stroke:#FFFFFF,fill:#E1BEE7

