flowchart TD
subgraph external [Can be performed whenever]
    idD1(Request permission
    from Perined) --> idD2(Upload approval
    from Perined
    to ticket)
end

id2 --> idD1

style idD2 fill:#c594c3
style external fill:#efd5ef, stroke:#a57ca5
click idD2 "https://elan-dcc.github.io/researchers/perined" "Perined" _blank
click idD2 "https://elanresearch.nl" "ELAN research" _blank