flowchart TB
    A --> B --> C
    subgraph A[A. 자판기에 동전 및 상품 투입]
        A1[잔돈으로 투입할\n금액 입력 및\n변환, 재고 채우기]
        A2[보유한 동전\n출력]
        A3[자판기에 투입할\n상품, 가격, 수량 입력]
        A4[변환 및 자판기에\n재고 채우기]
        A1 --> A2 --> A3 --> A4
    end

    subgraph B[B. 상품 구매]
        B1[금액 투입]
        B2[상품명 입력]
        B1 --> B2
    end
    subgraph C[C. 잔돈 반환]
    end
