flowchart
    bvb --- xhk
    bvb --- hfx
    cmg --- qnr
    cmg --- nvd
    cmg --- lhk
    cmg --- bvb
    frs --- qnr
    frs --- lhk
    frs --- lsr
    jqt --- rhn
    jqt --- xhk
    jqt --- nvd
    lsr --- lhk
    ntq --- jqt
    ntq --- hfx
    ntq --- bvb
    ntq --- xhk
    nvd --- lhk
    pzl --- lsr
    pzl --- hfx
    pzl --- nvd
    qnr --- nvd
    rhn --- xhk
    rhn --- bvb
    rhn --- hfx
    rsh --- frs
    rsh --- pzl
    rsh --- lsr
    rzs --- qnr
    rzs --- cmg
    rzs --- lsr
    rzs --- rsh
    xhk --- hfx
