sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server-->browser: Redirect to notes
    deactivate server
    Note right of browser: Create new note

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->browser: CSS file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->browser: JS file
    deactivate server
    Note right of browser: Execute JS to fetch JSON data

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->browser: JSON file [{"content": "text", "date": "2023-1-1"}, ... ]
    deactivate server
    Note right of browser: Render notes from JSON (execute callback function)

    browser->>server: GET https://studies.cs.helsinki.fi/favicon.ico
    activate server
    server-->browser: Favicon (not found)
    deactivate server
