sequenceDiagram
    participant browser
    participant server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server
    server-->>browser: HTML file
    server-->>browser: CSS file
    server-->>browser: Javascript file
    server-->>browser: JSON file
    deactivate server