sequenceDiagram
    actor Admin
    
    Admin ->> CriarCategoria: Criar categoria
    Admin ->> AtualizarCategoria: Atualizar categoria
    Admin ->> ExcluirCategoria: Excluir categoria
    Admin ->> ConsultarUmaCategoria: Consultar uma categoria
    Admin ->> ConsultarCategorias: Consultar categorias
