sequenceDiagram
    User->>Scene: gesture
    Note right of User: Gesture sources: Mouse, BCI, TouchSurface, SpaceNavigator, etc.
    Note over Scene: Agent collection
    opt pollFeed
        Scene-->>Agent: gesture
    end
    Note over Agent: Node collection
    %loop poll
        Agent->>Node: event
    %end
    opt track
        Node-->>Agent: node
    end
    Note over Agent,Node: inputNode = trackedNode != null ? trackedNode : defaultNode
