sequenceDiagram
    Portable Layer ->> Native Layer: Create a "main" window titled "Counter Program"
    activate Native Layer
    note right of Native Layer: Creates the window and shows it
    deactivate Native Layer
    Portable Layer ->> Native Layer: Draw these widgets in the "main" window
    activate Native Layer
    note right of Native Layer: Draws the widgets in the "main" window
    deactivate Native Layer
    note over Portable Layer, Native Layer: Program continues...
    note right of Native Layer: "Increment" button clicked!
    Native Layer ->> Portable Layer: Call function with handle "1"
    activate Portable Layer
    note left of Portable Layer: Finds callback by handle "1"
    note left of Portable Layer: Invokes the callback
    note left of Portable Layer: Updates counter from 0 to 1
    deactivate Portable Layer
    Portable Layer ->> Native Layer: Update "counter" widget with new content "1"
    activate Native Layer
    note right of Native Layer: Changes content of "counter" widget to "1"
    deactivate Native Layer
