sequenceDiagram
    User->>InputHandler: gesture
    Note right of User: Gesture sources: Mouse, BCI, TouchSurface, SpaceNavigator, etc.
    Note over InputHandler: Agent collection
    opt feed
        InputHandler-->>Agent: gesture
    end
    opt enqueue
        Agent-->>InputHandler: < inputGrabber, event >
    end
    loop dequeue
      InputHandler->>Grabber: event
    end
    Note over Grabber: interact(event)

    %%Note over InputHandler: Agent collection
