sequenceDiagram
    User->>InputHandler: gesture
    Note right of User: Gesture sources: Mouse, BCI, TouchSurface, SpaceNavigator, etc.
    Note over InputHandler: Agent collection
    opt handleFeed
        InputHandler-->>Agent: gesture
    end
    opt enqueue
        Agent-->>InputHandler: < inputNode, event >
    end
    loop dequeue
      InputHandler->>Node: event
    end
    Note over Node: interact(event)

    %%Note over InputHandler: Agent collection
