sequenceDiagram
    Portable Layer->>Native Layer: Create a window titled Counter Program
    activate Native Layer
    note right of Native Layer: Creates the window and shows it
    deactivate Native Layer
