sequenceDiagram 
    participant browser 
    participant server 
    browser ->> server: HTTP POST https://studies.cs.helsinki.fi//exampleapp/new_note_spa
    Note left of browser: Content-type: Application/json {content: ...}
    