sequenceDiagram
  participant f as Frontend
  participant pr as PlayerRegistry (by username)
  participant pa as PlayerAuthenticator (by playerId)

  Note over f,pa:change password for playerId
  f->>pa:ChangePassword
  alt if new password is invalid
    pa->>f:throw bad request
  else if old password is wrong
    pa->>f:throw forbidden
  else
    Note over pa:update password hash
    pa->>f:success
  end
