%% Constrained Delegation (S4U2Proxy)
sequenceDiagram

actor User

User->>DC: KRB_AS_REQ
DC->>User: KRB_AS_REP
Note right of User: User obtains TGT
User->>DC: KRB_TGS_REQ
DC->>User: KRB_TGS_REP
Note right of User: User obtains ST for User to Service
Note right of User: The ST is forwardable

User->>Service: KRB_AP_REQ
Note left of Service: Service obtains User's ST
Service->>User: KRB_AP_REP

critical DC checks if Resource is defined in Service's msDS-AllowedToDelegateTo and User's ST is forwardable
Note left of Service: User's ST is sent together for validation
Service->>DC: KRB_TGS_REQ (S4U2Proxy)
option Yes
DC->>Service: KRB_TGS_REP
Note left of Service: Service obtains ST for User to Resource

Note right of Service: Authenticates as User
Service->>Resource: KRB_AP_REQ
Resource->>Service: KRB_AP_REP

option No
DC->>Service: Reject
end
