<div class="mermaid">
sequenceDiagram
  User->> Cloud Controller: cf create-service
  Cloud Controller->> On Demand Broker: POST instance (create)
  On Demand Broker->>Service Adapter: generate-manifest
  Service Adapter->>On Demand Broker: manifest
  On Demand Broker->>BOSH: deploy
  BOSH->>On Demand Broker: accepted
  On Demand Broker->>Cloud Controller: accepted
  Cloud Controller->>User: create in progress
  loop until bosh task is complete
    Cloud Controller->>On Demand Broker: GET last operation
    On Demand Broker->>BOSH: GET deploy task
    BOSH->>On Demand Broker: task in progress
    On Demand Broker->>Cloud Controller: create in progress
  end
  Cloud Controller->>On Demand Broker: GET last operation
  On Demand Broker->>BOSH: GET task
  BOSH->>On Demand Broker: task done
  On Demand Broker->>BOSH: run post-deploy errand
  BOSH->>On Demand Broker: accepted
  loop until bosh task errand is complete
    Cloud Controller->>On Demand Broker:GET last operation
    On Demand Broker->>BOSH:GET errand task
    BOSH->>On Demand Broker:task in progress
    On Demand Broker->>Cloud Controller:create in progress
  end
  Cloud Controller->>On Demand Broker:GET last operation
  On Demand Broker->>BOSH:GET errand task
  BOSH->>On Demand Broker:task done
  On Demand Broker->>Cloud Controller:create succeeded
  User->>Cloud Controller:cf service
  Cloud Controller->>User: create succeeded
</div>
