sequenceDiagram
    participant B as Browser
    participant S as Server

    B->>+S: GET: exampleapp/spa
    S-->>-B: RESPONSE: 200 OK <br/> Sends HTML Document

    B->>+S: GET: exampleapp/main.css
    S-->>-B: RESPONSE: 200 OK <br/> Sends CSS file

    B->>+S: GET: exampleapp/spa.js
    S-->>-B: RESPONSE: 200 OK <br/> Sends JavaScript file

    B->>+S: GET: exampleapp/data.json
    S-->>-B: RESPONSE: 200 OK <br/> Sends JSON file
