sequenceDiagram
  
  participant A as 70bQ8 deepseekcoder
  participant B as 7bQ4 mistral or llama whatever
  participant C as 3bQ8 Phi3 or whatever
  participant D as 34bQ8 Kaiju
  participant Target_Server as deterministic development environment based on Ubuntu Linux

  A->> B: Generated output
  B->> A: Reason and Adjustments

  C->> A: Monitor outputs and ensure alignment with project parameters
  A->> C: Outputs
  C->> A: Confirmation

  D->> A: B(c): Monitor outputs and ensure alignment with project parameters
  D->> A: Confirmation

  A->> Target_Server: Tasks related to software development or other projects
  B->> Target_Server: Tasks related to software development or other projects
  C->> Target_Server: Tasks related to software development or other projects
  D->> Target_Server: Tasks related to software development or other projects
