%%{init: {'theme': 'dark', 'themeVariables': { 'primaryTextColor': 'white'}}}%%
sequenceDiagram
    participant A as Server<br>(z.B. conda-forge)
    participant B as Lokal<br>(dein Laptop)
    participant C as Session<br>

    A->> B: modul installieren
