sequenceDiagram
    Client->>+Server: Heres my password, username om and hcaptcha key
    Server->>+Client: Ok my dear, take this JWT token that I made with my super strong password! Don't lose it! 
    Client->>+Server: Hey server, I need some data about this. Heres my JWT token
    Server->>+Client: Ok, heres the data []