sequenceDiagram

    autonumber
    participant W as Web applications 
    participant T as Terminal
   
    W->>T: Initiates payment 
    T->>W:Returns payment status via callback
    opt 
    W->>T: Webhook
    end