sequenceDiagram
    title Adding a New Note and consequently page reloads
    participant browser
    participant server

    
    Note right of browser: User writes a new note and clicks the submit button

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    Note left of server: The server processes the new note and saves it
    server-->>browser: Redirect to /notes
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes (page reload)
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css (page reload)
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js (page reload)
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server (page reload)

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json (page reload)
    activate server
    server-->>browser: [{ "content": "This is a new note to draw UML", "date": "2024-07-22T15:50:08.679Z"}]
    deactivate server

    Note right of browser: The browser executes the callback function that renders the updated notes