sequenceDiagram
Title: ファイルの抹消
participant USER AS 登録者
participant DAPPS
participant FIL AS FileIdentityList

USER ->>+ DAPPS: ファイルの登録
    DAPPS ->>+ FIL: ファイル情報を照会（登録者であるか？）
    FIL -->>- DAPPS : 応答
    DAPPS ->>+ FIL: ファイル情報を抹消
    FIL -->>- DAPPS : 応答
DAPPS -->>- USER : 応答
