sequenceDiagram

Actor unauthenticatedUser as Unauthenticated User
Participant website as Website
Participant requestPasswordResetServlet as RequestPasswordReset Servlet
Participant userRepository as User Repository
Participant passwordResetRequestRepository as PasswordResetRequest Repository

Note right of unauthenticatedUser: Received email link:<br/>WEBSITE_URL/reset-password?token=TOKEN

unauthenticatedUser->>website: /reset-password?token=TOKEN
website->>requestPasswordResetServlet: GET: token
requestPasswordResetServlet->>passwordResetRequestRepository: findPasswordResetRequestByToken(token)

passwordResetRequestRepository->>requestPasswordResetServlet: passwordResetRequest
break when passwordResetRequest is null i.e. no passwordResetRequest for token given exists
requestPasswordResetServlet->website: show failure
end

website->>requestPasswordResetServlet: POST: newPassword, newPasswordConfirm, token
requestPasswordResetServlet->>passwordResetRequestRepository: findPasswordResetRequestByToken(token)
passwordResetRequestRepository->>requestPasswordResetServlet: passwordResetRequest
break when passwordResetRequest is null i.e. no passwordResetRequest for token given exists
requestPasswordResetServlet->website: show failure
end

break when passwordResetRequest.isExpired()
requestPasswordResetServlet->website: show failure
end

break when passwordResetRequest.isUsed()
requestPasswordResetServlet->website: show failure
end

break when newPassword != newPasswordConfirm
requestPasswordResetServlet->website: show failure
end

requestPasswordResetServlet->>userRepository: findUserById(passwordResetRequest.getUserId())

userRepository->>requestPasswordResetServlet: user
requestPasswordResetServlet->>userRepository: updateUserPassword(user, newPassword)

break when newPassword is not valid
userRepository->website: show failure
end


userRepository->>requestPasswordResetServlet: user
requestPasswordResetServlet->>passwordResetRequestRepository: markPasswordResetRequestAsUsed(passwordResetRequest)

passwordResetRequestRepository->>requestPasswordResetServlet: passwordResetRequest
requestPasswordResetServlet->>website: show success

website->>unauthenticatedUser: &nbsp;

unauthenticatedUser->>website: /login
