sequenceDiagram
    participant dbm as DB-kitabisa
    participant kf as kafka
    participant kw as kampanye-workers
    participant db as DB-kampanye
    note right of dbm: Sync DB kitabisa to DB kampanye
    dbm->>kf: push changes on table projects, <br>project_status & project_categories
    
    kf->>+kw: consume messages
    kw->>kw: validate()
    alt: need to sync
    note over kw,db: > update - projects<br> > insert/update - <br>project_statuses & project_categories
    kw->>db: sync
    db->>kw: OK
    end
    kw->>kf: commit
    deactivate kw