sequenceDiagram
    opt poll
        Note over Agent: Grabber collection
        Agent->>Grabber: event
        %opt track
            Note over Grabber: track(event)
            Grabber-->>Agent: grabber
        %end
        Note over Agent,Grabber: inputGrabber = trackedGrabber != null ? trackedGrabber : defaultGrabber
    end
