sequenceDiagram
    participant Bob
    participant LoanAggregatorSmartContract
    participant Alice
    participant PWN
    participant AAVE
    participant CollatoralisationStation
    participant OlasDonationManagerContract
    participant UniswapV2Pools
    participant ChainlinkOracle

    Bob ->> LoanAggregatorSmartContract: Deposit any coin for loans
    LoanAggregatorSmartContract ->> Inch: Any coin swap to ETH
    Inch ->> LoanAggregatorSmartContract: ETH
    Charlie ->> AAVE: Deposit DAI for loans
    AAVE ->> Charlie: aDAI
    Alice ->> PWN: Loan Request
    PWN ->> CollatoralisationStation: Poll Loan Requests
    CollatoralisationStation ->> LoanAggregatorSmartContract: Check Available Funds for loan
    CollatoralisationStation ->> OlasDonationManagerContract: Check Nft Claimable OLAS
    CollatoralisationStation ->> UniswapV2Pools: Get OLAS Weth price
    CollatoralisationStation ->> ChainlinkOracle: Get Weth USD Price
    CollatoralisationStation ->> CollatoralisationStation: Analyze Data
    CollatoralisationStation ->> PWN: Create Loan Offer
    Alice ->> PWN: Accept Offer
    Alice ->> PWN: TX NFT

    LoanAggregatorSmartContract ->> AAVE: Borrow DAI
    AAVE ->> LoanAggregatorSmartContract: DAI
    CollatoralisationStation ->> LoanAggregatorSmartContract: TX Loan To fulfill PWN
    LoanAggregatorSmartContract ->> PWN: DAI
    PWN ->> Alice: GIB Loan
    alt Repay loan
        Alice ->> PWN: Repays Loan
        PWN ->> LoanAggregatorSmartContract: Settle Loan + Fees
        LoanAggregatorSmartContract ->> Bob: Collect DAI + Fees
    end
    alt Default on loan
        Alice ->> PWN: REFUSE TO Pay
        PWN ->>LoanAggregatorSmartContract: txs Alice's nft
        CollatoralisationStation ->> LoanAggregatorSmartContract: proxy call to multisig
        LoanAggregatorSmartContract ->> OlasDonationManagerContract: claim OLAS
        LoanAggregatorSmartContract ->> Exchange_1Inch: Liquidate enough to repay bob
        Exchange_1Inch ->> LoanAggregatorSmartContract: DAI
        CollatoralisationStation ->> AAVE: DAI
        AAVE ->> Charlie: DAI + fees
        LoanAggregatorSmartContract ->> Bob: Collect DAI + Fees
        LoanAggregatorSmartContract ->> CollatoralisationStation: Collect
    end