sequenceDiagram
participant browser
participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server-->>browser: 201 Created
    deactivate server

    Note right of browser: The browser renders the new note and maintains the data without needing to refresh the page
