sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    Note right of browser: Form data is sent with HTTP POST, content type is application/json
    server-->>browser: HTTP Status Code 201 (Created)
    deactivate server

    