---
config:
  theme: default
---
sequenceDiagram
participant User
participant API
participant BusinessLogic
participant Database
User->>+API: API Call (Review Submission)
API->>+BusinessLogic: Validate and Process Submission Request
BusinessLogic->>+Database: Save Data
Database-->>-BusinessLogic: Confirm Save
BusinessLogic-->>-API: Return Success/Failure
API-->>-User: Return Success/Failure
