<div class="mermaid">
  sequenceDiagram
  User->> Cloud Controller: cf update-service -c '{"apply-changes":true}'
  Cloud Controller->> On Demand Broker: PATCH instance (update)
  On Demand Broker->>BOSH:GET manifest
  BOSH->>On Demand Broker:previous manifest
  On Demand Broker->>Service Adapter: generate-manifest
  Service Adapter->>On Demand Broker: manifest
  On Demand Broker->>BOSH: deploy
  BOSH->>On Demand Broker: accepted
  On Demand Broker->>Cloud Controller: accepted
  Cloud Controller->>User: update in progress
  loop until bosh task is complete
    Cloud Controller->>On Demand Broker:GET last operation
    On Demand Broker->>BOSH:GET task
    BOSH->>On Demand Broker:task in progress
    On Demand Broker->>Cloud Controller:update in progress
  end
  Cloud Controller->>On Demand Broker:GET last operation
  On Demand Broker->>BOSH:GET task
  BOSH->>On Demand Broker:task done
  On Demand Broker->>Cloud Controller:update succeeded
  User->>Cloud Controller: cf service
  Cloud Controller->>User: update succeeded
</div>
