```mermaid
sequenceDiagram
    participant User as "User"
    participant App as "Your app"
    participant SDK as "Voice SDK"
    participant Agora as "Agora"
    participant SDRTN as "SD-RTN"

    Note right of User: Open App
    User ->>+ SDK: agoraEngine = agoraEngine.createAgoraRtcEngine
    SDK -->>- User: SDK Initialized
    Note right of User: Start call
    User ->>+ SDK: agoraEngine.initialize
    SDK ->>+ SDRTN: Retrieve authentication token
    SDRTN -->>- SDK: Token sent
    SDK ->>+ SDRTN: agoraEngine.joinChannel
    Note over SDRTN, SDK: Join accepted
    SDRTN -->> SDK: Receive and send audio stream
    User ->> SDK: agoraEngine.leaveChannel
    SDK -->> User: Channel left
```