```mermaid
sequenceDiagram
    participant User as <img src="stick_figure.png"/> User
    participant App as Your app
    participant Agora as Agora

    App->>App: Open app
    App->>App: RtcEngine = Agora.Rtc.RtcEngine.CreateAgoraRtcEngine()
    App->>App: context = new RtcEngineContext(_appId, 0, true, CHANNEL_PROFILE_LIVE_BROADCASTING, AUDIO_SCENARIO_DEFAULT)
    App->>App: RtcEngine.Initialize(context)
    App-->>App: RtcEngine.EnableAudio()
    App-->>App: RtcBatch.SetClientRole(CLIENT_ROLE_BROADCASTER)
    App->>App: RtcEngine.JoinChannel()
    App->>Agora: SD-RTN
    Agora-->>App: SD-RTN
    App->>App: RtcEngine.LeaveChannel()
    App-->>App: RtcEngine.DisableAudio()
    App->>App: Close app
```