graph TD

1(choix du sujet individuel - prototype) 
1 --> 2[lab-outils : Installation des outils]
2 ..-> 23[Configuration Windows]
2 ..-> 21[PHP]
21 ..-> 211[xdebug]
2 ..-> 22[VScode]
22 ..-> 221[PHP,TODO,Images]
2 ..-> 24[Rapport avec Markdown]
2 --> 3[lab-frentend : Création de documentation avec HTML]
3--> 4[lab-laravel : backend]
4--> 5[lab-architecture : ]
5--> 6[lab-sécurité : ]