graph LR
1:startevent:((startevent)) --> 2:task:(GO requests the measurements to the MSP) 
2 --> 3:task:(MSP checks the received request) 
3 --> 4:exclusivegateway:{x} 
4 --> 5:task:(MSP denies the request of the GO) 
4 --> 6:task:(MSP performs the measurement) 
5 --> 7:endevent:((endevent)) 
6 --> 8:task:(MSP informs the GO about the failure of the reading) 
6 --> 9:task:(MSP transmits the measured values to the GO) 
9 --> 10:task:(GO processes the measured values) 
10 --> 11:task:(GO sends the changed values to the MSP) 
11 --> 12:task:(GO transmit the readings to the SP) 
12 --> 13:endevent:((endevent))