graph LR
id:startevent:((startevent)) --> id:task:Receive order
id:task:Receive order --> id:exclusivegateway:{x}
id:exclusivegateway:{x} --> |Accept|id:task:Accept order
id:exclusivegateway:{x} --> |Reject|id:endevent:((endevent))
id:task:Accept order --> id:task:Inform storehouse/engineering
id:task:Inform storehouse/engineering --> id:task:Process part list
id:task:Process part list --> id:exclusivegateway:{x}
id:exclusivegateway:{x} --> |Reserve|id:task:Reserve parts
id:exclusivegateway:{x} --> |Back-order|id:task:Back-order parts
id:task:Reserve parts --> id:task:Prepare assembly
id:task:Back-order parts --> id:task:Prepare assembly
id:task:Prepare assembly --> id:task:Assemble bicycle
id:task:Assemble bicycle --> id:task:Ship bicycle
id:task:Ship bicycle --> id:endevent:((endevent