graph LR
A[Sales Department] --> B(Reject/Accept Order)
B --> |Reject| C[Process Instance Finished]
B --> |Accept| D[Storehouse]
D --> E[Check Required Quantity]
E --> |Available| F[Reserve]
E --> |Not Available| G[Back-Order]
D --> H[Engineering Department]
H --> I[Prepare Everything]
F --> I
G --> I
I --> J[Assemble Bicycle]
J --> K[Sales Department]
K --> L[Ship Bicycle]
L --> M[Process Instance Finished]