graph LR
1:startevent:((startevent)) --> 2:task:(Check defect)
2:task: --> 3:task:(Calculate repair cost)
3:task: --> 4:exclusivegateway:{x}
4:exclusivegateway: --> |costs acceptable|5:task:(Check hardware)
4:exclusivegateway: --> |costs not acceptable|9:endevent:((endevent))
5:task: --> 6:task:(Repair hardware)
6:task: --> 7:task:(Check software)
7:task: --> 8:task:(Configure software)
8:task: --> 10:task:(Test system functionality)
10:task: --> 11:exclusivegateway:{x}
11:exclusivegateway: --> |error detected|8:task:
11:exclusivegateway: --> |no error detected|9:endevent:
