graph LR
1:startevent:((startevent)) --> 2:task:(Take order)
2:task: --> 3:task:(Submit ticket)
3:task: --> 4:task:(Order sommelier)
4:task: --> 5:task:(Prepare cart)
5:task: --> 6:task:(Fetch wine)
6:task: --> 7:task:(Prepare drinks)
7:task: --> 8:task:(Deliver order)
8:task: --> 9:task:(Debit account)
9:task: --> 10:endevent:((endevent))
