graph LR
1:startevent:((startevent)) --> 2:task:(Register claim)
2:task: --> 3:task:(Examine claim)
3:task: --> 4:task:(Write recommendation)
4:task: --> 5:exclusivegateway:{x}
5:exclusivegateway:{x} --> |OK|6:task:(Check recommendation)
5:exclusivegateway:{x} --> |Not OK|7:task:(Send back)
6:task: --> 8:task:(Mark claim)
8:task: --> 12:exclusivegateway:{AND}
7:task: --> 9:task:(Repeat recommendation)
9:task: --> 5:exclusivegateway:{x}
12:exclusivegateway:{AND} --> |OK|10:task:(Proceed)
10:task: --> 11:endevent:((endevent))
