graph LR
1:startevent:((startevent)) --> 2:task:(Customer brings defective computer)
2:task: --> 3:task:(CRS checks the defect)
3:task: --> 4:task:(CRS calculates repair cost)
4:task: --> 5:exclusivegateway:{x}
5:exclusivegateway: --> |Customer accepts cost|6:parallelgateway:{AND}
5:exclusivegateway: --> |Customer rejects cost|10:endevent:((endevent))
6:parallelgateway: --> 7:task:(Check and repair hardware)
6:parallelgateway: --> 8:task:(Check and configure software)
7:task: --> 9:exclusivegateway:{x}
8:task: --> 9:exclusivegateway:
9:exclusivegateway: --> |Error detected|11:task:(Detect and repair errors)
9:exclusivegateway: --> |No error detected|12:endevent:((endevent))
11:task: --> 9:exclusivegateway:
