graph LR
    1:startevent:((startevent)) --> 2:task:(Employee submits vacation request)
    2:task: --> 3:task:(Register vacation request)
    3:task: --> 4:task:(Supervisor receives request)
    4:task: --> 5:exclusivegateway:{x}
    5:exclusivegateway: --> |reject| 6:task:(Return application to employee)
    6:task: --> 7:task:(Employee reviews rejection reasons)
    7:task: --> 1:startevent:
    5:exclusivegateway: --> |approve| 8:task:(Generate approval notification)
    8:task: --> 9:task:(Notify Human Resources Representative)
    9:task: --> 10:task:(Complete management procedures)
    10:task: --> 11:endevent:((endevent))
