graph LR
1:startevent:((startevent)) --> 2:task:(Guest calls room service)
2:task: --> 3:task:(Room-service manager takes order)
3:task: --> 4:task:(Manager submits order ticket)
4:task: --> 5:task:(Manager orders sommelier)
5:task: --> 6:task:(Sommelier fetches wine)
6:task: --> 7:task:(Sommelier prepares alcoholic beverages)
7:task: --> 8:task:(Manager assigns order to waiter)
8:task: --> 9:task:(Waiter readies a cart)
9:task: --> 10:task:(Waiter gathers silverware)
10:task: --> 11:task:(Waiter prepares nonalcoholic drinks)
11:task: --> 12:task:(Waiter delivers order)
12:task: --> 13:task:(Waiter returns to station)
13:task: --> 14:task:(Waiter debits guest's account)
14:task: --> 15:task:(Waiter prepares next order)
15:task: --> 16:endevent:((endevent))
