\title{
Pearson Edexcel
}

Mark Scheme (Results)

\section*{Summer 2022}

Pearson Edexcel GCE
In Mathematics (9MA0)
Paper 01 Pure Mathematics 1

\section*{Edexcel and BTEC Qualifications}

Edexcel and BTEC qualifications are awarded by Pearson, the UK's largest awarding body. We provide a wi range of qualifications including academic, vocational, occupational and specific programmes for employe For further information visit our qualifications websites at www.edexcel.com or www.btec.co.uk. Alternative you can get in touch with us using the details on our contact us page at www.edexcel.com/contactus.

Pearson: helping people progress, everywhere

Pearson aspires to be the world's leading learning company. Our aim is to help everyone progress in their li through education. We believe in every kind of learning, for all kinds of people, wherever they are in the wor We've been involved in education for over 150 years, and by working across 70 countries, in 100 languages, have built an international reputation for our commitment to high standards and raising achievement throu innovation in education. Find out more about how we can help you and your students at: www.pearson.com

Summer 2022
Question Paper Log Number P69601A_*
Publications Code 9MAO_01_2206_MS*
All the material in this publication is copyright
(c) Pearson Education Ltd 2022
- All candidates must receive the same treatment. Examiners must mark the first candidate in exactly the same way as they mark the last.
- Mark schemes should be applied positively. Candidates must be rewarded for what they have shown they can do rather than penalised for omissions.
- Examiners should mark according to the mark scheme not according to their perception of where the grade boundaries may lie.
- There is no ceiling on achievement. All marks on the mark scheme should be used appropriately.
- All the marks on the mark scheme are designed to be awarded. Examiners should always award full marks if deserved, i.e. if the answer matches the mark scheme. Examiners should also be prepared to award zero marks if the candidate's response is not worthy of credit according to the mark scheme.
- Where some judgement is required, mark schemes will provide the principles by which marks will be awarded and exemplification may be limited.
- When examiners are in doubt regarding the application of the mark scheme to a candidate's response, the team leader must be consulted.
- Crossed out work should be marked UNLESS the candidate has replaced it with an alternative response.

\section*{EDEXCEL GCE MATHEMATICS}

\section*{General Instructions for Marking}
1. The total number of marks for the paper is 100 .
2. The Edexcel Mathematics mark schemes use the following types of marks:
- M marks: method marks are awarded for ‘knowing a method and attempting to apply it’, unless otherwise indicated.
- A marks: Accuracy marks can only be awarded if the relevant method (M) marks have been earned.
- B marks are unconditional accuracy marks (independent of \(M\) marks)
- Marks should not be subdivided.

\section*{3. Abbreviations}

These are some of the traditional marking abbreviations that will appear in the mark schemes.
- bod - benefit of doubt
- ft - follow through
- the symbol will be used for correct ft
- cao - correct answer only
- cso - correct solution only. There must be no errors in this part of the question to obtain this mark
- isw - ignore subsequent working
- awrt - answers which round to
- SC: special case
- oe - or equivalent (and appropriate)
- dep - dependent
- indep - independent
- dp decimal places
- sf significant figures
- \(*\) The answer is printed on the paper
- \(\square\) The second mark is dependent on gaining the first mark
4. For misreading which does not alter the character of a question or materially simplify it, deduct two from any A or B marks gained, in that part of the question affected.
5. Where a candidate has made multiple responses and indicates which response they wish to submit, examiners should mark this response.
If there are several attempts at a question which have not been crossed out, examiners should mark the final answer which is the answer that is the most complete.
6. Ignore wrong working or incorrect statements following a correct answer.
7. Mark schemes will firstly show the solution judged to be the most common response expected from candidates. Where appropriate, alternatives answers are provided in the notes. If examiners are not sure if an answer is acceptable, they will check the mark scheme to see if an alternative answer is given for the method used.

\section*{General Principles for Pure Mathematics Marking}
(But note that specific mark schemes may sometimes override these general principles)

\section*{Method mark for solving 3 term quadratic:}

\section*{1. Factorisation}
\[
\begin{aligned}
& \left(x^{2}+b x+c\right)=(x+p)(x+q), \text { where }|p q|=|c|, \text { leading to } x=\ldots \\
& \left(a x^{2}+b x+c\right)=(m x+p)(n x+q), \text { where }|p q|=|c| \text { and }|m n|=|a|, \text { leading to } x=\ldots
\end{aligned}
\]

\section*{2. Formula}

Attempt to use the correct formula (with values for \(a, b\) and \(c\) )

\section*{3. Completing the square}

Solving \(x^{2}+b x+c=0:\left(x \pm \frac{b}{2}\right)^{2} \pm q \pm c=0, q \neq 0\), leading to \(x=\ldots\)

\section*{Method marks for differentiation and integration:}

\section*{1. Differentiation}

Power of at least one term decreased by 1. \(\left(x^{n} \rightarrow x^{n-1}\right)\)

\section*{2. Integration}

Power of at least one term increased by \(1 .\left(x^{n} \rightarrow x^{n+1}\right)\)

\section*{Use of a formula}

Where a method involves using a formula that has been learnt, the advice given in recent examiners' reports is that the formula should be quoted first.

Normal marking procedure is as follows:
Method mark for quoting a correct formula and attempting to use it, even if there are small errors in the substitution of values.

Where the formula is not quoted, the method mark can be gained by implication from correct working with values but may be lost if there is any mistake in the working.

\section*{Exact answers}

Examiners' reports have emphasised that where, for example, an exact answer is asked for, or working with surds is clearly required, marks will normally be lost if the candidate resorts to using rounded decimals.
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{2}{*}{1 (a) } & \((-2,-3)\) & B1 & 1.1b \\
\hline & & (1) & \\
\hline \multirow[t]{2}{*}{ (b) } & \((-2,5)\) & B1 & 1.1 b \\
\hline & & (1) & \\
\hline \multirow[t]{3}{*}{ (c) } & Either \(x=0\) or \(y=-13\) & M1 & \(1.1 b\) \\
\hline & \((0,-13)\) & A1 & 1.1 b \\
\hline & & (2) & \\
\hline \multicolumn{4}{|l|}{ (4 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}

Watch for answers in the body of the question and on sketch graphs. This is acceptable. If coordinates are written by the question and in the main answer section the answer section takes precedence.
(a)

B1: Accept without brackets. May be written \(x=-2, y=-3\)
(b)

B1: Accept without brackets. May be written \(x=-2, y=5\)
(c)

M1: For either coordinate. E.g. \((0, \ldots)\) or \((\ldots,-13)\)
If they are building up their solution in stages e.g. \((-2,-5) \rightarrow(0,-5) \rightarrow(0,-15) \rightarrow(0,-13)\) only mark their final coordinate pair
A1: Correct coordinates. See above for building up solution in stages
Accept without brackets. May be written \(x=0, y=-13\)
SC 10 for candidates who write \((-13,0)\)
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \(\mathbf{3}\) & Sets \(\mathrm{f}(-2)=0 \Rightarrow(-2-4)\left((-2)^{2}-3 \times-2+k\right)-42=0\) & M1 & 3.1 a \\
\cline { 2 - 4 } & \(-6(k+10)=42 \Rightarrow k=\ldots\) & M1 & 1.1 b \\
\cline { 2 - 5 } & \(k=-17\) & A 1 & 1.1 b \\
\cline { 2 - 5 } & & \(\mathbf{( 3 )}\) & \\
\hline \multicolumn{4}{|l|}{ (3 marks) } \\
\hline
\end{tabular}

M1: Attempts \(\mathrm{f}(-2)=0\) leading to an equation in \(k\). So \((-2-4)\left((-2)^{2}-3 \times-2+k\right)-42=0\) is fine
Condone slips but expect to see a first bracket of \((-2-4)\).
" -42 " must not be omitted but could appear as +42 with a sign slip.
There may have been attempts to expand \(\mathrm{f}(x)=(x-4)\left(x^{2}-3 x+k\right)-42\) before attempting to set \(\mathrm{f}(-2)=0\). This is acceptable and condone slips/errors in the expansion, but the 42 must be present. FYI the expanded (and simplified) \(\mathrm{f}(x)=x^{3}-7 x^{2}+(12+k) x-4 k-42\)
M1: Solves a linear equation in \(k\) as a result of setting \(\mathrm{f}( \pm 2)=0\).
The \(\pm 42\) must be there at some point when the substitution is made.
Allow minimal evidence here. A linear equation leading to a solution is fine.
If \(\mathrm{f}(x)\) is expanded then it is dependent upon being a cubic which contains a \(k x\) term and a ' 42 '
\(\mathrm{A} 1: k=-17\) correct answer following correct work but allow recovery from invisible brackets \(\qquad\)

Answers of \(k=-17\) may appear with very little or no working, perhaps via trial and improvement. If so, then marks can only be allocated if evidence is shown.
E.g. \(k=-17 \Rightarrow \mathrm{f}(x)=(x-4)\left(x^{2}-3 x-17\right)-42\)
\(f(-2)=(-6) \times(-7)-42=0\). Hence \((x+2)\) is a factor.

\section*{More difficult alternative methods may be seen}

Alt I : You may see attempts via division / inspection..................................................
\(x + 2 \longdiv { x ^ { 2 } - 9 x + ( k + 3 0 ) }\)
Then sets remainder \(-6 k-102=0 \Rightarrow k=-17\)
\[
-6 k-102
\]

M1: For dividing their cubic by \((x+2)\) which has both an \(x\) and a constant coefficient in \(k\), leading to a quadratic quotient and a linear remainder in \(k\) which is then set \(=0\)

M1: Solves a equation resulting from setting a linear remainder in \(k\) equal to 0 . It is dependent on the first M via this route

A1: Completely correct with \(k=-17\)

Alt II: You may also see a grid or an attempt at factorisation via inspection
\begin{tabular}{c|ccc} 
& \(x^{2}\) & \(-9 x\) & \(-2 k-21\) \\
\hline\(x\) & \(x^{3}\) & \(-9 x^{2}\) & \((-2 k-21) x\) \\
+2 & \(2 x^{2}\) & \(-18 x\) & \(-4 k-42\)
\end{tabular}
\[
\text { OR } x^{3}-7 x^{2}+(12+k) x-4 k-42 \equiv(x+2)\left(x^{2}-9 x-2 k-21\right)
\]
which should be followed by equating the \(x\) terms to form an equation in k
\[
12+k=-18-2 k-21 \Rightarrow 3 k=-51 \Rightarrow k=-17
\]

OR \(x^{3}-7 x^{2}+(12+k) x-4 k-42 \equiv(x+2)\left(x^{2}-9 x+k+30\right)\)
which should be followed by equating the constant terms to form an equation in k
\[
-4 k-42=2(k+30) \Rightarrow 6 k=-102 \Rightarrow k=-17
\]

The above are examples. There may be other correct attempts so look at what is done.
M1: For an attempt at factorising E.g. \(x^{3}-7 x^{2}+(12+k) x-4 k-42 \equiv(x+2)\left(x^{2}+b x+c\right)\) and attempting to set up three equations in \(b, c\) and \(k\). E.g \(2+b=-7,2 b+c=12+k, 2 c=-4 k-42\)

The expanded \(\mathrm{f}(x)\) must be a cubic which contains both a \(k x\) term and a ' 42 '
M1: Solves the equations set up from an allowable equation to find \(k\). It is dependent via this route.
A1: Completely correct with \(k=-17\)
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{4}{*}{3 (a) } & (i) \(x^{2}+y^{2}-10 x+16 y=80 \Rightarrow(x-5)^{2}+(y+8)^{2}=\ldots\) & M1 & \(1.1 b\) \\
\hline & Centre \((5,-8)\) & A1 & 1.1 b \\
\hline & (ii) Radius 13 & A1 & \(1.1 b\) \\
\hline & & (3) & \\
\hline \multirow[t]{3}{*}{ (b) } & ![](https://cdn.mathpix.com/cropped/2024_10_02_ac75d09201ee034eecfag-09.jpg?height=76\&width=503\&top_left_y=569\&top_left_x=581) & M1 & 3.1 a \\
\hline & \(13+\sqrt{89}\) but ft on their centre and radius & A1ft & 1.1 b \\
\hline & & (2) & \\
\hline \multicolumn{4}{|l|}{ (5 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}
(a)(i)

M1: Attempts to complete the square on both \(x\) and \(y\) terms.
Accept \((x \pm 5)^{2}+(y \pm 8)^{2}=\ldots\) or imply this mark for a centre of \(( \pm 5, \pm 8)\)
Condone \((x \pm 5)^{2} \ldots .(y \pm 8)^{2}=\ldots\) where the first \(\ldots\) could be , or even -
A1: Correct centre \((5,-8)\).
Accept without brackets. May be written \(x=5, y=-8\)
(a)(ii)

A1: 13. The \(M\) mark must have been awarded, so it can be scored following a centre of \(( \pm 5, \pm 8)\). Do not allow for \(\sqrt{169}\) or \(\pm 13\)
(b)

M1: Attempts \(\sqrt{" 5 n^{2}+" 8 n^{2}}+" 13 "\) for their centre \((5,-8)\) and their radius 13 .
Award when this is given as a decimal, e.g. 22.4 for correct centre and radius. Look for \(\sqrt{a^{2}+b^{2}}+r\) where centre is \(( \pm a, \pm b)\) and radius is \(r\)

A1ft: \(13+\sqrt{89}\) Follow through on their \((5,-8)\) and their 13 leading to an exact answer. ISW for example if they write \(13+\sqrt{89}=22.4\)

![](https://cdn.mathpix.com/cropped/2024_10_02_ac75d09201ee034eecfag-09.jpg?height=436&width=418&top_left_y=1738&top_left_x=1570)

There are more complicated attempts which could involve finding \(P\) by solving \(y="-\frac{8}{5} x "\) and \(x^{2}+y^{2}-10 x+16 y=80\) simultaneously and choosing the coordinate with the greatest modulus. The method is only scored when the distance of the largest coordinate from \(O\) is attempted. Such methods are unlikely to result in an exact value but can score 1 mark for the method. Condone slips

FYI. Solving \(y=-\frac{8}{5} x\) and \(x^{2}+y^{2}-10 x+16 y=80 \Rightarrow 89 x^{2}-890 x-2000=0 \Rightarrow P=(11.89,-19.02)\)
Hence \(O P=\sqrt{" 11.89 n^{2}+" 19.022^{2}}(=22.43)\) scores M1 A0 but \(O P=\sqrt{258+26 \sqrt{89}}\) is M1 A1
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline 4 (a) & \(\lim _{\delta x \rightarrow 0} \sum_{x=2.1}^{6.3} \frac{2}{x} \delta x=\int_{2.1}^{6.3} \frac{2}{x} \mathrm{~d} x\) & B 1 & 1.2 \\
\hline \multirow{3}{*}{\((\mathrm{~b})\)} & \(=[2 \ln x]_{2.1}^{6.3}=2 \ln 6.3-2 \ln 2.1\) & \(\mathbf{( 1 )}\) & \\
\hline & \(=\ln 9 \quad \mathrm{CSO}\) & A 1 & 1.1 b \\
\hline & & \(\mathbf{( 2 )}\) & \\
\hline & & & \(\mathbf{( 3}\) marks) \\
\hline Notes: & & & \\
\hline
\end{tabular}

Mark (a) and (b) as one
(a)

B1: States that \(\int_{2.1}^{6.3} \frac{2}{x} \mathrm{~d} x\) or equivalent such as \(2 \int_{2.1}^{6.3} x^{-1} \mathrm{~d} x\) but must include the limits and the \(\mathrm{d} x\).
Condone \(\mathrm{d} x \leftrightarrow \delta x\) as it is very difficult to tell one from another sometimes
(b)

M1: Know that \(\int \frac{1}{x} \mathrm{~d} x=\ln x\) and attempts to apply the limits (either way around)
Condone \(\int \frac{2}{x} \mathrm{~d} x=p \ln x\) (including \(p=1\) ) or \(\int \frac{2}{x} \mathrm{~d} x=p \ln q x\) as long as the limits are applied.
Also be aware that \(\int \frac{2}{x} \mathrm{~d} x=\ln x^{2}, \int \frac{2}{x} \mathrm{~d} x=2 \ln |x|+c\) and \(\int \frac{2}{x} \mathrm{~d} x=2 \ln c x\) o.e. are also correct \([p \ln x]_{2.1}^{6.3}=p \ln 6.3-p \ln 2.1\) is sufficient evidence to award this mark
A1: CSO \(\ln 9\). Also answer \(=\ln 3^{2}\) so \(k=9\) is fine. Condone \(\ln |9|\)
The method mark must have been awarded. Do not accept answers such as \(\ln \frac{39.69}{4.41}\)
Note that solutions appearing from "rounded" decimal work when taking lns should not score the final mark. It is a "show that" question
E.g. \([2 \ln x]_{2.1}^{6.3}=2 \ln 6.3-2 \ln 2.1=2.197=\ln k \Rightarrow k=\mathrm{e}^{2.197}=8.998=9\)
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{5}{*}{5 (a) } & \begin{tabular}{l} 
Attempts to use \(\quad h^{2}=a t+b\) \\
with either \(t=2, h=2.6\) or \(t=10, h=5.1\)
\end{tabular} & M1 & \(3.1 b\) \\
\hline & \begin{tabular}{l} 
Correct equations \\
\begin{tabular}{l}
\(2 a+b=6.76\) \\
\(10 a+b=26.01\)
\end{tabular}
\end{tabular} & A1 & \(1.1 b\) \\
\hline & Solves simultaneously to find values for \(a\) and \(b\) & dM1 & \(1.1 b\) \\
\hline & \(h^{2}=2.41 t+1.95\) cao & A1 & 3.3 \\
\hline & & (4) & \\
\hline \multirow[t]{3}{*}{ (b) } & \begin{tabular}{l} 
Substitutes \(t=20\) into their \(h^{2}=2.41 t+1.95\) and finds \(h\) or \(h^{2}\) \\
Or substitutes \(h=7\) into their \(h^{2}=2.41 t+1.95\) and finds \(t\)
\end{tabular} & M1 & 3.4 \\
\hline & \begin{tabular}{l} 
Compares the model with the true values and concludes "good \\
model" with a minimal reason \\
E.g. I Finds \(h=7.08(\mathrm{~m})\) and states that it is a good model as \\
\(7.08(\mathrm{~m})\) is close to \(7(\mathrm{~m})\) \\
E.g II Finds \(t=19.5\) years and states that the model is accurate \\
as 19.5 (years) \(\approx 20\) (years)
\end{tabular} & A1 & 3.5 a \\
\hline & & (2) & \\
\hline \multicolumn{4}{|l|}{ (6 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}
(a)

M1: For translating the problem into mathematics. Attempts to use the given equation o.e. with either of the pieces of information to form one correct equation.
Award for unsimplified equations as well, such as \(2.6^{2}=2 a+b\) or \(2.6=\sqrt{2 a+b}\)
A1: Two correct (and different) equations which may be unsimplified
dM 1 : Solves simultaneously to find values for \(a\) and \(b\). It is dependent upon the previous M
Don't be too concerned with the process here as calculators may be used.
Score if values of \(a\) and \(b\) are reached from a pair of simultaneous equations
A1: Establishes the full equation of the model with values of \(a\) and \(b\) given to exactly 3 sf . Award if seen in either (a) or (b). It is not scored for the values of \(a\) and \(b\).
Allow either \(h^{2}=2.41 t+1.95\) or \(h=\sqrt{2.41 t+1.95}\)
If they go on to square root each term from \(h^{2}=2.41 t+1.95\) then it is A0. E.g. \(h=1.55 t+1.40\)
Special case for candidates who mistakenly use \(h=a t+b\)
For \(2.6=2 a+b, \quad 5.1=10 a+b \quad \Rightarrow h=0.3125 t+1.975\) or \(h=0.313 t+1.98\)
can score M1 correct equations with attempt to solve and A1 for either correct answer shown above. These are the only marks available to them for a maximum mark of 110000
(b)

M1: A full and valid attempt to
either substitute \(t=20\) into their \(h^{2}=2.41 t+1.95\) o.e. and find a value for \(h\) or \(h^{2}\)
or substitute \(h=7\) into their \(h^{2}=2.41 t+1.95\) o.e. and find a value for \(t\)
(to enable the candidate to compare real life data with that of the model.)
The equation of the model must be of the correct form, either \(h^{2}=a t+b\) or \(h=\sqrt{a t+b}\)
Do not be too concerned with the mechanics of the solution but the square or \(\sqrt{ }\) must have been used appropriately to enable the comparison to be made.
In cases with no working you will need to check the calculation
A1: Compares their \(h=7.08 \mathrm{~m}\) to 7 m o.e using \(h^{2}\) or their \(t=19.5\) years to 20 years and makes valid conclusion with reason.
For this mark you require
- a statement that it is a "good" or "accurate' ' model or similar wording
- a reason such as "the values are close", "the values are similar" or "the predicted values are within \(5 \%\) of the true values."
- \(\quad\) a model with equation \(h^{2}=a t+b\) o.e. where \(a=\operatorname{awrt} 2.4\) and \(b \in[1.9,2.0]\)
- correct calculations

Condone a statement like ' the model is pretty accurate as it predicted 7.08 m and the actual value is 7 m '
Do not allow incorrect statements such as the model is incorrect as it does not give 7 metres.
Do not allow just "the model gives an underestimate of the true value."
Do not allow 'bad' or 'poor' model
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{2}{*}{6 (a) } & \(2<x<6\) & B1 & \(1.1 b\) \\
\hline & & (1) & \\
\hline \multirow[t]{3}{*}{ (b) } & States either \(k>8\) or \(k<0\) & M1 & \(3.1 a\) \\
\hline & States e.g. \(\{k: k>8\} \cup\{k: k<0\}\) & A1 & 2.5 \\
\hline & & (2) & \\
\hline \multirow[t]{5}{*}{\((c)\)} & Please see notes for alternatives & & \\
\hline & States \(y=a x(x-6)^{2}\) or \(\mathrm{f}(x)=a x(x-6)^{2}\) & M1 & 1.1 b \\
\hline & Substitutes \((2,8)\) into \(y=a x(x-6)^{2}\) and attempts to find \(a\) & dM1 & 3.1 a \\
\hline & \begin{tabular}{l}
\(y=\frac{1}{4} x(x-6)^{2}\) or \(\mathrm{f}(x)=\frac{1}{4} x(x-6)^{2}\) o.e
\end{tabular} & A1 & 2.1 \\
\hline & & (3) & \\
\hline \multicolumn{4}{|l|}{ (6 marks) } \\
\hline \multicolumn{4}{|l|}{\begin{tabular}{l} 
Notes: Watch for answers written by the question. If they are beside the question and in \\
the answer space, the one in the answer space takes precedence
\end{tabular}} \\
\hline
\end{tabular}
(a)

B1: Deduces \(2<x<6\) o.e. such as \(x>2, x<6 \quad x>2\) and \(x<6 \quad\{x: x>2\} \cap\{x: x<6\} \quad x \in(2,6)\) Condone attempts in which set notation is incorrectly attempted but correct values can be seen or implied E.g. \(\{x>2\} \cap\{x<6\}\{x>2, x<6\}\). Allow just the open interval \((2,6)\)
Do not allow for incorrect inequalities such as e.g. \(x>2\) or \(x<6,\{x: x>2\} \cup\{x: x<6\} x \in[2,6]\)
(b)

M1: Establishes a correct method by finding one of the (correct) inequalities
States either \(k>8\) (condone \(k \geqslant 8\) ) or \(k<0\) (condone \(k \leqslant 0\) )
Condone for this mark \(y \leftrightarrow k\) or \(\mathrm{f}(x) \leftrightarrow k\) and \(8<k<0\)
A1: Fully correct solution in the form \(\{k: k>8\} \cup\{k: k<0\}\) or \(\{k \mid k>8\} \cup\{k \mid k<0\}\) either way around but condone \(\quad\{k<0\} \cup\{k>8\},\{k: k<0 \cup k>8\},\{k<0 \cup k>8\}\). It is not necessary to mention \(\mathbb{R}\), e.g. \(\{k: k \in \mathbb{R}, k>8\} \cup\{k: k \in \mathbb{R}, k<0\} \quad\) Look for \(\}\) and \(\cup\)
Do not allow solutions not in set notation such as \(k<0\) or \(k>8\).
(c)

M1: Realises that the equation of \(C\) is of the form \(y=a x(x-6)^{2}\). Condone with \(a=1\) for this mark.
So award for sight of \(a x(x-6)^{2}\) even with \(a=1\)
dM 1 : Substitutes \((2,8)\) into the form \(y=a x(x-6)^{2}\) and attempts to find the value for \(a\).
It is dependent upon having an equation, which the \((y=.\).\() may be implied, of the correct form.\)
A1: Uses all of the information to form a correct equation for \(C y=\frac{1}{4} x(x-6)^{2}\) o.e.
ISW after a correct answer. Condone \(\mathrm{f}(x)=\frac{1}{4} x(x-6)^{2}\) but not \(C=\frac{1}{4} x(x-6)^{2}\).
Allow this to be written down for all 3 marks

\section*{Alternative I part (c):}

Using the form \(y=a x^{3}+b x^{2}+c x\) and setting up then solving simultaneous equations.

\section*{There are various versions of this but can be marked similarly}

M1: Realises that the equation of \(C\) is of the form \(y=a x^{3}+b x^{2}+c x\) and forms two equations in \(a, b\) and \(c\). Condone with \(a=1\) for this mark.
Note that the form \(y=a x^{3}+b x^{2}+c x+d\) is M0 until \(d\) is set equal to 0 .
There are four equations that could be formed, only two are necessary for this mark.
Condone slips
Using \((6,0) \quad \Rightarrow 216 a+36 b+6 c=0\)
Using \((2,8) \quad \Rightarrow 8 \mathrm{a}+4 \mathrm{~b}+2 \mathrm{c}=8\)
Using \(\frac{\mathrm{d} y}{\mathrm{~d} x}=0\) at \(x=2 \Rightarrow 12 a+4 b+c=0\)
Using \(\frac{\mathrm{d} y}{\mathrm{~d} x}=0\) at \(x=6 \Rightarrow 108 a+12 b+c=0\)
dM 1 : Forms and solves three different equations, one of which must be using \((2,8)\) to find values for \(a, b\) and \(c\). A calculator can be used to solve the equations
A1: Uses all of the information to form a correct equation for \(C y=\frac{1}{4} x^{3}-3 x^{2}+9 x\) o.e.
ISW after a correct answer. Condone \(\mathrm{f}(x)=\frac{1}{4} x^{3}-3 x^{2}+9 x\)

\section*{Alternative II part (c) \\ Using the gradient and integrating}

M1: Realises that the gradient of \(C\) is zero at 2 and 6 so sets \(\mathrm{f}^{\prime}(x)=k(x-2)(x-6)\) oe and attempts to integrate. Condone with \(k=1\)
dM 1 : Substitutes \(x=2, y=8\) into \(\mathrm{f}(x)=k\left(\ldots x^{3}+\ldots x+\ldots\right)\) and finds a value for \(k\)
A1: Uses all of the information to form a correct equation for \(C y=\frac{3}{4}\left(\frac{1}{3} x^{3}-4 x^{2}+12 x\right)\) o.e.
ISW after a correct answer. Condone \(\mathrm{f}(x)=\frac{3}{4}\left(\frac{1}{3} x^{3}-4 x^{2}+12 x\right)\)
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{4}{*}{7 (i) } & \begin{tabular}{l} 
For setting up the contradiction: \\
There exists integers \(p\) and \(q\) such that \(p q\) is even and both \(p\) and \\
\(q\) are odd
\end{tabular} & B1 & 2.5 \\
\hline & \begin{tabular}{l} 
For example, sets \(p=2 m+1\) and \(q=2 n+1\) and then attempts \\
\(p q=(2 m+1)(2 n+1)=\ldots\)
\end{tabular} & M1 & \(1.1 b\) \\
\hline & \begin{tabular}{l} 
Obtains \(p q=(2 m+1)(2 n+1)=4 m n+2 m+2 n+1\) \\
\(=2(2 m n+m+n)+1\) \\
States that this is odd, giving a contradiction so \\
" if \(p q\) is even, then at least one of \(p\) and \(q\) is even" *
\end{tabular} & A1* & 2.1 \\
\hline & & (3) & \\
\hline \multirow[t]{4}{*}{ (ii) } & & & \\
\hline & \((x+y)^{2}<9 x^{2}+y^{2} \Rightarrow 2 x y<8 x^{2}\) & M1 & 2.2a \\
\hline & \begin{tabular}{l} 
States that as \\
\begin{aligned}\(x<0 & \Rightarrow 2 y>8 x \\
& \Rightarrow y>4 x *\end{aligned}\)
\end{tabular} & A1* & 2.1 \\
\hline & & (2) & \\
\hline \multicolumn{4}{|l|}{ (5 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}
(i)

B1: For using the "correct"/ allowable language in setting up the contradiction.
Expect to see a minimum of
- "assume" or "let" or "there is " or other similar words
- " \(p q\) is even" and " \(p\) and \(q\) are (both) odd"

M1: Uses a correct algebraic form for \(p\) and \(q\) and attempting to multiply.
Allow any correct form so \(p=2 n+1\) and \(q=2 m+3\) would be fine to use
Different variables must be used for \(p\) and \(q\), so \(p=2 n+1\) and \(q=2 n-1\) would be M 0
A1*: Full argument .
This requires (1) a correct calculation for their \(p q\)
(2) a correct reason and conclusion that it is odd
E.g. \((2 m+1)(2 n+1)=4 m n+2 m+2 n+1=2(2 m n+m+n)+1=\) odd
E.g. \((2 m-1)(2 n+1)=4 m n+2 m-2 n-1=\) even + even - even \(-1=\) odd
and (3) a minimal statement implying that they have proven what was required which could be QED, proven etc

Note that B0 M1 A1 is possible
(ii)

M1: For multiplying out and cancelling terms before proceeding to a correct intermediate line such as \(2 x y<8 x^{2}\) o.e. such as \(2 x(4 x-y)>0\)

A1*: Full and rigorous proof with reason shown as to why inequality reverses. The point at which it reverses must be correct and a correct reason given

See scheme
Alt: \(2 x y<8 x^{2} \Rightarrow x y-4 x^{2}<0 \Rightarrow x(y-4 x)<0\)
as \(x<0,(y-4 x)>0 \Rightarrow y>4 x\) scores M1 A1

So, the following should be scored M1 A0 as line 3 is incorrect
\[
\begin{aligned}
& 2 x y-8 x^{2}<0 \\
& \Rightarrow 2 x y<8 x^{2} \\
& \Rightarrow y<4 x \\
& \Rightarrow y>4 x \text { as } x<0
\end{aligned}
\]

There should be no incorrect lines in their proof
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{2}{*}{8 (a) } & 25 & B1 & 3.4 \\
\hline & & (1) & \\
\hline \multirow[t]{4}{*}{ (b) } & \begin{tabular}{l} 
Attempts to differentiate using the product rule \\
\(\frac{\mathrm{d} v}{\mathrm{~d} t}=\ln (t+1) \times-0.4+\frac{(10-0.4 t)}{t+1}\)
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{c} 
M1 \\
A1
\end{tabular}
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{l}
3.1 b \\
1.1 b
\end{tabular}
\end{tabular} \\
\hline & \begin{tabular}{l} 
Sets their \(\frac{\mathrm{d} v}{\mathrm{~d} t}=0 \Rightarrow \frac{(10-0.4 \boldsymbol{t})}{(\boldsymbol{t}+1)}=0.4 \ln (t+1)\) and then makes \\
progress towards making " \(t\) " the subject (See notes for this)
\end{tabular} & dM1 & \(1.1 b\) \\
\hline & \begin{tabular}{l}
\begin{tabular}{l}
\(t=\frac{25-\ln (t+1)}{1+\ln (t+1)}\) \\
\(\quad t=\frac{26}{1+\ln (t+1)}-1 *\)
\end{tabular}
\end{tabular} & A1* & 2.1 \\
\hline & & (4) & \\
\hline \multirow[t]{4}{*}{ (c) } & (i) Attempts \(t_{2}=\frac{26}{1+\ln 8}-1\) & M1 & \(1.1 b\) \\
\hline & awrt 7.298 & A1 & 1.1 b \\
\hline & (ii) awrt 7.33 seconds & A1 & 3.2 a \\
\hline & & (3) & \\
\hline \multicolumn{4}{|l|}{ (8 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}
(a)

B1: 25 but condone 25 seconds. If another value is given (apart from 0 ) it is B0
(b)

M1: Attempts to use the product rule in an attempt to differentiate \(v=(10-0.4 t) \ln (t+1)\)
Look for \((10-0.4 t) \times \frac{1}{(t+1)} \pm k \ln (t+1)\), where \(k\) is a constant, condoning slips.
If you see direct evidence of an incorrect rule used e.g. \(v u^{\prime}-u v^{\prime}\) it is M0
You will see attempts from \(v=10 \ln (t+1)-0.4 t \ln (t+1)\) which can be similarly marked.
In this case look for \(\frac{a}{t+1} \pm \frac{b t}{t+1} \pm c \ln (t+1)\)

A1: Correct differentiation. Condone a missing left hand or it seen as \(v^{\prime}, \frac{\mathrm{d} y}{\mathrm{~d} x}\) or even \(=0\)
\[
\left(\frac{\mathrm{d} v}{\mathrm{~d} t}\right)=\ln (t+1) \times-0.4+\frac{(10-0.4 t)}{t+1} \text { or equivalent such as }\left(\frac{\mathrm{d} v}{\mathrm{~d} t}\right)=\frac{10}{t+1}-\frac{0.4 t}{(t+1)}-0.4 \ln (t+1)
\]
dM 1 : Score for setting their \(\mathrm{d} V / \mathrm{d} t=0\) (which must be in an appropriate form) and proceeding to an equation where the variable \(t\) occurs only once - ignoring \(\ln (t+1)\).
See two examples of how this can be achieved below. It is dependent upon the previous M. Look for the following steps
- An allowable derivative set \((\) or implied \()=0 \quad\) E.g. \(\ln (t+1) \times 0.4=\frac{(10-0.4 t)}{t+1}\)
- Cross multiplication (or division) and rearrangement to form an equation where the variable \(t\) only occurs once.
\[
\begin{aligned}
& \text { E.g.1. } \quad \begin{array}{ll}
\ln (t+1) \times 0.4=\frac{(10-0.4 t)}{t+1} \\
& \Rightarrow \ln (t+1)=\frac{25-t}{t+1} \\
& \Rightarrow \ln (t+1)=-1+\frac{26}{t+1}
\end{array}
\end{aligned}
\]
\[
\text { E.g } 2 \begin{aligned}
\ln (t+1) \times 0.4 & =\frac{(10-0.4 t)}{t+1} \\
\Rightarrow 0.4 t \ln (t+1)+0.4 \ln (t+1) & =10-0.4 t \\
\Rightarrow 0.4 t(1+\ln (t+1)) & =10-0.4 \ln (t+1)
\end{aligned}
\]

A1*: Correctly proceeds to the given answer of \(t=\frac{26}{1+\ln (t+1)}-1\) showing all key steps.
The key steps must include
- use of \(\frac{\mathrm{d} v}{\mathrm{~d} t}\) or \(v^{\prime}\) which must be correct
- a correct line preceding the given answer, usually \(t=\frac{25-\ln (t+1)}{1+\ln (t+1)}\) or \(\frac{26}{t+1}-1=\ln (t+1)\)
(c) (i)

M1: Attempts to use the iteration formula at least once.
Usually to find \(t_{2}=\frac{26}{1+\ln 8}-1\) which may be implied by awrt 7.44
A1: awrt 7.298. This alone will score both marks as iteration is implied. ISW after sight of this value. As \(t_{3}\) is the only value that rounds to 7.298 just score the rhs, it does not need to be labelled \(t_{3}\)
(c)(ii)

A1: Uses repeated iteration until value established as awrt 7.33 seconds. Allow awrt \(7.33 \mathbf{s}\)
Requires units. It also requires some evidence of iteration which will be usually be awarded from the award of the M
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{2}{*}{ 9(a) } & Attempts both \(|\overrightarrow{P Q}|=\sqrt{2^{2}+3^{2}+(-4)^{2}}\) and \(|\overrightarrow{Q R}|=\sqrt{5^{2}+(-2)^{2}}\) & M1 & 3.1 a \\
\hline & States that \(|\overrightarrow{P Q}|=|\overrightarrow{Q R}|=\sqrt{29}\) so \(P Q R S\) is a rhombus & A1 & 2.4 \\
\hline & & (2) & \\
\hline \multirow[t]{4}{*}{ (b) } & \begin{tabular}{l} 
Attempts BOTH \(\overrightarrow{P R}=\overrightarrow{P Q}+\overrightarrow{Q R}=7 \mathbf{i}+3 \mathbf{j}-6 \mathbf{k}\) \\
AND \(\quad \overrightarrow{Q S}=-\overrightarrow{P Q}+\overrightarrow{P S}=3 \mathbf{i}-3 \mathbf{j}+2 \mathbf{k}\)
\end{tabular} & M1 & 3.1 a \\
\hline & Correct \(\overrightarrow{P R}=7 \mathbf{i}+3 \mathbf{j}-6 \mathbf{k}\) and \(\overrightarrow{Q S}=3 \mathbf{i}-3 \mathbf{j}+2 \mathbf{k}\) & A1 & \(1.1 b\) \\
\hline & Correct method for area \(P Q R S\). E.g. \(\frac{1}{2} \times|\overrightarrow{P R}| \times|\overrightarrow{Q S}|\) & dM1 & 2.1 \\
\hline & \(=\sqrt{517}\) & A1 & \(1.1 b\) \\
\hline & & (4) & \\
\hline \multicolumn{4}{|l|}{ (6 marks) } \\
\hline \multirow{4}{*}{\begin{tabular}{l} 
Alt (b) \\
Example \\
using the \\
cosine \\
rule
\end{tabular}} & \begin{tabular}{l}
\begin{tabular}{l} 
Attempts \(|\overrightarrow{Q S}|=\sqrt{3^{2}+(-3)^{2}+2^{2}}=\sqrt{22}\) and so \\
\(22=29+29-2 \sqrt{29} \sqrt{29} \cos S P Q\)
\end{tabular}
\end{tabular} & M1 & 3.1 a \\
\hline & \begin{tabular}{l}
\(\cos P Q R=-\frac{18}{29}\) or \(\cos S P Q=\frac{18}{29}\) \\
Condone angles in degrees 51.6, 128.4 (1dp) or radians 2.24, 0.901 \\
(3sf) here
\end{tabular} & \begin{tabular}{l} 
A1
\end{tabular} & \(1.1 b\) \\
\hline & \begin{tabular}{l} 
Correct method for area PQRS. E.g. \\
\(P Q \times Q R \sin P Q R=\sqrt{2^{2}+3^{2}+(-4)^{2}} \times \sqrt{5^{2}+(-2)^{2}} \times \frac{\sqrt{517}}{29}\)
\end{tabular} & dM1 & 2.1 \\
\hline & \(=\sqrt{517}\) & A1 & 1.1b \\
\hline & & (4) & \\
\hline
\end{tabular}

FYI
\[
\overrightarrow{Q R}=5 \mathbf{i}+0 \mathbf{j}-2 \mathbf{k}
\]
\[
\overrightarrow{P Q}=2 \mathbf{i}+3 \mathbf{j}-4 \mathbf{k} \quad Q
\]
\(\overrightarrow{S Q}=-3 \mathbf{i}+3 \mathbf{j}-2 \mathbf{k}\)
\[
\overrightarrow{M Q}=-1.5 \mathbf{i}+1.5 \mathbf{j}-1 \mathbf{k}
\]

![](https://cdn.mathpix.com/cropped/2024_10_02_ac75d09201ee034eecfag-19.jpg?height=552&width=744&top_left_y=1843&top_left_x=633)
\(\overrightarrow{P R}=7 \mathbf{i}+3 \mathbf{j}-6 \mathbf{k}\)
\(\overrightarrow{P M}=3.5 \mathbf{i}+1.5 \mathbf{j}-3 \mathbf{k}\)
(a) Do not award marks in part (a) from work in part (b).

M1: Attempts both \(|\overrightarrow{P Q}|=\sqrt{2^{2}+3^{2}+( \pm 4)^{2}}\) and \(|\overrightarrow{Q R}|=\sqrt{5^{2}+( \pm 2)^{2}}\) or \(P Q^{2}\) and \(Q R^{2}\). For this mark only, condone just the correct answers \(|\overrightarrow{P Q}|=\sqrt{29}\) and \(|\overrightarrow{Q R}|=\sqrt{29}\). Alternatively attempts \(\overrightarrow{P R} \bullet \overrightarrow{Q S}\) or \(P M^{2}, M Q^{2}\) and \(P Q^{2}\) where \(M\) is the mid point of \(P R\)
A1: Shows that \(|\overrightarrow{P Q}|=|\overrightarrow{Q R}|=\sqrt{29}\) (with calculations) and states \(P Q R S\) is a rhombus.

Condone poor notation such as \(\overrightarrow{P Q}=\sqrt{29}\) here, So \(\overrightarrow{P Q}=\overrightarrow{Q R}=\sqrt{29}\) hence rhombus.
Requires both a reason and a conclusion. The reason may be given at the start of their solution.
In the alternatives \(\overrightarrow{P R} \bullet \overrightarrow{Q S}=(7 \mathbf{i}+3 \mathbf{j}-6 \mathbf{k}) \bullet(3 \mathbf{i}-3 \mathbf{j}+2 \mathbf{k})=21-9-12=0\) so diagonals cross at \(90^{\circ}\) so \(P Q R S\) is a rhombus or \(P M^{2}+M Q^{2}=P Q^{2}=23.5+5.5=29 \Rightarrow \angle P M Q=90^{\circ} \Rightarrow\) Rhombus
(b)

\section*{Candidates can transfer answers from (a) to use in part (b) to find the area}

Look through their complete solution first. The first two marks are for finding the elements that are required to calculate the area. The second set of two marks is for combining these elements correctly. If the method is NOT shown on how to find vector it can be implied by two correct components. Allow as column vectors.
M1: For a key step in solving the problem. It is scored for attempting to find both key vectors.
Attempts both \(\overrightarrow{P R}=\overrightarrow{P Q}+\overrightarrow{Q R}=(7 \mathbf{i}+3 \mathbf{j}-6 \mathbf{k})\) AND \(\quad \overrightarrow{Q S}=-\overrightarrow{P Q}+\overrightarrow{P S}=(3 \mathbf{i}-3 \mathbf{j}+2 \mathbf{k})\)
You may see \(\overrightarrow{P M}=\frac{1}{2} \overrightarrow{P Q}+\frac{1}{2} \overrightarrow{Q R}=\left(\frac{7}{2} \mathbf{i}+\frac{3}{2} \mathbf{j}-3 \mathbf{k}\right)\) AND \(\quad \overrightarrow{Q M}=-\frac{1}{2} \overrightarrow{P Q}+\frac{1}{2} \overrightarrow{P S}=\left(\frac{3}{2} \mathbf{i}-\frac{3}{2} \mathbf{j}+1 \mathbf{k}\right)\)
A1: Accurately finds both key vectors whose lengths are required to solve the problem.
Score for both \(\overrightarrow{P R}=7 \mathbf{i}+3 \mathbf{j}-6 \mathbf{k}\) and \(\overrightarrow{Q S}=3 \mathbf{i}-3 \mathbf{j}+2 \mathbf{k}\) (Allow either way around.)
or both \(\overrightarrow{P M}=\frac{7}{2} \mathbf{i}+\frac{3}{2} \mathbf{j}-3 \mathbf{k}\) and \(\overrightarrow{Q M}=\frac{3}{2} \mathbf{i}-\frac{3}{2} \mathbf{j}+1 \mathbf{k}\) (Allow either way around.)
dM 1: Constructs a rigorous method leading to the area \(P Q R S\). Dependent upon previous M .
E.g. See scheme. Alt: the sum of the area of four right angled triangles e.g. \(4 \times \frac{1}{2} \times|\overrightarrow{P M}| \times|\overrightarrow{Q M}|\),

A1: \(\sqrt{517}\)
Alternatives for (b). Two such ways are set out below
Alt 1-Examples via cosine rule but you may see use of scalar product via a Further Maths method.
M1: For a key step in solving the problem. In this case it for an attempt at \(\cos P Q R\) or \(\cos S P Q\).
Don't be too concerned with the labelling of the angle which may appear as \(\theta\).
Attempts \(\pm\left(\begin{array}{c}2 \\ 3 \\ -4\end{array}\right) \bullet \pm\left(\begin{array}{c}5 \\ 0 \\ -2\end{array}\right)=\sqrt{2^{2}+3^{2}+(-4)^{2}} \times \sqrt{5^{2}+(-2)^{2}} \cos P Q R\)
A1: Finds the cosine of one of the angles in the Figure.
Look for \(\cos \ldots=-\frac{18}{29}\) or \(\cos \ldots=\frac{18}{29}\) which may have been achieved via the cosine rule.
Accept rounded answers and the angles in degrees 51.6, 128.4 (1dp) or radians 2.24, 0.901 (3sf) here. dM1: Constructs a rigorous method leading to the area PQRS. Implied by awrt 22.7
\[
\text { E.g. } P Q \times Q R \sin P Q R=\sqrt{2^{2}+3^{2}+(-4)^{2}} \times \sqrt{5^{2}+(-2)^{2}} \times \frac{\sqrt{517}}{29}
\]

A1: \(\sqrt{517}\)

\section*{Alt 2-Example via vector product via a Further Maths method.}

M1: For a key step in solving the problem. In this case it for an attempt at \(\pm \overrightarrow{P Q} \times \overrightarrow{Q R}\)
E.g. \(\quad \overrightarrow{P Q} \times \overrightarrow{Q R}=\left(\begin{array}{ccc}\mathbf{i} & \mathbf{j} & \mathbf{k} \\ 2 & 3 & -4 \\ 5 & 0 & -2\end{array}\right)=(3 \times-2-0 \times-4) \mathbf{i}-(2 \times-2-5 \times-4) \mathbf{j}+(2 \times 0-3 \times 5) \mathbf{k}\)

A1: E.g. \(\overrightarrow{P Q} \times \overrightarrow{Q R}=-6 \mathbf{i}-16 \mathbf{j}-15 \mathbf{k}\)
dM 1 : Constructs a rigorous method leading to the area \(P Q R S\). In this case \(|\overrightarrow{P Q} \times \overrightarrow{Q R}|\)
\(\mathrm{A} 1:=\sqrt{(-6)^{2}+(-16)^{2}+(-15)^{2}}=\sqrt{517}\)
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{2}{*}{10 (a) } & 265 thousand & B1 & 3.4 \\
\hline & & (1) & \\
\hline \multirow[t]{3}{*}{ (b) } & \begin{tabular}{l} 
Attempts \(\frac{\mathrm{d} N_{b}}{\mathrm{~d} t}=11 \mathrm{e}^{0.05 t}\)
\end{tabular} & M1 & \(1.1 b\) \\
\hline & \begin{tabular}{l} 
Substitutes \(t=10\) into their \(\frac{\mathrm{d} N_{b}}{\mathrm{~d} t}\)
\end{tabular} & M1 & 3.4 \\
\hline & \begin{tabular}{l}
\(\frac{\mathrm{d} N_{b}}{\mathrm{~d} t}=\) awrt 18.1 which is approximately 18 thousand per year *
\end{tabular} & A1* & 2.1 \\
\hline & & (3) & \\
\hline \multirow[t]{4}{*}{ (c) } & \begin{tabular}{l} 
Sets \\
\(45+220 \mathrm{e}^{0.05 t}=10+800 \mathrm{e}^{-0.05 t} \Rightarrow 220 \mathrm{e}^{0.05 t}+35-800 \mathrm{e}^{-0.05 t}=0\)
\end{tabular} & M1 & \(3.1 b\) \\
\hline & \begin{tabular}{l}
\begin{tabular}{c} 
Correct quadratic equation \\
\(\Rightarrow 220\left(\mathrm{e}^{0.05 t}\right)^{2}+35 \mathrm{e}^{0.05 t}-800=0\)
\end{tabular}
\end{tabular} & A1 & \(1.1 b\) \\
\hline & \(\mathrm{e}^{0.05 t}=1.829,(-1.988) \Rightarrow 0.05 t=\ln (1.829)\) & M1 & 2.1 \\
\hline & \(T=12.08\) & A1 & 1.1b \\
\hline & & (4) & \\
\hline \multicolumn{4}{|l|}{ (8 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}
(a) May be seen in the question so watch out.

B1: Accept 265 thousand or 265000 or equivalent such as 265 k but not just 265 .
(b)

M1: Differentiates to a form \(k \mathrm{e}^{0.05 t}, k>0, k \neq 220\). Do not be too concerned about the lhs.
M1: Substitutes \(t=10\) into a changed function that was formed from an attempt at differentiation.
The left hand side must have implied differentiation. E.g. Rate \(=, N^{\prime}, \frac{d N_{b}}{d t}, \frac{d N}{d t}\) or even \(\frac{\mathrm{d} y}{\mathrm{~d} x}\)
\(\mathrm{A} 1^{*}\) : Full and complete proof that requires
- some correct lhs seen at some point. E.g. "Rate \(=, " \frac{d N_{b}}{d t}, \frac{d N}{d t}\) but condone \(N^{\prime}\).
- an intermediate line/answer of either \(11 \mathrm{e}^{0.05 \times 10}\) or awrt 18.1 before a minimal conclusion which must be referencing the 18000 or 18 thousand
(c)

M1: Attempts to set both equations equal to each other and simplify the constant terms.
Look for \(220 \mathrm{e}^{0.05 t}+35=800 \mathrm{e}^{-0.05 t}\) o.e but condone slips
It is also possible to set \(\frac{N-45}{220}=\left(\mathrm{e}^{0.05 t}=\right) \frac{800}{N-10}\) and form an equation in \(N\)
A1: Correct quadratic form.
Look for \(220\left(\mathrm{e}^{0.05 t}\right)^{2}+35 \mathrm{e}^{0.05 t}-800=0\) or \(220 \mathrm{e}^{0.1 t}+35 \mathrm{e}^{0.05 t}-800=0\) but allow with terms in different order such as \(220 \mathrm{e}^{0.1 t}+35 \mathrm{e}^{0.05 t}=800\)

FYI the equation in \(N\) is \(N^{2}-55 N-175550=0\)
M1: Full attempt to find the value of \(t\) (or a constant multiple of \(t\) )
This involves the key step of recognising and solving a 3TQ in \(\mathrm{e}^{0.05 t}\) followed by the use of lns.
If the answers to the quadratic just appear (from a calculator) you will need to check.
Accuracy should be to 3sf.
You may see different variables used such as \(x\)
\[
x=\mathrm{e}^{0.05 t}, 220 \mathrm{e}^{0.1 t}+35 \mathrm{e}^{0.05 t}=800 \Rightarrow 220 x^{2}+35 x=800 \Rightarrow x=1.82 \ldots \Rightarrow t=20 \ln 1.82 \ldots
\]

Allow use of calculator for solving the quadratic and for \(\mathrm{e}^{0.05 t}=1.82 . . \Rightarrow t=12.08\)
Via the \(N\) route it will involve substituting the positive solution to their quadratic into either equation to find a value for \(t / T\) using same rules as above.
A1: AWRT 12.08

\section*{Answers with limited or no working in (b) and (c)}
(b) A derivative in the correct form must be seen
(c) Candidates who state \(45+220 \mathrm{e}^{0.05 t}=10+800 \mathrm{e}^{-0.05 t}\) followed by awrt 12.08 (presumably from using num-solv on their calculators) can score SC 1100. Rubric on the front of the paper states that "Answers without working may not gain full credit" so we demand a method in this part.
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{3}{*}{11 (a) } & \begin{tabular}{l} 
Substitutes \(x=\frac{1}{2}\) into \(y=2 x^{3}+10\) and \(y=42 x-15 x^{2}-7\) \\
and finds the \(y\) values for both
\end{tabular} & M1 & \(1.1 b\) \\
\hline & \begin{tabular}{l} 
Achieves \(\frac{41}{4}\) o.e. for both and makes a valid conclusion. *
\end{tabular} & A1* & 2.4 \\
\hline & & (2) & \\
\hline \multirow[t]{5}{*}{ (b) } & Sets \(42 x-15 x^{2}-7=2 x^{3}+10 \Rightarrow 2 x^{3}+15 x^{2}-42 x+17=0\) & M1 & \(1.1 b\) \\
\hline & Deduces that \((2 x-1)\) is a factor and attempts to divide & dM1 & 2.1 \\
\hline & \(2 x^{3}+15 x^{2}-42 x+17=(2 x-1)\left(x^{2}+8 x-17\right)\) & A1 & \(1.1 b\) \\
\hline & Solves their \(x^{2}+8 x-17=0\) using suitable method & M1 & \(1.1 b\) \\
\hline & Deduces \(x=-4+\sqrt{33}\) (see note) & A1 & 2.2 a \\
\hline & & (5) & \\
\hline \multicolumn{4}{|l|}{ (7 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}
(a)

M1: Substitutes \(x=\frac{1}{2}\) into both \(y=2 x^{3}+10\) and \(y=42 x-15 x^{2}-7\) and finds \(y\) values Sight of just the \(y\) values at each is sufficient for this mark only.
Alternative: Sets \(42 x-15 x^{2}-7=2 x^{3}+10 \Rightarrow\) cubic and substitutes \(x=\frac{1}{2}\) into the expression, attempts \(\mathrm{f}\left(\frac{1}{2}\right)\) or else attempts to divide the cubic \(=0\) by \((2 x-1)\) or \(\left(x-\frac{1}{2}\right)\). Condone \(\mathrm{f}\left(\frac{1}{2}\right)=0\) without calculations for this mark only.
\(\mathrm{A} 1^{*}\) : Correct calculations must be seen with a minimal conclusion that curves intersect (at \(x=\frac{1}{2}\) ).
E.g. \(2\left(\frac{1}{2}\right)^{3}+10=10.25\) and \(42\left(\frac{1}{2}\right)-15\left(\frac{1}{2}\right)^{2}-7=10.25\) so curves intersect.

Acceptable alternatives are:
\(\mathrm{f}(x)=42 x-15 x^{2}-7-2 x^{3}-10, \mathrm{f}\left(\frac{1}{2}\right)=42\left(\frac{1}{2}\right)-15\left(\frac{1}{2}\right)^{2}-7-2\left(\frac{1}{2}\right)^{3}-10=0 \Rightarrow\) so curves intersect
\(\mathrm{f}(x)=2 x^{3}+15 x^{2}-42 x+17 \Rightarrow\left(x-\frac{1}{2}\right)\left(2 x^{2}+16 x-34\right)\) so \(x=\frac{1}{2}\) is a root so curves intersect
\(\mathrm{f}(x)=2 x^{3}+15 x^{2}-42 x+17 \Rightarrow(2 x-1)\left(x^{2}+8 x-17\right)\) so \((2 x-1)\) is a factor hence curves intersect

Only accept verified, QED etc if there is a preamble mentioning intersection about how it will be shown.
Special case: Scores M1 A0 with or without a conclusion
This is presumably done using a calculator and requires all three roots exact or correct to 3 sf
\(\mathrm{f}(x)=2 x^{3}+15 x^{2}-42 x+17=0\)
\(\Rightarrow x=0.5,1.74,-9.74\)
(b) This part requires candidates to show all stages of their working. Answers without working will not score any marks A method must be seen which could be from part (a) which must then be continued in (b)
M1: Sets \(42 x-15 x^{2}-7=2 x^{3}+10\) and proceeds to 4 term cubic equation.
Condone slips, e.g. signs. Terms do not have to be on one side of the equation.
dM1: For the key step in attempting to "divide" the cubic by \((2 x-1)\)
If attempted via inspection look for correct first and last terms
E.g. \(2 x^{3}+15 x^{2}-42 x+17=(2 x-1)\left(x^{2}+\ldots \pm 17\right)\) if cubic expression is correct

If attempted via division look for correct first and second terms

![](https://cdn.mathpix.com/cropped/2024_10_02_ac75d09201ee034eecfag-24.jpg?height=174&width=1006&top_left_y=704&top_left_x=628)

It is acceptable for an attempt to divide by \(\left(x-\frac{1}{2}\right)\). It is easily marked using the same
guidelines, e.g. \(2 x^{3}+15 x^{2}-42 x+17=\left(x-\frac{1}{2}\right)\left(2 x^{2}+16 x \ldots.\right)\)
A1: \(2 x^{3}+15 x^{2}-42 x+17=(2 x-1)\left(x^{2}+8 x-17\right)\) o.e. \(\left(x-\frac{1}{2}\right)\left(2 x^{2}+16 x-34\right)\)
This may be implied by sight of \(\left(x^{2}+8 x-17\right)\) or \(\left(2 x^{2}+16 x-34\right)\) in a "division" sum.
M1: Solves their quadratic \(x^{2}+8 x-17=0\) using a suitable method including calculator. You may need to check this. It is not completely dependent upon the previous M's but an attempt at a full method must have been seen. So look for
- the two equations being set equal to each other and some attempt made to combine
- some attempt to "divide" the result by \((2 x-1)\) o.e. allowing for flaws in the method

A1: Gives \(x=-4+\sqrt{33}\) o.e. only. The \(x=-4-\sqrt{33}\) must not be included in the final answer.
Allow exact unsimplified equivalents such as \(x=\frac{-8+\sqrt{132}}{2}\). ISW for instance if they then put this in decimal form.
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline 12 & \(\int x^{3} \ln x \mathrm{~d} x=\frac{x^{4}}{4} \ln x-\int \frac{x^{4}}{4} \times \frac{1}{x} \mathrm{~d} x\) & M1 & 1.1 b \\
\cline { 2 - 5 } & \(=\frac{x^{4}}{4} \ln x-\frac{x^{4}}{16}(+c)\) & M1 & 1.1 b \\
& \(\int_{1}^{\mathrm{e}^{2}} x^{3} \ln x \mathrm{~d} x=\left[\frac{x^{4}}{4} \ln x-\frac{x^{4}}{16}\right]_{1}^{\mathrm{e}^{2}}=\left(\frac{\mathrm{e}^{8}}{4} \ln \mathrm{e}^{2}-\frac{\mathrm{e}^{8}}{16}\right)-\left(-\frac{1^{4}}{16}\right)\) & M1 & 2.1 \\
\cline { 2 - 5 } & \(=\frac{7}{16} \mathrm{e}^{8}+\frac{1}{16}\) & A1 & 1.1 b \\
\hline
\end{tabular}

M1: Integrates by parts the right way round.
Look for \(k x^{4} \ln x-\int k x^{4} \times \frac{1}{x} \mathrm{~d} x\) o.e. with \(k>0\). Condone a missing \(\mathrm{d} x\)
M1: Uses a correct method to integrate an expression of the form \(\int k x^{4} \times \frac{1}{x} \mathrm{~d} x \rightarrow c x^{4}\)
A1: \(\int x^{3} \ln x \mathrm{~d} x=\frac{x^{4}}{4} \ln x-\frac{x^{4}}{16}(+c)\) which may be left unsimplified
M1: Attempts to substitute 1 and \(\mathrm{e}^{2}\) into an expression of the form \(\pm p x^{4} \ln x \pm q x^{4}\), subtracts and uses \(\ln \mathrm{e}^{2}=2\) (which may be implied).
A1: \(\frac{7}{16} \mathrm{e}^{8}+\frac{1}{16}\) o.e. Allow \(0.4375 \mathrm{e}^{8}+0.0625\) or uncancelled fractions. NOT ISW: \(7 \mathrm{e}^{8}+1\) is A 0
You may see attempts where substitution has been attempted.
E.g. \(u=\ln x \Rightarrow x=\mathrm{e}^{u}\) and \(\frac{\mathrm{d} x}{\mathrm{~d} u}=\mathrm{e}^{u}\)

M1: Attempts to integrate the correct way around condoning slips on the coefficients
\[
\int x^{3} \ln x \mathrm{~d} x=\int \mathrm{e}^{4 u} u \mathrm{~d} u=\frac{\mathrm{e}^{4 u}}{4} u-\int \frac{\mathrm{e}^{4 u}}{4} \mathrm{~d} u
\]

M1 A1: \(\int x^{3} \ln x \mathrm{~d} x=\frac{\mathrm{e}^{4 u}}{4} u-\frac{\mathrm{e}^{4 u}}{16}(+c)\)
M1 A1: Substitutes 0 and 2 into an expression of the form \(\pm p u \mathrm{e}^{4 u} \pm q \mathrm{e}^{4 u}\) and subtracts
It is possible to use integration by parts "the other way around"
To do this, candidates need to know or use \(\int \ln x \mathrm{~d} x=x \ln x-x\)
FYI \(I=\int x^{3} \ln x \mathrm{~d} x=x^{3}(x \ln x-x)-\int(x \ln x-x) \times 3 x^{2} \mathrm{~d} x=x^{3}(x \ln x-x)-3 I+\frac{3}{4} x^{4}\)
Hence \(4 I=x^{4} \ln x-\frac{1}{4} x^{4} \Rightarrow I=\frac{1}{4} x^{4} \ln x-\frac{1}{16} x^{4}\)
Score M1 for a full attempt at line 1 (condoning bracketing and coefficient slips) followed by M 1 for line 2 where terms in \(I\) o.e. to form the answer.
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{3}{*}{13 (i) } & States that \(S=a+(a+d)+\ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots .+(a+(n-1) d)\) & B1 & 1.1 a \\
\hline & \begin{tabular}{l}
\begin{tabular}{l}
\(S=a+\quad \cdot \quad(a+d)+\quad(a+(n-1) d)\) \\
\(S=(a+(n-1) d)+(a+(n-2) d)+\ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots+a\)
\end{tabular}
\end{tabular} & M1 & 3.1a \\
\hline & \begin{tabular}{l} 
Reaches \(2 S=n \times(2 a+(n-1) d)\) \\
And so proves that \(S=\frac{n}{2}[2 a+(n-1) d] *\)
\end{tabular} & A1* & 2.1 \\
\hline & & (3) & \\
\hline \multirow[t]{7}{*}{ (ii) } & (a) \(S=10+9.20+8.40+\ldots\) & & \\
\hline & \(64=\frac{n}{2}(20-0.8(n-1)) \quad\) o.e & M1 & \(3.1 b\) \\
\hline & \begin{tabular}{l}
\begin{tabular}{c}
\(128=20 n-0.8 n^{2}+0.8 n\) \\
\(0.8 n^{2}-20.8 n+128=0\) \\
\(n^{2}-26 n+160=0 *\)
\end{tabular}
\end{tabular} & A1* & 2.1 \\
\hline & & (2) & \\
\hline & (b) \(n=10,16\) & B1 & \(1.1 b\) \\
\hline & & (1) & \\
\hline & \begin{tabular}{l} 
(c) 10 weeks with a minimal correct reason. E.g. \\
- He has saved up the amount by 10 weeks so he would \\
not save for another 6 weeks \\
- You would choose the smaller number \\
- He starts saving negative amounts (in week 14 ) so 16 \\
does not make sense
\end{tabular} & B1 & 2.3 \\
\hline & & (1) & \\
\hline \multicolumn{4}{|l|}{ (7 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}
(i)

B1: Correctly writes down an expression for the key terms \(S\) or \(S_{n}\) including \(S=\) or \(S_{n}=\)
Allow a minimum of 3 correct terms including the first and last terms, and no incorrect terms.
Score for \(S\) or \(S_{n}=a+(a+d)+\) .\(+(a+(n-1) d)\) with + signs, not commas
If the series contains extra terms that should not be there E.g
\(S=a+(a+d)+\ldots \ldots \ldots \ldots \ldots \ldots \ldots(\boldsymbol{a}+\boldsymbol{n d})+(a+(n-1) d)\) score B0
M1: For the key step in reversing the terms and adding the two series.
Look for a minimum of two terms, including \(a\) and \(a+(n-1) d\), the series reversed with evidence of adding, for example \(2 S=\) Condone the extra incorrect terms (see above) appearing.
Can be scored when terms are separated by commas
A1*: Shows correct work (no errors) with all steps shown leading to given answer.
There should be no incorrect terms. A minimum of 3 terms should be shown in each sum

The solution below is a variation of this.
\[
\begin{aligned}
& S=a+(a+d)+\ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \ldots \\
& S=l+(l-d)+\ldots \ldots \\
& 2 S=n(a+l) \\
& S=\frac{n}{2}(a+l)=\frac{n}{2}(a+a+(n-1) d)=\frac{n}{2}(2 a+(n-1) d)
\end{aligned}
\]

B1 and A1 are not scored until the last line, \(M\) scored on line 3
The following scores B 1 M 0 A 0 as the terms in the second sum are not reversed

![](https://cdn.mathpix.com/cropped/2024_10_02_ac75d09201ee034eecfag-27.jpg?height=423&width=1252&top_left_y=625&top_left_x=399)

SC in (a) Scores B1 M0 A0.
They use \(0+1+2+\ldots .+(n-1)=\frac{n(n-1)}{2}\) which relies on the quoted proof.

![](https://cdn.mathpix.com/cropped/2024_10_02_ac75d09201ee034eecfag-27.jpg?height=518&width=780&top_left_y=1277&top_left_x=501)
(ii) (a)

M1: Uses the information given to set up a correct equation in \(n\).
The values of \(S, a\) and \(d\) need to be correct and used within a correct formula
Possible ways to score this include unsimplified versions \(64=\frac{n}{2}(2 \times 10+(n-1) \times-0.8)\),
\(64=\frac{n}{2}(10+10+(n-1) \times-0.8)\) or versions using pence rather than \(£^{\prime}\) s \(6400=\frac{n}{2}(2000+(n-1) \times-80)\)
Allow recovery for both marks following \(64=\frac{n}{2}(2 \times 10+(n-1)-0.8)\) with an invisible \(\times\)
A1*: Proceeds without error to the given answer. (Do not penalise a missing final trailing bracket )
Look for at least a line with the brackets correctly removed as well as a line with the terms in \(n\) correctly combined
E.g. \(64=\frac{n}{2}(20+(n-1) \times-0.8) \Rightarrow 64=10 n-0.4 n^{2}+0.4 n \Rightarrow 0.4 n^{2}-10.4 n+64=0 \Rightarrow n^{2}-26 n+160=0\)
(ii)(b)

B1: \(n=10,16\)
(ii)(c)

B1: Chooses 10 (weeks) and gives a minimal acceptable reason. The reason must focus on why the answer is 10 (weeks) rather than 16(weeks) or alternatively why it would not be 16 weeks.
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline \multirow[t]{5}{*}{ 14(a) } & \begin{tabular}{l} 
Attempts to use both \\
\begin{tabular}{l}
\(\sin \left(x-60^{\circ}\right)= \pm \sin x \cos 60^{\circ} \pm \cos x \sin 60^{\circ}\) \\
\(\cos \left(x-30^{\circ}\right)= \pm \cos x \cos 30^{\circ} \pm \sin x \sin 30^{\circ}\)
\end{tabular}
\end{tabular} & M1 & 2.1 \\
\hline & \begin{tabular}{l} 
Correct equation \\
\(2 \sin x \cos 60^{\circ}-2 \cos x \sin 60^{\circ}=\cos x \cos 30^{\circ}+\sin x \sin 30^{\circ}\)
\end{tabular} & A1 & \(1.1 b\) \\
\hline & \begin{tabular}{l} 
Either uses \(\frac{\sin x}{\cos x}=\tan x\) and attempts to make \(\tan x\) the subject \\
E.g. \(\left(2 \cos 60^{\circ}-\sin 30^{\circ}\right) \tan x=\cos 30^{\circ}+2 \sin 60^{\circ}\) \\
Or attempts \(\sin 30^{\circ}\) etc with at least two correct and collects terms in \\
\(\sin x\) and \(\cos x\) \\
E.g. \(\left(2 \times \frac{1}{2}-\frac{1}{2}\right) \sin x=\left(2 \times \frac{\sqrt{3}}{2}+\frac{\sqrt{3}}{2}\right) \cos x\)
\end{tabular} & M1 & 2.1 \\
\hline & \begin{tabular}{l} 
Proceeds to given answer showing all key steps \\
E.g. \(\frac{1}{2} \tan x=\frac{3 \sqrt{3}}{2} \Rightarrow \tan x=3 \sqrt{3}\)
\end{tabular} & A1* & \(1.1 b\) \\
\hline & & (4) & \\
\hline \multirow[t]{3}{*}{ (b) } & Deduces that \(x=2 \theta+60^{\circ}\) & B1 & 2.2 a \\
\hline & \(\tan \left(2 \theta+60^{\circ}\right)=3 \sqrt{3} \Rightarrow 2 \theta+60^{\circ}=79.1^{\circ}, 259.1^{\circ}, \ldots .\). & M1 & 1.1 b \\
\hline & \begin{tabular}{l} 
Correct method to find one value of \(\theta\) E.g \(\theta=\frac{79.1^{\circ}-60^{\circ}}{2}\)
\end{tabular} & dM1 & \(1.1 b\) \\
\hline & \(\theta=\) awrt \(9.6^{\circ}, 99.6^{\circ}\) (See note) & A1 & 2.1 \\
\hline & & (4) & \\
\hline \multicolumn{4}{|l|}{ (8 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}
(a)

M1: Attempts to use both compound angle expansions to set up an equation in \(\sin x\) and \(\cos x\) The terms must be correct but condone sign errors and a slip on the multiplication of 2
A1: Correct equation \(2 \sin x \cos 60^{\circ}-2 \cos x \sin 60^{\circ}=\cos x \cos 30^{\circ}+\sin x \sin 30^{\circ}\) o.e.
Note that \(\cos 60^{\circ}=\sin 30^{\circ}\) and \(\cos 30^{\circ}=\sin 60^{\circ}\)
Also allow this mark for candidates who substitute in their trigonometric values "early"
\[
2 \sin x \times \frac{1}{2}-2 \cos x \times \frac{\sqrt{3}}{2}=\cos x \times \frac{\sqrt{3}}{2}+\sin x \times \frac{1}{2} \text { o.e. }
\]

M1: Shows the necessary progress towards showing the given result.
There are three key moves, two of which must be shown for this mark.
- uses \(\frac{\sin x}{\cos x}=\tan x\) to form an equation in just \(\tan x\).
- uses exact numerical values for \(\sin 30^{\circ}, \sin 60^{\circ}, \cos 30^{\circ}, \cos 60^{\circ}\) with at least two correct
- collects terms in \(\sin x\) and \(\cos x\) or alternatively in \(\tan x\)

A1*: Proceeds to the given answer with accurate work showing all necessary lines.

Examples of two proofs showing all necessary lines

E.g. I \(\quad 2 \sin x \cos 60^{\circ}-2 \cos x \sin 60^{\circ}=\cos x \cos 30^{\circ}+\sin x \sin 30^{\circ}\)
\[
\begin{aligned}
& \sin x\left(2 \cos 60^{\circ}-\sin 30^{\circ}\right)=\cos x\left(\cos 30^{\circ}+2 \sin 60^{\circ}\right) \quad \text { 1. collect terms } \\
& \left(2 \cos 60^{\circ}-\sin 30^{\circ}\right) \tan x=\cos 30^{\circ}+2 \sin 60^{\circ} \\
& \text { 2. } \frac{\sin x}{\cos x}=\tan x \text { so M1 } \\
& \tan x=\frac{\cos 30^{\circ}+2 \sin 60^{\circ}}{2 \cos 60^{\circ}-\sin 30^{\circ}}=\frac{\frac{\sqrt{3}}{2}+\sqrt{3}}{1-\frac{1}{2}}=3 \sqrt{3} \\
& \text { 3..uses values and completes proof } \mathrm{A} 1^{*}
\end{aligned}
\]
E.g II
\[
\begin{array}{rlr}
2 \sin x \times \frac{1}{2}-2 \cos x \times \frac{\sqrt{3}}{2}=\cos x \times \frac{\sqrt{3}}{2}+\sin x \times \frac{1}{2} & \text { 1.uses values } \\
\Rightarrow \frac{1}{2} \sin x & =\frac{3 \sqrt{3}}{2} \cos x & \text { 2.collects terms so M1 } \\
\Rightarrow \tan x & =3 \sqrt{3} & \text { 3. } \frac{\sin x}{\cos x}=\tan x \text { completes proof A1* }
\end{array}
\]

\section*{(b) Hence}

B1: Deduces that \(x=2 \theta+60^{\circ}\) o.e such as \(\theta=\frac{x-60^{\circ}}{2}\)
This is implied for sight of the equation \(\tan \left(2 \theta+60^{\circ}\right)=3 \sqrt{3}\)
M1: Proceeds from \(\tan \left(2 \theta \pm \alpha^{\circ}\right)=3 \sqrt{3} \Rightarrow 2 \theta \pm \alpha^{\circ}=\) one of \(79.1^{\circ}, 259.1^{\circ}, \ldots .\). where \(\alpha \neq 0\)
One angle for \(\arctan (3 \sqrt{3})\) must be correct in degrees or radians( 3 sf ). FYI radian answers 1.38, 4.52
dM1: Correct method to find one value of \(\theta\) from their \(2 \theta \pm \alpha^{\circ}=79.1^{\circ}\) to \(\theta=\frac{79.1^{\circ} \mp \alpha^{\circ}}{2}\)
This is dependent upon one angle being correct, which must be in degrees, for \(\arctan (3 \sqrt{3})\) \(\tan \left(2 \theta+60^{\circ}\right)=3 \sqrt{3} \Rightarrow \theta=9.6^{\circ}\) would imply B1 M1 dM1
A1: \(\theta=\) awrt \(9.6^{\circ}, 99.6^{\circ}\) with no other values given in the range
Otherwise: Via the use of \(\cos \left(2 \theta+30^{\circ}\right)=\cos 2 \theta \cos 30^{\circ}-\sin 2 \theta \sin 30^{\circ}\).
\(2 \sin 2 \theta=\cos \left(2 \theta+30^{\circ}\right) \Rightarrow \tan 2 \theta=\frac{\sqrt{3}}{5} \Rightarrow \theta=9.6^{\circ}, 99.6^{\circ}\)

\section*{The order of the marks needs to match up to the main scheme so 0110 is possible.}

B1: For achieving \(\tan 2 \theta=\frac{\sqrt{3}}{5}\) o.e so allow \(\tan 2 \theta=\operatorname{awrt} 0.346\) or \(\tan 2 \theta=\frac{\cos 30^{\circ}}{2+\sin 30^{\circ}}\)
Or via double angle identities \(\sqrt{3} \tan ^{2} \theta+10 \tan \theta-\sqrt{3}=0\) o.e.
M1: Attempts to use the compound angle identities to reach a form \(\tan 2 \theta=k\) where \(k\) is a constant not \(3 \sqrt{3}\) (or expression in trig terms such as \(\cos 30\) etc as seen above)

Or via double angle identities reaches a 3 TQ in \(\tan \theta\)
dM 1 : Correct order of operations from \(\tan 2 \theta=k\) leading to \(\theta=\ldots\)
Correctly solves their \(\sqrt{3} \tan ^{2} \theta+10 \tan \theta-\sqrt{3}=0\) leading to \(\theta=\ldots\)
A1: \(\theta=\) awrt \(9.6^{\circ}, 99.6^{\circ}\) with no other values given in the range.
Note that \(\tan \left(2 \theta+60^{\circ}\right)=3 \sqrt{3} \Rightarrow \theta=9.6^{\circ}, 99.6^{\circ}\) is acceptable for full marks
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline 15 (a) & \begin{tabular}{l} 
Sets up an allowable equation using volume \(=240\) \\
E.g. \(\frac{1}{2} r^{2} \times 0.8 h=240 \Rightarrow h=\frac{600}{r^{2}}\) o.e.
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{l} 
M1 \\
A1
\end{tabular}
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{l}
3.4 \\
1.1 b
\end{tabular}
\end{tabular} \\
\hline & \begin{tabular}{l} 
Attempts to substitute their \(h=\frac{600}{r^{2}}\) into \\
\((S=) \frac{1}{2} r^{2} \times 0.8+\frac{1}{2} r^{2} \times 0.8+2 r h+0.8 r h\)
\end{tabular} & dM1 & 3.4 \\
\hline & \begin{tabular}{l}
\(S=0.8 r^{2}+2.8 r h=0.8 r^{2}+2.8 \times \frac{600}{r}=0.8 r^{2}+\frac{1680}{r} *\)
\end{tabular} & A1* & 2.1 \\
\hline & & (4) & \\
\hline (b) & \begin{tabular}{l}
\(\left(\frac{\mathrm{d} S}{\mathrm{~d} r}\right)=1.6 r-\frac{1680}{r^{2}}\)
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{l}
\hline M1 \\
A1
\end{tabular}
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{l}
\hline 3.1 a \\
1.1 b
\end{tabular}
\end{tabular} \\
\hline & \begin{tabular}{l}
\begin{tabular}{l} 
Sets \(\frac{\mathrm{d} S}{\mathrm{~d} r}=0 \Rightarrow r^{3}=1050\) \\
\(r=\) awrt 10.2
\end{tabular}
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{c}
d 1 1 1 \\
A 1
\end{tabular}
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{l}
2.1 \\
1.1 b
\end{tabular}
\end{tabular} \\
\hline & & (4) & \\
\hline (c) & \begin{tabular}{l} 
Attempts to substitute their positive \(r\) into \(\left(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}\right)=1.6+\frac{3360}{r^{3}}\) \\
and considers its value or sign
\end{tabular} & M1 & \(1.1 b\) \\
\hline & \begin{tabular}{l} 
E.g. Correct \(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}=1.6+\frac{3360}{r^{3}}\) with \(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}{ }_{r=10.2}=5>0\) proving a \\
minimum value of \(S\)
\end{tabular} & A1 & \(1.1 b\) \\
\hline & & (2) & \\
\hline \multicolumn{4}{|l|}{ (10 marks) } \\
\hline \multicolumn{4}{|l|}{ Notes: } \\
\hline
\end{tabular}

Volume \(=0.4 r^{2} h\)

![](https://cdn.mathpix.com/cropped/2024_10_02_ac75d09201ee034eecfag-30.jpg?height=540&width=1240&top_left_y=1863&top_left_x=568)

Total surface area \(=2 r h+0.8 r^{2}+0.8 r h\)
(a)

M1: Attempts to use the fact that the volume of the toy is \(240 \mathrm{~cm}^{3}\)
Sight of \(\frac{1}{2} r^{2} \times 0.8 \times h=240\) leading to \(h=\ldots\) or \(r h=\ldots\) scores this mark
But condone an equation of the correct form so allow for \(k r^{2} h=240 \Rightarrow h=\ldots\) or \(r h=\ldots\)
A1: A correct expression for \(h=\frac{600}{r^{2}}\) or \(r h=\frac{600}{r}\) which may be left unsimplified.
This may be implied when you see an expression for S or part of S E.g \(2 r h=2 r \times \frac{600}{r^{2}}\)
dM1: Attempts to substitute their \(h=\frac{a}{r^{2}}\) o.e. such as \(h r=\frac{a}{r}\) into a correct expression for \(S\)
Sight of \(\frac{1}{2} r^{2} \times 0.8+\frac{1}{2} r^{2} \times 0.8+r h+r h+0.8 r h\) with an appropriate substitution
Simplified versions such as \(0.8 r^{2}+2 r h+0.8 r h\) used with an appropriate substitution is fine.
A1*: Correct work leading to the given result.
\(S=, S A=\) or surface area = must be seen at least once in the correct place
The method must be made clear so expect to see evidence. For example
\(S=0.8 r^{2}+2 r h+0.8 r h \Rightarrow S=0.8 r^{2}+2 r \times \frac{600}{r^{2}}+0.8 r \times \frac{600}{r^{2}} \Rightarrow S=0.8 r^{2}+\frac{1680}{r}\) would be fine.
(b) There is no requirement to see \(\frac{\mathrm{d} S}{\mathrm{~d} r}\) in part (b). It may even be called \(\frac{\mathrm{d} y}{\mathrm{~d} x}\).

M1: Achieves a derivative of the form \(p r \pm \frac{q}{r^{2}}\) where \(p\) and \(q\) are non- zero constants
A1: Achieves \(\left(\frac{\mathrm{d} S}{\mathrm{~d} r}\right)=1.6 r-\frac{1680}{r^{2}}\)
dM1: Sets or implies that their \(\frac{\mathrm{d} S}{\mathrm{~d} r}=0\) and proceeds to \(m r^{3}=n, \quad m \times n>0\). It is dependent upon a correct attempt at differentiation. This mark may be implied by a correct answer to their \(p r-\frac{q}{r^{2}}=0\)
A1: \(r=\) awrt 10.2 or \(\sqrt[3]{1050}\)
(c)

M1: Attempts to substitute their positive \(r\) (found in (b)) into \(\left(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}=\right) e \pm \frac{f}{r^{3}}\) where \(e\) and \(f\) are non zero and finds its value or sign.
Alternatively considers the sign of \(\left(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}=\right) e \pm \frac{f}{r^{3}}\) (at their positive \(r\) found in (b))
Condone the \(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}\) to be \(\frac{\mathrm{d}^{2} y}{\mathrm{~d} x^{2}}\) or being absent, but only for this mark.
A1: States that \(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}\) or \(S^{\prime \prime}=1.6+\frac{3360}{r^{3}}=\) awrt \(5>0\) proving a minimum value of \(S\)
This is dependent upon having achieved \(r=\) awrt 10 and a correct \(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}=1.6+\frac{3360}{r^{3}}\) It can be argued without finding the value of \(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}\). E.g. \(\frac{\mathrm{d}^{2} S}{\mathrm{~d} r^{2}}=1.6+\frac{3360}{r^{3}}>0\) as \(r>0\), so minimum value of \(S\). For consistency it is also dependent upon having achieved \(r=\) awrt 10 Do NOT allow \(\frac{\mathrm{d}^{2} y}{\mathrm{~d} x^{2}}\) for this mark
\begin{tabular}{|c|c|c|c|}
\hline Question & Scheme & Marks & AOs \\
\hline 16 (a) & \begin{tabular}{l} 
Attempts \\
\(y \cdot \frac{\mathrm{~d} x}{\mathrm{~d} t}=(2 \sin 2 t+3 \sin t) \times 16 \sin t \cos t\) and uses \(\sin 2 t=2 \sin t \cos t\)
\end{tabular} & M1 & 2.1 \\
\hline & \begin{tabular}{l} 
Correct expanded integrand. Usually for one of \\
\((R)=\int \underline{\underline{48 \sin ^{2} t \cos t+16 \sin ^{2} 2 t} \mathrm{~d} t}\) \\
\((R)=\int \underline{\underline{48 \sin ^{2} t \cos t+64 \sin ^{2} t \cos ^{2} t} \mathrm{~d} t}\) \\
\((R)=\int \underline{\underline{24 \sin 2 t \sin t+16 \sin ^{2} 2 t} \mathrm{~d} t}\)
\end{tabular} & A1 & \(1.1 b\) \\
\hline & Attempts to use \(\cos 4 t=1-2 \sin ^{2} 2 t=\left(1-8 \sin ^{2} t \cos ^{2} t\right)\) & M1 & \(1.1 b\) \\
\hline & \begin{tabular}{l}
\(R=\int_{0}^{a} 8-8 \cos 4 t+48 \sin ^{2} t \cos t \mathrm{~d} t \quad *\)
\end{tabular} & A1* & 2.1 \\
\hline & Deduces \(a=\frac{\pi}{4}\) & B1 & 2.2 a \\
\hline & & (5) & \\
\hline (b) & \begin{tabular}{l}
\(\int 8-8 \cos 4 t+48 \sin ^{2} t \cos t \mathrm{~d} t=8 t-2 \sin 4 t+16 \sin ^{3} t\)
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{l} 
M1 \\
A1
\end{tabular}
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{c}
\hline 2.1 \\
\(1.1 b\)
\end{tabular}
\end{tabular} \\
\hline & \begin{tabular}{l}
{\(\left[8 t-2 \sin 4 t+16 \sin ^{3} t\right]_{0}^{\frac{\pi}{4}}=2 \pi+4 \sqrt{2}\)}
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{l} 
M1 \\
A1
\end{tabular}
\end{tabular} & \begin{tabular}{l}
\begin{tabular}{c}
2.1 \\
1.1 b
\end{tabular}
\end{tabular} \\
\hline & & (4) & \\
\hline \multicolumn{4}{|l|}{ (9 marks) } \\
\hline Notes: & & & \\
\hline
\end{tabular}
(a) Condone work in another variable, say \(\theta \leftrightarrow t\) if used consistently for the first \(\mathbf{3}\) marks

M1: For the key step in attempting \(y \cdot \frac{\mathrm{~d} x}{\mathrm{~d} t}=(2 \sin 2 t+3 \sin t) \times 16 \sin t \cos t\) with an attempt to use \(\sin 2 t=2 \sin t \cos t \quad\) Condone slips in finding \(\frac{\mathrm{d} x}{\mathrm{~d} t}\) but it must be of the form \(k \sin t \cos t\)
E.g. I \(y . \frac{\mathrm{d} x}{\mathrm{~d} t}=(2 \sin 2 t+3 \sin t) \times k \sin t \cos t=(4 \sin t \cos t+3 \sin t) \times k \sin t \cos t\)
E.g. II \(y . \frac{\mathrm{d} x}{\mathrm{~d} t}=(2 \sin 2 t+3 \sin t) \times k \sin t \cos t=(2 \sin 2 t+3 \sin t) \times \frac{k}{2} \sin 2 t\)

A1: A correct (expanded) integrand in \(t\). Don't be concerned by the absence of \(\int\) or \(\mathrm{d} t\) or limits
\[
(R)=\int \underline{\underline{48 \sin ^{2} t \cos t+16 \sin ^{2} 2 t} \mathrm{~d} t} \text { or }(R)=\int \underline{\underline{48 \sin ^{2} t \cos t+64 \sin ^{2} t \cos ^{2} t \mathrm{~d} t}}
\]
but watch for other correct versions such as \((R)=\int \underline{\underline{24 \sin 2 t \sin t+16 \sin ^{2} 2 t} \mathrm{~d} t}\)

M1: Attempts to use \(\cos 4 t= \pm 1 \pm 2 \sin ^{2} 2 t\) to get the integrand in the correct form.
If they have the form \(P \sin ^{2} 2 t\) it is acceptable to write \(P \sin ^{2} 2 t=\frac{P}{2}( \pm 1 \pm \cos 4 t)\)
If they have the form \(Q \sin ^{2} t \cos ^{2} t\) sight and use of \(\sin 2 t\) and/or \(\cos 2 t\) will usually be seen first.
There are many ways to do this, below is such an example
\(Q \sin ^{2} t \cos ^{2} t=Q\left(\frac{1-\cos 2 t}{2}\right)\left(\frac{1+\cos 2 t}{2}\right)=Q\left(\frac{1-\cos ^{2} 2 t}{4}\right)=Q\left(\frac{1}{4}-\frac{\cos ^{2} 2 t}{4}\right)=Q\left(\frac{1}{4}-\frac{1+\cos 4 t}{8}\right)\)
Allow candidates to start with the given answer and work backwards using the same rules. So expect to see \(\cos 4 t= \pm 1 \pm 2 \times \sin ^{2} 2 t\) or \(\cos 4 t= \pm 2 \times \cos ^{2} 2 t \pm 1\) before double angle identities for \(\sin 2 t\) or \(\cos 2 t\) are used.
A1*: Proceeds to the given answer with correct working. The order of the terms is not important. Ignore limits for this mark. The integration sign and the \(\mathrm{d} t\) must be seen on their final answer. If they have worked backwards there must be a concluding statement to the effect that they know that they have shown it. The integration sign and the \(d \mathrm{t}\) must also be seen
E.g. Reaches \(\int 48 \sin ^{2} t \cos t+64 \sin ^{2} t \cos ^{2} t \mathrm{~d} t\)

Answer is \(\quad \int 8-8 \cos 4 t+48 \sin ^{2} t \cos t \mathrm{~d} t\)
\[
\begin{aligned}
& =\int 8-8\left(1-2 \sin ^{2} 2 t\right)+48 \sin ^{2} t \cos t \mathrm{~d} t \\
& =\int 16 \sin ^{2} 2 t+48 \sin ^{2} t \cos t \mathrm{~d} t \\
& =\int 64 \sin ^{2} t \cos ^{2} t+48 \sin ^{2} t \cos t \mathrm{~d} t
\end{aligned}
\]
which is the same, \(\checkmark\)
B1: Deduces \(a=\frac{\pi}{4}\). It may be awarded from the upper limit and can be awarded from (b)
(b)

M1: For the key process in using a correct approach to integrating the trigonometric terms.
May be done separately.
There may be lots of intermediate steps (e.g. let \(u=\sin t\) ).
There are other more complicated methods so look carefully at what they are doing.
\(\int 8-8 \cos 4 t+48 \sin ^{2} t \cos t \mathrm{~d} t=\ldots \pm P \sin 4 t \pm Q \sin ^{3} t\) where \(P\) and \(Q\) are constants
A1: \(\int 8-8 \cos 4 t+48 \sin ^{2} t \cos t \mathrm{~d} t=8 t-2 \sin 4 t+16 \sin ^{3} t(+c)\)
If they have written \(16 \sin ^{3} t\) as \(16 \sin t^{3}\) only award if further work implies a correct answer.
Similarly, \(8 t\) may be written as \(8 x\). Award if further work implies \(8 t\), e.g. substituting in their limits.
Do not penalise this sort of slip at all, these are intermediate answers.
M1: Uses the limits their \(a\) and 0 where \(a=\frac{\pi}{6}, \frac{\pi}{4}\) or \(\frac{\pi}{3}\) in an expression of the form \(k t \pm P \sin 4 t \pm Q \sin ^{3} t\) leading to an exact answer. Ignore evidence at lower limit as terms are 0
A1: CSO \(2 \pi+4 \sqrt{2}\) or exact simplified equivalent such as \(2 \pi+\frac{8}{\sqrt{2}}\) or \(2 \pi+\sqrt{32}\).

![](https://cdn.mathpix.com/cropped/2024_10_02_ac75d09201ee034eecfag-33.jpg?height=124&width=1688&top_left_y=2531&top_left_x=344) correct answer but would only score M1 A0 M1 A0