graph TD
    subgraph Row1[Harvesting]
        A1[The Numbers] 
        A2[Comentary] 
    end

    subgraph Row2[Storage]
        B1[The Numbers] 
        B2[Comentary] 
        B3[Reflection]
    end

    subgraph Row3[Derived Measurements]
        C1[Graph of Numbers]
        C2[Trend on highlighted Areas]
        
    end
    Row1 --> Row2
    Row2 --> Row3
