graph TD
    A[Two NEMids]
    A1[Same strand]
    A2[Different Strands]

    A --> A1
    A --> A2

    A1 --> A1A[Open strand 1A]
    A1 --> A1B[Closed strand 1B]

    A2 --> A2A[One is open 2A]
    A2 --> A2B[Both are open 2B]
    A2 --> A2C[Neither are open 2C]

