---
title: Czy dostał kredyt?
---

graph TD;
    A[dochody] -->|niskie| B[wklad_wlasny]
    A -->|srednie| C[stan_cywilny]
    A -->|wysokie| D[tak]

    B -->|">20%"| E[tak]
    B -->|"10%"| F[nie]

    C -->|w zwiazku| G[tak]
    C -->|wolny| H[nie]

    classDef yesNode fill:#9f6,stroke:#333,stroke-width:2px;
    classDef noNode fill:#f99,stroke:#333,stroke-width:2px;
    class D,E,G yesNode;
    class F,H noNode;
