graph LR
  AppModule-->AuthModule
  AppModule-->ConfigHostModule
  AppModule-->ConfigModule
  AppModule-->DebugModule
  AppModule-->LoggerModule
  AppModule-->ParticipationModule
  AppModule-->PassportModule
  AppModule-->ProjectModule
  AppModule-->UserModule
  AuthModule-->ConfigHostModule
  AuthModule-->JwtModule
  AuthModule-->PassportModule
  ConfigModule-->ConfigHostModule
  CurrencyModule-->ConfigHostModule
  CurrencyModule-->DbModule
  DbModule-->ConfigHostModule
  DbModule-->ConfigModule
  DbModule-->LoggerModule
  DbModule-->MemoryDbModule
  DebugModule-->ConfigHostModule
  DebugModule-->MemoryDbModule
  ExpensesModule-->ConfigHostModule
  ExpensesModule-->CurrencyModule
  ExpensesModule-->DbModule
  ExpensesModule-->LoggerModule
  ExpensesModule-->PaymentTypeModule
  ExpensesModule-->UserModule
  JwtModule-->ConfigHostModule
  LoggerModule-->ConfigHostModule
  MemoryDbModule-->ConfigHostModule
  MemoryDbModule-->ConfigModule
  MemoryDbModule-->LoggerModule
  ParticipationModule-->ConfigHostModule
  ParticipationModule-->ConfigModule
  ParticipationModule-->DbModule
  ParticipationModule-->ExpensesModule
  ParticipationModule-->LoggerModule
  ParticipationModule-->ProjectModule
  ParticipationModule-->UserModule
  PassportModule-->ConfigHostModule
  PaymentTypeModule-->ConfigHostModule
  PaymentTypeModule-->DbModule
  PaymentTypeModule-->LoggerModule
  ProjectModule-->ConfigHostModule
  ProjectModule-->ConfigModule
  ProjectModule-->DbModule
  ProjectModule-->ExpensesModule
  ProjectModule-->LoggerModule
  UserModule-->ConfigHostModule
  UserModule-->ConfigModule
  UserModule-->DbModule
  UserModule-->LoggerModule