graph LR
  AppModule-->AuthModule
  AppModule-->ClientModule
  AppModule-->EventsManagementModule
  AppModule-->JwtModule
  AppModule-->NewspaperModule
  AppModule-->UploadModule
  AppModule-->UsersManagmentModule
  AuthModule-->AppModule
  AuthModule-->JwtModule
  ClientModule-->AppModule
  ClientModule-->JwtModule
  EventsManagementModule-->AppModule
  EventsManagementModule-->JwtModule
  JwtModule-->AppModule
  MulterModule-->AppModule
  MulterModule-->JwtModule
  NewspaperModule-->AppModule
  NewspaperModule-->JwtModule
  UploadModule-->AppModule
  UploadModule-->JwtModule
  UploadModule-->MulterModule
  UsersManagmentModule-->AppModule
  UsersManagmentModule-->JwtModule