graph TD
    root[/ /]
    root --> bin
    root --> etc
    root --> home
    root --> opt
    root --> tmp
    root --> usr
    root --> var

    home --> durga
    home --> akshay

    usr --> usr_bin[bin]
    usr --> usr_lib[lib]
    
    var --> log

    style root fill:#f9f,stroke:#333,stroke-width:2px
    linkStyle default orthogonal