graph LR
    A[File Information] --> B[Type of file]
    A --> C[File permissions]
    A --> D[Number of links]
    A --> E[Owner name]
    A --> F[Group name]
    A --> G[File size in bytes]
    A --> H[Last modified/creation time]
    A --> I[File name]
    
    B --> B1[-]
    C --> C1[-rw-r--r--]
    D --> D1[1]
    E --> E1[durga]
    F --> F1[durga]
    G --> G1[0]
    H --> H1[Jan 31 11:49]
    I --> I1[a.txt]
