graph LR
subgraph AI ["Artificial Intelligence (1950s)"]
   subgraph ML ["Machine Learning (1990s)"]
      subgraph NN ["Neural Networks"]
         subgraph DL ["Deep Learning (2000s)"]
            subgraph GenAI ["Generative AI (2020s)"]
            end
         end
      end
      subgraph RL ["Reinforcement Learning"]
      end
   end
end
