flowchart TD
    Title[Encounter Hierarchy] --> Drunk{Are you drunk?}
    Drunk --> |Yes| DrunkZone[Zone set to Drunken Stupor]
    Drunk --> |No| HardCoded
    DrunkZone -.- SSPD[If St. Sneaky Pete's Day and drunkenness 26+, receive SSPD Stupor]
    DrunkZone --> HardCoded
    HardCoded{Hard-Coded?}
    HardCoded --> |Yes| Encounter
    HardCoded --> |No| PortScan

    subgraph "Zone Overrides"
        ZoneOverrideNote["Not &quot;true&quot; wandering monsters.<br>These are special exceptions that have higher priority"]
        PortScan[Port Scan] --> ProtoPack[Protopack Ghost]
    end
    ProtoPack --> AstralMushroom

    AstralMushroom{"Flashbacks<br />(Astral Mushrooms)"} --> |Yes| Encounter
    AstralMushroom --> |No| MiniAdventurer

    MiniAdventurer{"Littlest Identity Crisis<br />(Mini-Adventurer)"} --> |Yes| Encounter
    MiniAdventurer --> |No| LlamaLama

    LlamaLama{"Welcome Back<br />(Llama Lama Gong)"} --> |Yes| Encounter
    LlamaLama --> |No| Lucky

    Lucky{"Lucky"} --> |Yes| Encounter
    Lucky --> |No| Hallowiener

    Hallowiener{"Hallowiener Dog"} --> |Yes| Encounter
    Hallowiener --> |No| SuperLikely

    SuperLikely{"Superlikely available<br>and conditions satisfied"} --- |Yes| SuperlikelyNote["Equal chance of encountering multiple satisfied superlikelies"] --> Encounter
    SuperLikely --> |No| Wanderers

    Wanderers{Wanderer Due?}
    Wanderers --> |Yes| RubberSpider
    Wanderers --> |No| Kramco

    %% Wanderer Priority
    subgraph "Wanderer Priority"
        RubberSpider[Rubber Spider] -->
        FeastOfBoris[Feast of Boris] -->
        Saber[Saber Friends] -->
        TimeSpinner[Time-Spinner Prank] -->
        VotingBooth[Vote Monster] -->
        Digitize[Digitize] -->
        Wink[Reanimator/Angel] -->
        Enamorang -->
        Nemesis[Nemesis Quest Thug] -->
        EDLMB[El Dia De Los Muertos]
    end
    EDLMB --> Encounter

    Kramco{Kramco Goblin} --> |Yes| Encounter
    Kramco --> |No| Hipster

    Hipster{Hipster/Goth} --> |Yes| Encounter
    Hipster --> |No| RollEncounter

    subgraph "Zone Encounter Selection"
        RollEncounter{Roll 1d100<br>against zone combat rate}
        RollEncounter --Combat--> AnyCombats
        RollEncounter ---> |Non-combat| AnyNonCombats

        AnyNonCombats{Any non-combats available?}
        AnyNonCombats ---> |Yes| RollNonCombat
        AnyNonCombats ---> |No| AnyCombats

        RollNonCombat[Roll for NC]
        RollNonCombat --> NonCombatInQueue{Rolled NC in queue?}
        NonCombatInQueue --> |Yes| NonCombatRejection{Roll for rejection}
        NonCombatInQueue --> |No| EncounterSelected
        NonCombatRejection --> |"Rejected (75%)"| RollNonCombat
        NonCombatRejection --> |"Accepted (25%)"| EncounterSelected

        AnyCombats{Any combats available?}
        AnyCombats --> |Yes| RollCombat
        AnyCombats --> |No| Tumbleweed --> EncounterSelected

        RollCombat[Roll for Combat]
        RollCombat --> Olfacted{Olfacted?}
        Olfacted --> |Yes| EncounterSelected
        Olfacted --> |No| CombatInQueue{Rolled combat in queue?}
        CombatInQueue --> |Yes| CombatRejection{Roll for rejection}
        CombatInQueue --> |No| EncounterSelected
        CombatRejection --> |"Accepted (25%)"| EncounterSelected
        CombatRejection --> |"Rejected (75%)"| RollCombat

        EncounterSelected[Encounter selected from zone]
    end

    EncounterSelected --> Encounter

    Encounter[That's your encounter!]