---
config:
  look: neo
  theme: mc
---
graph TD
    A["Запуск инкрементальный?<br>is_incremental()"]
    B["Считаем первый батч<br>до 2023-08-01"]
    C["Дата задана?<br>var()"]
    D[Считаем все<br>оставшиеся данные]
    E[Считаем одну дату]

    A -->|Нет<br>--full-refresh| B
    A -->|Да| C
    C -->|Нет| D
    C -->|Да| E
