graph TD
  country_population{{
    # Population of Countries
    China[1,439,323,776]
    India[1,380,004,385]
    "United States"[331,002,651]
    Indonesia[273,523,615]
  }}

  country_population --> |Bar Chart|