%%{init: {'theme': 'dark', 'themeVariables': { 'primaryTextColor': 'white'}}}%%
graph LR
    B[pandas] --> A[Lokal]
    C[matplotlib] --> A
    D[jupyter notebook] --> A
    E[geopandas] --> A
    A --> X[Project A]
    A --> Y[Project B]
    A --> Z[Projekt C]
