graph LR
1:startevent:((startevent)) --> 2:task:(Query all web shops for parts)
2:task: --> 3:exclusivegateway:{x}
3:exclusivegateway:{x} --> |If shop has enough parts| 4:task:(Order parts from cheapest shop)
3:exclusivegateway:{x} --> |If shop doesn't have enough parts| 5:task:(Order parts from several shops)
4:task: --> 6:task:(Wait for parts to arrive)
5:task: --> 6:task:
6:task: --> 7:task:(Start building when first parts arrive)
7:task: --> 8:exclusivegateway:{x}
8:exclusivegateway:{x} --> |If stock falls below 5| 9:task:(Reorder cheapest parts)
8:exclusivegateway:{x} --> |If stock falls below 3| 10:task:(Reorder fastest parts)
8:exclusivegateway:{x} --> |If stock is zero| 11:task:(Write a mail complaining about webshops)
9:task: --> 8:exclusivegateway:{x}
10:task: --> 8:exclusivegateway:{x}
11:task: --> 12:endevent:((endevent))

