flowchart TD
id1("(Write research protocol)") --> id2(Submit one ELAN ticket per research/article)
subgraph ticket [Takes at least 2 months]
    id4
end
id4(Process feedback, 
changes in protocol and 
ticket text when needed,
and await approval
from ELAN research committee) --> id5
id5(Submit final protocol
to the PHEG
Science Committee) -->|About 1 month| id6
id6(Await approval,
and process feedback
if applicable from
ELAN research committee) --> id7
id7(submit documents 
to nWMO committee) -->|1 to 2 months| id9
id9(Await approval) --> id10
id10(Upload approval
to ticket) --> idend(Start your data analysis!)
id6 --> id8
id8("Contact ELAN-DCC
to start 
set-up of your 
research data
(including the Data
Management Plan):
elan.dcc@lumc.nl") --> id11(Start process of
gaining access
to CBS or LUMC directories
and upload the DTA/DAA)

id2 --> ticket
id11 --> idend


style idend fill:#86c985,stroke:#4d934c,stroke-width:4px
style id2 fill:#c594c3
style id5 fill:#c594c3
style id7 fill:#c594c3
style id10 fill:#c594c3

style ticket fill:#efd5ef, stroke:#a57ca5

click id2 "https://elanresearch.nl" "ELAN research" _blank
click id5 "https://elan-dcc.github.io/researchers/sciencecommittee" "Science committee"
click id7 "https://www.metc-ldd.nl/toetsingsprocedures/niet-wmo-en-niet-mdr" "nWMO committee" _blank