graph TD;
  A["Runner"] --> M_1["Nucleic Acid Params Manager"];
  A --> M_2["Strands Manager"];
  A --> M_3["Domains Manager"];
  
  M_1 --> C_1[".current"]
  M_2 --> C_2[".current"]
  M_3 --> C_3[".current"]
