graph TD
microservice-demo-->|"HTTP Verb: GET<br/>Arguments: [@PathVariable(#quot;id#quot;) long id]<br/>Return: ResponseEntity<Customer><br/>Endpoint function: com.ewolff.microservice.order.customerstub.CustomerStub.getById"|microservice-demo
microservice-demo-->|"HTTP Verb: GET<br/>Arguments: [@PathVariable(#quot;id#quot;) long id]<br/>Return: ResponseEntity<Item><br/>Endpoint function: com.ewolff.microservice.order.catalogstub.CatalogStub.getById"|microservice-demo

