graph LR
    PC1 <--> Switch1
    PC2 <--> Switch1
    Switch1 <--> Router((Router))
    Router <--> Switch2
    Switch2 <--> PC3
    Switch2 <--> PC4
    Switch2 <--> PC5
    Router <--> Switch3
    Switch3 <--> PC6
    Switch3 <--> PC7
    Switch3 <--> PC8
