%%{
    init: {
        'theme': 'base', 
        'themeVariables': { 
            'fontSize': '25px',
            'primaryColor': '#0B6E4F',
            'primaryBorderColor': '#14cb92',
            'primaryTextColor': '#fff',
            'tertiaryTextColor': '#000',
            'fontFamily': 'Lexend'
        }
    }
}%%

graph LR
    I[Starting conditions] --> P[O/P/SDE Problem]
    F[Equations of motion] --> P
    SP[Simulation parameters] --> P