erDiagram
	SCENARIO-MANAGEMENT ||..o{ SCHEDULER : "triggers"
	TIME-BASED-VARIABLE o{--o| SCHEDULER : "feeds"
  EXECUTION-GRAPH o|..o{ SCHEDULER  : "outputs"
  SCHEDULER o{--|| MODEL : "initiates"
  SCHEDULER o{--|| SNAPSHOT : "initiates"
  SCHEDULER ||--|{ RESPONSE : "returns"
