graph TD
    A[SNMP-трап от коммутатора] --> B(Обработка трапа)
    B --> C{Проверка сообщества SNMP}
    C -->|Успешно| D[Проверка консистентности данных]
    D -->|Успешно| E[Анализ данных]
    E --> F{Анализ состояния порта}
    F -->|Порт включен| G[Включение порта]
    F -->|Порт выключен| H[Выключение порта]
    G --> I[Преобразование данных в JSON]
    I --> J[Сохранение данных в базе]
    H --> I
    C -->|Неуспешно| B
    D -->|Неуспешно| B
    E -->|Неуспешно| B
