graph TD
recommendation-client-->|"HTTP Verb: GET<br/>Arguments: [@RequestParam String ids]<br/>Return: Collection<MovieDTO><br/>Endpoint function: com.example.MovieController.getListMovies"|movie-service

