classDiagram 
    Format <|-- DateFormat
    Format <|-- MessageFormat
    Format <|-- NumberFormat
    DateFormat <|-- SimpleDateFormat
    NumberFormat <|-- ChoiceFormat
    NumberFormat <|-- CompactNumberFormat
    NumberFormat <|-- DecimalFormat
