classDiagram
    class root
    root *-- "1..*" Component

    class State
    root *-- "1..*" State

    class Component {
        +pin: Number
    }
    Component <|-- Sensor
    Component <|-- Alarm


    class Transition
    State *-- "1" Transition: transition
    class Action {
        +value: Signal
    }
    State *-- "0..*" Action: Actions
    Action --> "1" Alarm: alarm switch
    
    
    Transition --> "1" State : Next

    Transition <|-- PinBased

    class Condition {
        +name: ID
    }

    class SimpleCondition {
        
        +value: Signal
    }

    class ComposedCondition {
        +cond: SimpleCondition
        +op: OPERATOR
    }


    class  OPERATOR {
        +OR
        +AND
    }

    ComposedCondition o--> "2" SimpleCondition 

    Condition <|--  ComposedCondition
    Condition <|--  SimpleCondition

    PinBased *-- "1" Condition

    class Temporal {
       +duration: Number 
    }
    Transition <|-- Temporal

    PinBased --> "1..2" Sensor