classDiagram
    class Brand {
        +getAllegedName()
        +getDisplayInfo()
        +isMyIssuer(issuer)
        issuer.getBrand()
        payment.getAllegedBrand()
    }

    Issuer "1" -- "1" Brand : 1-to-1
    Mint "1" -- "1" Brand : 1-to-1

    class Issuer
    class Mint