classDiagram

    Category "1" o-- "0..*" Product : Contains
    Husband "1" -- "1" Wife : Married
    Instructor "1" -- "0..*" Batch : Teaches
    Batch "1" -- "0..*" Student : Has
    Theatre "*" -- "*" Movie : Shows