classDiagram
    class Category {
        uuid id
        string name
        string description
        boolean is_active
        date created_at
        
        create()
        update()
        activate()
        deactivate()
        delete()
    }
