classDiagram
    class CompatibilityDomain {
        <<abstract>>
        -qbm
        -tbm
        -computed
        +__init__(query_bit_matrix, target_bit_matrix)
        -_check_conditions(query_edge, target_edge)
        +compute()
        +get_all_query_edges()
        +get_domain(edge)
        +get_domain_cardinality(edge)
    }
    class CompatibilityDomainWithDictionary {
        -domain
        +__init__(query_bit_matrix, target_bit_matrix)
        +compute()
        +get_all_query_edges()
        +get_domain(edge)
        +get_domain_cardinality(edge)
    }

    CompatibilityDomain
    CompatibilityDomain <|-- CompatibilityDomainWithDictionary
