classDiagram
    class DesempenhoEscolar{
        -int rmEstudante
        -String nomeEstudante
        -int bimestre 
        -String curso
        -String disciplina
        -double n1
        -double n2
        -double n3
        -String mencaoFinal
        -int totalFaltas
        +double calculaNotaFinal()
        +String verificaSituacao()
    }
    
