classDiagram

class Enemy{
    +sprite
    +enemies []
    +animations []
    +health : int 
    +speed : int 
    +isDead : bool 
    +setup()
    +preload()
    +loadAnimations()
    +spawn(int, int)
    +behavior(wizard)
}