classDiagram
  class accounts {
  }
  class admin {
  }
  class apps {
  }
  class forms {
  }
  class migrations {
  }
  class 0001_initial {
  }
  class models {
  }
  class tests {
  }
  class urls {
  }
  class views {
  }
  admin --> forms
  admin --> models
  forms --> models
  views --> forms
