classDiagram
    direction BT
    class BaseException
    class Exception
    class node68
    class node29
    class object
    class node36
    class node21
    class node44
    class node75
    class node78
    class node35
    class node6
    class node69
    class node67
    class node62
    class node70
    class node32
    class node13
    class node28
    class node79
    class node5
    class node25
    class node45
    class node66
    class node46
    class node10
    class node59
    class node14
    class node60
    class node9
    class node73
    class node34
    class node41
    class node56
    class node20
    class node47
    class node33
    class node54
    class node49
    class node52
    class node51
    class node42
    class node57
    class node63
    class node8
    class node30
    class node2
    class node1
    class node22
    class node50
    class node55
    class node11
    class node15
    class node26
    class node64
    class node72
    class node4
    class node65
    class node27
    class node18
    class node77
    class node76
    class node39
    class node40
    class node37
    class node71
    class node24
    class node12
    class node23
    class node53
    class node38
    class node74
    class str
    class node31
    class node58
    class node61
    class node7
    class node43
    class node16
    class node3

    object --> BaseException
    BaseException --> Exception
    node29 "isinstanceof" ..> node68
    object --> node68
    node61 ..> node68
    node7 ..> node29
    node43 ..> node29
    node3 ..> node29
    node61 ..> object
    object --> node21
    node36 "isinstanceof" ..> node21
    node7 ..> node21
    node21 --> node44
    object --> node75
    object --> node78
    object --> node35
    node35 --> node6
    node35 --> node69
    node35 --> node67
    node35 --> node62
    node35 --> node70
    node35 --> node32
    Exception --> node13
    node59 --> node28
    node13 --> node79
    node13 --> node5
    node13 --> node25
    node13 --> node45
    node25 --> node66
    node25 --> node46
    node25 --> node10
    node13 --> node59
    node25 --> node14
    node13 --> node60
    node45 --> node9
    node25 --> node73
    node45 --> node34
    node13 --> node41
    node79 --> node56
    node13 --> node20
    node13 --> node47
    node13 --> node33
    node21 --> node54
    node21 --> node49
    node21 --> node52
    node21 --> node51
    node21 --> node42
    node21 --> node57
    node21 --> node63
    node21 --> node8
    node21 --> node30
    node21 --> node2
    node21 --> node1
    node21 --> node22
    node21 --> node50
    node21 --> node55
    node21 --> node11
    node21 --> node15
    node44 --> node26
    node44 --> node64
    node21 --> node72
    node72 --> node4
    node72 --> node65
    node21 --> node27
    node21 --> node18
    node68 --> node77
    str --> node77
    node21 --> node76
    node68 --> node39
    str --> node39
    node21 --> node40
    node68 --> node37
    str --> node37
    node21 --> node71
    node71 --> node24
    node71 --> node12
    node68 --> node23
    str --> node23
    node21 --> node53
    node53 --> node38
    node53 --> node74
    node61 ..> str
    node43 ..> str
    node3 --> str
    node58 --> node31
    node7 --> node31
    node7 --> node16
