```mermaid
---
title: Streamy Domain Model
---
classDiagram
    direction TB
    Title "1..*" -- "1..*" Genre: is associated with
    Title "1" *-- "0..*" Season: has
    Title "1" *-- "0..*" Review: has
    Title "0..*" o-- "1..*" Actor: features

    `TV Show` --|> Title: implements
    Short --|> Title: implements
    Film --|> Title: implements

    Viewer "0..*" --> "0..*" Title: watches

    Season "1" *-- "0..*" Review: has
    Season "1" *-- "1..*" Episode: contains

    Episode "1" *-- "0..*" Review: has

    %% Added to improve readability
    Title: \n
    style Title fill:#f9f

    %% Enrich Nodes with Links
    link Title "https://www.imdb.com/" _blank
```
