classDiagram

class RefCatalogInterface
CombineZernikesBaseTask <|-- CombineZernikesMeanTask
CombineZernikesBaseTask <|-- CombineZernikesSigmaClipTask
CombineZernikesBaseTask *-- CombineZernikesBaseConfig
CombineZernikesBaseConfig <|-- CombineZernikesSigmaClipTaskConfig
CombineZernikesSigmaClipTask *-- CombineZernikesSigmaClipTaskConfig
DonutSourceSelectorTask *-- DonutSourceSelectorTaskConfig
DonutQuickMeasurementTask *-- DonutQuickMeasurementTaskConfig
GenerateDonutCatalogOnlineTaskConfig *-- DonutSourceSelectorTask
GenerateDonutCatalogOnlineTask *-- GenerateDonutCatalogOnlineTaskConfig
GenerateDonutDirectDetectTaskConfig *-- GenerateDonutDirectDetectTaskConnections
GenerateDonutDirectDetectTaskConfig *-- DonutSourceSelectorTask
GenerateDonutDirectDetectTaskConfig *-- DonutQuickMeasurementTask
GenerateDonutDirectDetectTask *-- GenerateDonutDirectDetectTaskConfig
GenerateDonutDirectDetectTask ..> DonutTemplateFactory
GenerateDonutCatalogWcsTaskConfig *-- DonutSourceSelectorTask
GenerateDonutCatalogWcsTaskConfig *-- GenerateDonutCatalogWcsTaskConnections
GenerateDonutCatalogWcsTask *-- GenerateDonutCatalogWcsTaskConfig
DonutStamps *-- DonutStamp
CutOutDonutsBaseTaskConfig <|-- CutOutDonutsUnpairedTaskConfig
CutOutDonutsBaseTask <|-- CutOutDonutsUnpairedTask
CutOutDonutsUnpairedTaskConfig *-- CutOutDonutsBaseTaskConnections
CutOutDonutsUnpairedTask *-- CutOutDonutsUnpairedTaskConfig
CutOutDonutsUnpairedTask ..> DonutStamps
CutOutDonutsBaseTaskConfig <|-- CutOutDonutsCwfsTaskConfig
CutOutDonutsBaseTask <|-- CutOutDonutsCwfsTask
CutOutDonutsCwfsTaskConfig *-- CutOutDonutsBaseTaskConnections
CutOutDonutsCwfsTask *-- CutOutDonutsCwfsTaskConfig
CutOutDonutsCwfsTask ..> DonutStamps
CutOutDonutsBaseTaskConfig <|-- CutOutDonutsScienceSensorTaskConfig
CutOutDonutsBaseTask <|-- CutOutDonutsScienceSensorTask
CutOutDonutsScienceSensorTaskConfig *-- CutOutDonutsBaseTaskConnections
CutOutDonutsScienceSensorTask *-- CutOutDonutsScienceSensorTaskConfig
CutOutDonutsBaseTaskConnections <|-- CutOutDonutsScienceSensorTaskConnections
CutOutDonutsScienceSensorTaskConfig *-- CutOutDonutsScienceSensorTaskConnections
CutOutDonutsScienceSensorTaskConfig *-- ExposurePairer
CutOutDonutsScienceSensorTask ..> DonutStamps
CutOutDonutsBaseTaskConfig *-- CutOutDonutsBaseTaskConnections
CutOutDonutsBaseTask *-- CutOutDonutsBaseTaskConfig
CutOutDonutsBaseTask ..> DonutStamps
CutOutDonutsBaseTask ..> DonutStamp
CalcZernikesTaskConfig *-- CombineZernikesSigmaClipTask
CalcZernikesTaskConfig *-- CalcZernikesTaskConnections
CalcZernikesTask *-- CalcZernikesTaskConfig
CalcZernikesTask ..> DonutStamps
CalcZernikesUnpairedTaskConfig *-- CombineZernikesSigmaClipTask
CalcZernikesUnpairedTaskConfig *-- CalcZernikesUnpairedTaskConnections
CalcZernikesUnpairedTask *-- CalcZernikesUnpairedTaskConfig
CalcZernikesUnpairedTask ..> DonutStamps
GenerateDonutFromRefitWcsTaskConfig *-- GenerateDonutFromRefitWcsTaskConnections
GenerateDonutCatalogWcsTaskConfig <|-- GenerateDonutFromRefitWcsTaskConfig
GenerateDonutFromRefitWcsTask *-- GenerateDonutFromRefitWcsTaskConfig
GenerateDonutCatalogWcsTask <|-- GenerateDonutFromRefitWcsTask
ExposurePairer *-- ExposurePairerConfig
TablePairer *-- TablePairerConfig
