quadrantChart
    title "Reach and engagement of games"
    x-axis "Low Reach" --> "High Reach"
    y-axis "Low Engagement" --> "High Engagement"
    quadrant-1 "We should expand"
    quadrant-2 "Need to promote"
    quadrant-3 "Re-evaluate"
    quadrant-4 "May be improved"
    "Game A": [0.3, 0.6]
    "Game B": [0.45, 0.23]
    "Game C": [0.57, 0.69]
    "Game D": [0.78, 0.34]
    "Game E": [0.40, 0.34]
    "Game F": [0.35, 0.78]
    "Our Target Product": [0.5, 0.6]