quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Immigration NZ": [0.8, 0.6]
    "Just Landed": [0.7, 0.4]
    "Expat Arrivals": [0.6, 0.3]
    "MoveHub": [0.5, 0.4]
    "Visa Bureau": [0.4, 0.5]
    "Our Target Product": [0.6, 0.8]
