quadrantChart
    title Test Case Management Tools
    x-axis Low Automation Integration --> High Automation Integration
    y-axis Low Reporting and Visualization --> High Reporting and Visualization
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "TestRail": [0.7, 0.6]
    "Zephyr": [0.6, 0.8]
    "qTest": [0.9, 0.5]
    "PractiTest": [0.4, 0.7]
    "TestLodge": [0.5, 0.4]
    "TestLink": [0.3, 0.3]
    "Testuff": [0.6, 0.9]
    "Our Target Product": [0.8, 0.8]
