quadrantChart
    title Interest of Java vs Javascript
    x-axis Not a Fan of Java --> Big Fan of Java
    y-axis Not a Fan of Javascript --> Big Fan of Javascript
    quadrant-1 A 
    quadrant-2 B 
    quadrant-3 C 
    quadrant-4 D 
    User1: [0.1,0.9]
    User2: [0.5,0.7]
    User3: [0.3, 0.5]
    User4: [0.1, 0.9]
    User5: [0.9, 0.3]        
    User6: [0.1, 0.3]      