stateDiagram-v2

  [*] --> 初期状態
  初期状態 --> 対象ウィンドウ捕捉準備: 開始ボタン押下
  対象ウィンドウ捕捉準備 --> 対象ウィンドウ捕捉中: フォーカスイベント登録完了
  対象ウィンドウ捕捉中 --> 監視中: ウィンドウ捕捉完了
  監視中 --> 一時停止: 一時停止ボタン押下
  一時停止 --> 監視中: 再開ボタン押下
  監視中 --> 初期状態: 停止ボタン押下
  監視中 --> 完了: 全参加完了済み
  完了 --> 初期状態: 全参加完了済み
