stateDiagram-v2
15: (15) END
14: (14) w = d + d
14 --> 15
13: (13) d = y - x
13 --> 14
0: (0) START
0 --> 1
1: (1) d = 1
1 --> 2
2: (2) a = 2
2 --> 3
3: (3) b = 3
3 --> 4
4: (4) c = 1
4 --> 5
5: (5) x = a + b
5 --> 6
6: (6) y = d + c
6 --> 7
7: (7) y = y + 3 + c
7 --> 8
8: (8) if (y > 5)
8 --> 13
8 --> 9
9: (9) d = x + y
9 --> 10
10: (10) y = y + c
10 --> 11
11: (11) if (y > 10)
11 --> 14
11 --> 12
12: (12) d = d + y
12 --> 14
