stateDiagram-v2
10: (10) END
9: (9) g = e
9 --> 10
8: (8) f = f - 1
8 --> 6
7: (7) e = e + a
7 --> 8
6: (6) while (f > 10)
6 --> 9
6 --> 7
5: (5) f = f + e
5 --> 6
4: (4) f = d + 6
4 --> 5
3: (3) e = d + a
3 --> 4
2: (2) a = 2
2 --> 3
1: (1) d = 1
1 --> 2
0: (0) START
0 --> 1
