stateDiagram-v2
等待品牌审核 --> 品牌审核不通过 : 品牌部审核未通过
品牌审核不通过 --> 等待品牌审核 : 重新提交品牌部审核
等待品牌审核 --> 等待财务部审核 : 品牌部审核通过
等待财务部审核 --> 待领用 : 财务审核通过
待领用 --> 已部分发放+采购中 : 部分发放
待领用 --> 已领用 : 全部发放
已部分发放+采购中 --> 已领用 : 全部发放
已领用 --> 已寄送客户 : 寄送客户
