stateDiagram-v2
    direction TB

    classDef symbol_table_class font-style:italic

    state "Lexical Analyzer" as lexical_analyzer
    state "Syntax Analyzer" as syntax_analyzer
    state "Semantic Analyzer" as semantic_analyzer
    state "Intermediate Code Generator" as intermediate_code_generator
    state "Machine_Independent Code Optimizer" as machine_independent_code_optimizer
    state "Code Generator" as code_generator
    state "Machine_Dependent Code Optimizer" as machine_dependent_code_optimizer
    state "Symbol Table" as symbol_table

    class symbol_table symbol_table_class

    [*] --> lexical_analyzer: character stream
    lexical_analyzer --> syntax_analyzer: token stream
    syntax_analyzer --> semantic_analyzer: syntax tree
    semantic_analyzer --> intermediate_code_generator: syntax tree
    intermediate_code_generator --> machine_independent_code_optimizer: intermediate representation
    machine_independent_code_optimizer --> code_generator: intermediate representation
    code_generator --> machine_dependent_code_optimizer: target-machine code
    machine_dependent_code_optimizer --> [*]: target-machine code
