stateDiagram-v2
    [*] --> cz
    [*] --> gm
    [*] --> jn
    [*] --> ts
    nr --> hq
    xk --> sn
    cl --> xk
    mj --> dq
    mj --> qr
    gm --> lk
    gm --> cl
    mv --> lz
    mv --> rr
    qr --> cz
    qr --> sp
    qr --> lb
    qr --> xt
    qr --> fx
    xt --> vl
    dd --> [*]
    rv --> qr
    ts --> lz
    ts --> nk
    vl --> zj
    vl --> qr
    qm --> db
    qm --> lk
    sn --> lp
    xc --> lz
    jn --> sz
    jn --> ft
    vg --> lk
    vg --> ks
    hq --> ft
    hq --> lh
    lz --> gx
    lz --> xn
    lz --> jq
    lz --> fb
    lz --> ts
    lz --> rr
    nk --> mv
    nk --> lz
    nx --> dd
    sp --> dd
    jj --> qr
    jj --> mj
    sz --> nr
    sz --> ft
    rn --> qm
    cz --> xt
    cz --> qr
    fr --> ft
    vb --> lz
    vb --> xn
    fb --> vb
    hd --> lz
    hd --> xc
    gx --> fb
    db --> mh
    db --> lk
    ft --> jx
    ft --> nx
    ft --> lh
    ft --> pc
    ft --> nr
    ft --> jn
    ft --> kr
    qc --> pl
    qc --> ft
    fx --> bz
    jx --> kr
    pl --> ft
    pl --> fr
    lh --> jx
    rr --> gx
    cc --> dd
    xn --> xl
    kr --> pc
    xl --> dv
    xl --> lz
    dq --> qr
    dq --> rv
    mh --> lk
    mh --> vg
    sb --> lk
    sb --> rn
    bz --> lb
    bz --> qr
    ks --> lk
    qh --> ft
    qh --> qc
    pc --> qh
    lb --> mb
    dv --> lz
    dv --> hd
    mb --> qr
    mb --> jj
    zj --> fx
    zj --> qr
    lp --> sb
    jq --> dd
    lk --> sn
    lk --> cc
    lk --> xk
    lk --> rn
    lk --> gm
    lk --> cl
    lk --> lp
