stateDiagram-v2
  [*] --> READY

  ERROR --> READY: KEEP_ALIVE, ON_LAUNCH, STOP_REC
  ERROR --> RUNNING: START_REC, window_reading

  READY --> ERROR: TIMEOUT
  READY --> RUNNING: START_REC, window_reading
  READY --> ALERT_READY: RAISE_ALERT

  RUNNING --> ERROR: TIMEOUT
  RUNNING --> READY: STOP_REC, ON_LAUNCH

  ALERT_READY --> READY: HANDLE_ALERT
