stateDiagram-v2
   classDef event fill:darkgrey, color:black
   classDef public_api fill:lightgrey, color:black

    [*] --> seizing : seizing date, postponed event, resource-name
    state postponed_event
    state unblocking <<join>>
    state seizing {
        state if_capacity <<choice>>
        [*] --> if_capacity
        if_capacity --> [*] : capacity not defined
        if_capacity --> consuming_capacity : available >0
        if_capacity --> blocked  : available <=0
        consuming_capacity --> actual_seizing
        actual_seizing --> [*]
        }
    blocked --> unblocking
    unblocking --> seizing : unblocked event
    state disposing {
       [*] --> freeing_capacity
       freeing_capacity --> choosing_unblocking_event
       choosing_unblocking_event --> [*]
    }
    disposing --> unblocking
    [*] --> disposing : disposing date, resource-name
