stateDiagram-v2
    [*] --> StartingScheduler : model
    state "Starting scheduler" as StartingScheduler
	  state "Prepare scheduler iteration" as PREPARE
	  state "Middlewares build request" as MDW_REQUEST
	  state "Executing event" as ExecuteEvent
	  state "Middlewares build response" as ISE
    state if_state <<choice>>

	  StartingScheduler --> PREPARE
	  PREPARE --> MDW_REQUEST : current iteration
    MDW_REQUEST --> ExecuteEvent : request
    ExecuteEvent --> ISE : next snapshot
    MDW_REQUEST --> if_state : stop
    ExecuteEvent --> PREPARE : next snapshot
    ISE --> if_state : response
    if_state --> return : stop?
    if_state --> PREPARE : next iteration
    state "Stopping scheduler" as return
    return --> [*] : returns last snapshot
