stateDiagram-v2
[*] --> Получение_SNMP_трапа : trigger
Получение_SNMP_трапа --> Проверка_сообщества_SNMP : Сообщество SNMP получено
Проверка_сообщества_SNMP --> Проверка_консистентности_данных : Сообщество SNMP<BR> прошло проверку
Проверка_сообщества_SNMP --> Запись_ошибки_в_журнал : Сообщество SNMP<BR> не прошло проверку
Проверка_консистентности_данных --> Проверка_данных_на_валидность : Проверка данных на валидность
Проверка_консистентности_данных --> Запись_ошибки_в_журнал : Данные не соответствуют<BR> ожидаемым форматам и типам
Проверка_данных_на_валидность --> Анализ_данных : Данные соответствуют<BR> ожидаемым форматам и типам
Проверка_данных_на_валидность --> Запись_ошибки_в_журнал : Данные не соответствуют<BR> ожидаемым форматам и типам
Анализ_данных --> Включение_порта : Необходимо включить порт
Анализ_данных --> Выключение_порта : Необходимо выключить порт
Включение_порта --> Преобразование_данных_в_формат_JSON : Порт успешно включен
Выключение_порта --> Преобразование_данных_в_формат_JSON : Порт успешно выключен
Преобразование_данных_в_формат_JSON --> Сохранение_данных_в_базе : Данные успешно<BR> преобразованы в JSON
Сохранение_данных_в_базе --> [*] : Данные успешно сохранены в базе
Запись_ошибки_в_журнал --> [*] : Запись ошибки в журнал<BR> успешно выполнена
