---
title: Jinni AI Divination Process Diagram
description: System design and step-by-step process of reading player data and generating images of player avatars
---
journey
    title Jinni AI Divination Process Diagram
    section Aggregate Data
      Store Player Intentions: 5: JINNI API
      LLM Generates Analysis Prompt Based On Intentions: 1: JINNI API, OPEN AI API
      Equip Items: 1: Player
      Conjure Data From Integrations: 3: JINNI API
      Store Player Actions: 3: JINNI API
    section Read Data
      Get Last Divination: 5: JINNI API
      Get Recent Player Actions: 5: JINNI API
    section Analyze Data
      Run Analysis Prompt On Player Actions: 1: JINNI API, OPEN AI API
      Store Analysis Output: 5: JINNI API
    section Generate Image
      Run Augmentation Prompt On Analysis Output: 1: JINNI API, OPEN AI API
      Store DALLE Prompt From Augmentation Output: 5: JINNI API
      Evolve Jinni Using Augmentation Output: 1: JINNI API, OPEN AI API
      Store Jinni Evolution: 5: JINNI API
    section Internalization
      Player Views New Jinni: 1: Player
      Analyze How Actions Affected Jinni: 3: Player
      Player Sets New Intentions: 1: Player