journey
    title Writing a review (Alternativ 1)
    section Enter online shop
        Visit website: 4: User
        Log in: 3: User
    section Go to product
        Navigate to product: 4: User
        Go to Reviews section: 4: User
        Click on "Review": 4: User
    section Write review
        Choose title: 4: User
        Write text: 4: User
        Submit review: 5: User