journey
    title Looking for a specific product (Alternative 1)
    section Enter online shop
        Visit website: 4: User
        Log in (optional): 3: User
    section Look for specific product
        Go to search: 4: User
        Search with text input: 4: User
        Apply filter to search results: 4: User
        Scroll through (filtered) search results: 4: User
        Go to promising product: 5: User
        Read product description: 4: User
        Check out product variants: 4: User
        Read reviews: 4: User
        Decide if product found: 4: User