journey
    title Adding a new wishlist
    section Enter online shop
        Visit website: 4: User
        Log in: 3: User
    section Add wishlist
        Go to my wishlists: 4: User
        Click on "Add wishlist": 4: User
        Choose name: 4: User
        Confirm creation: 5: User