journey
    title Cheyo's Paths as of 2021
    section Pre-Career
      Media Producer: 4: Past Me
    section Career 
      Video Editor: 7: Past Me
      Project Manager: 5: Past Me
      Software Engineer: 7: Current Me
    section Post-Career
      Retired: 3: Future Me