journey
    title Adding a new product that has multiple variants
    section Enter online shop
        Visit website somehow: 4: Employee
        Log in as employee: 3: Employee
    section Add new product
        Click "Add Product": 4: Employee
        Click "Add Variant": 4: Employee
    section Add variant (iteratively)
        Provide name: 4: Employee
        Set visibility: 4: Employee
        Write description: 4: Employee
        Set retail price: 4: Employee
        Set current price (optional): 4: Employee
        Add images: 4: Employee
    section Finish adding product
        Select default variant: 4: Employee
        Add product to categories: 4: Employee
        Click "Submit": 4: Employee