journey
    title Returning an ordered item
    section Enter online shop
        Visit website: 3: User
        Log in: 2: User
    section Initiate return
        Go to my orders: 3: User
        Go to order in question: 3: User
        Select items to return: 3: User
        Create return request: 3: User
        Wait for confirmation: 3: User
        Check return instructions: 3: User
        Print shipping label: 2: User
        Receive refund: 4: User