journey
    title Adding an item to the wishlist
    section Enter online shop
        Visit website: 5: User
        Log in (optional): 3: User
    section Browse online shop
        Scroll through start page: 5: User
        Check out categories: 3: User
        Go to category: 3: User
        Apply filter to category: 3: User
        Scroll through products: 3: User
        Go to product: 5: User
        Read review: 1: User
        Read another review: 5: User
        Check out product variants: 3: User
        Click on "Add to wishlist": 5: User
        Choose wishlist: 5: User