journey
    title Checking my order's status
    section Enter online shop
        Visit website: 4: User
        Log in: 3: User
    section Check order status
        Go to my orders: 4: User
        Go to order in question: 4: User
        Check status: 4: User