%%{init: {'gitGraph': {'mainBranchName': 'master'}} }%%


gitGraph:
  commit
  commit
  commit
  commit
  branch doc_ja_master
  checkout doc_ja_master
  commit
  merge master
  checkout master
  commit
  commit
  checkout doc_ja_master
  commit
  merge master
  checkout master
  commit
  commit
  checkout doc_ja_master
  merge master
  commit
