gitGraph
   commit id: "Initial Commit"
   branch feature
   commit id: "Feature work 1"
   branch bugfix
   commit id: "Bugfix work 1"
   checkout main
   commit id: "Main work 1"
   checkout feature
   commit id: "Feature work 2"
   checkout bugfix
   commit id: "Bugfix work 2"
   checkout main
   commit id: "Main work 2"
   merge bugfix tag: "Bugfix merged"
   checkout feature
   commit id: "Feature work 3"
   checkout main
   merge feature tag: "Feature merged"
   commit id: "Main work 3"